### ISSUE TITLE
Cnchi failed to install a package after tryign all mirrors

### ISSUE THREAD

**Issue by noraj** [Antergos/Cnchi#1009]
### Problem:

I used Anarchy Linux and their CLI installer is blazing fast.

Now I'm using AntergOS with Cnchi and 20min after pressing **Install** I'm still at 2% complete, and the interface seems unresponsiv being updated only each five minutes.

I don't know if it is due to antergos repository and mirrors or if it is cnchi. (Not my internet speed coz I did 5 install with anarchy just before).

Then (while I was writing this issue) I got this error pup-up: 

> "Can't download needed packages. Cnchi can't continue."
>
> Please reference the following number when reporting this error: None

It occurred during the "Fetching lib32-gcc-libs (21/833)".

So now after I read logs I know this is because:

```
2018-09-03 21:50:41 [ERROR] download_requests.py(202) start(): Can't download lib32-gcc-libs-8.2.1+20180831-1-x86_64.pkg.tar.xz, even after trying all available mirrors
2018-09-03 21:50:41 [ERROR] process.py(130) run(): "Can't download needed packages. Cnchi can't continue."
```

### Steps To Reproduce:

I don't know if it is reproducible yet.

### Log Files

- Link to /tmp/cnchi.log output. https://paste2.org/6kXfkw42
- Link to /tmp/postinstall.log. None

**Comment by karasu** [comment]
Hi @noraj , thanks for reporting this one.

You've just been caught between updates... I'm sure if you try again in a few hours it will work (at this exact time,  gcc-libs is being updated to version 8.2.1 in my computer... so it's normal it wasn't in the mirrors you've tried).

To be honest, when Cnchi says that can't find <name> package in all mirrors, it really means in all mirrors that it has tried, not in all existing mirrors...

This is what happens with an online installer... it's a PITA but we want to have the latest packages when installing.

Thanks!
