### ISSUE TITLE
Cnchi stops progress after mirror ranking

### ISSUE THREAD

**Issue by moonlies** [Antergos/Cnchi#1073]
**Describe the bug**
Cnchi seems to stop after successfully ranking mirrors automatically. The progress bar remains at 100%, "Cnchi ist still updating and optimizing your mirror lists.".

**To Reproduce**
1. Download latest antergos minimal iso.
2. Put it onto USB with ddrescue
3. Boot into antergos
4. Run installation
5. Select automatic mirror ranking
6. wait...

**Expected behavior**
The installation should proceed.

**Log Files**
- Link to /tmp/cnchi.log output: https://paste2.org/fa3Gh3Cx

**Additional context**
 - Installation on a Shuttle by Shuttle Inc.
 - Network connection via USB-Tethering

**Comment by kebabliminator** [comment]
Same issue here. Tried uninstalling cnchi via pacman and using cnchi-dev instead, which let me get a bit further but only because it doesn't rank mirrors until later.
