### ISSUE TITLE
Libre Office package cannot be found

### ISSUE THREAD

**Issue by MinecraftPlaye** [Antergos/Cnchi#1085]
**Describe the bug**
Cnchi fails when selecting locale en-GB at the step to download libreoffice.

**To Reproduce**
1. Start the installation process
2. Choose en-GB as language/region
3. Choose LibreOffice for the installation

**Expected behavior**
I expected Cnchi to install AntergOS with LibreOffice.

**Log Files**
- https://pastebin.com/WfybcSTg

**Additional context**
Beforehand I uncommented the _[mulilib]_ keyword and the _include_ line for it in the _/etc/pacman.conf_ in order to work around some lib32-mesa problems.
`2018-09-11 19:09:40 [ERROR] metalink.py(126) create(): Can't find these packages: lib32-mesa
`

**Comment by karasu** [comment]
Should be fixed in 0.16.x
Closing.
