### ISSUE TITLE
Cannot create download package list (metalinks)

### ISSUE THREAD

**Issue by Wulfex** [Antergos/Cnchi#1086]
**Describe the bug**
On the last step of installing Antergos, I recieve the following error:
'Cannot create download package list (metalinks)'
'Please reference the following number when reporting this error: [blank]'

Things I've tried:

- disabling all extra packages
- downloading the github version
- running 'pacman -Syy' before running Cnchi.

**To Reproduce**
1. Go through all the installation steps
2. On the last page to create a username and password, receive error.

**Screenshots**
![image](https://user-images.githubusercontent.com/26010409/45391863-39cae700-b614-11e8-88b1-3f7671fbdee5.png)

**Log Files**
- Link to /tmp/cnchi.log output
[https://pastebin.com/embed_js/MSmfxdkz](https://pastebin.com/embed_js/MSmfxdkz)
- Link to /tmp/cnchi-alpm.log output
[https://pastebin.com/0pFQyNgy](https://pastebin.com/0pFQyNgy)
- Link to /tmp/postinstall.log output
 N/A (Empty)

**Comment by Wulfex** [comment]
For context, I'm running the live image on a USB 2.0 Thumb drive.

**Comment by keponk** [comment]
Same here while trying to make a new install from usb.

* Used `dd` option to create USB
* Chose usb drive from boot menu
* Antergos menu presented with several boot option
* Choosing the `live (usb)` boot fails with a message saying unable to find EFI
* Only working boot option is `live (cd/dvd)` 
* boot into the system, try to install, same error as OP

**Comment by znmeb** [comment]
I've seen all kinds of mysterious errors in cnchi today ... mirrorlist hangs, this crash, and a couple others. I think either they shipped a bad cnchi or something's corrupted on the server :-(

**Comment by znmeb** [comment]
I switched from the September ISO to the August one and things all worked!!

**Comment by ehakan** [comment]
Manually updating cnchi with `$ sudo pacman -S cnchi --force` worked for me. The current ISO comes with 0.14.475 and the automatic updater does not download 0.14.477.

I think #1083 still persists in 0.14.477 but manually selecting the mirrors too is a valid workaround.

**Comment by Wulfex** [comment]
@ehakan That worked for me! Thank you!
