### ISSUE TITLE
System freeze using Live ISO

### ISSUE THREAD

**Issue by MinecraftPlaye** [Antergos/Cnchi#1087]
**Describe the bug**
At random points, sometimes while clicking through the installer, sometimes while having the terminal opened or sometimes when the system just started, everything freezes and I can't do anything except for a hard reset (5s power button).

**To Reproduce**
1. Download antergos-18.9-x86_64.iso or antergos-18.8-x86_64.iso and verify it.
2. Create an installation media (in my case using rufus on Windows and a USB 3 Thumb drive).
3. Start the installation media and wait... (see _additional context_ and _note_)
4. Linux freezes entirely...

**Expected behavior**
Be able to use the Live ISO in order to install AntergOS on my laptop.

**Log Files**
- There are no log files available... As soon as the problem occures there is no way for me to access any log files anymore.

**Additional context**
I'm using an Lenovo Thinkpad T480s (2018, model number: 20L8S02E00) with an Intel® Core™ i7-8550U and a NVIDIA® GeForce® MX150. The laptop also got a Samsung SSD. Windows 10 has already been installed and SecureBoot has been disabled for the purpose of installing Linux.

**Note:** The problem only occured using my Laptop or the laptop of a friend (same model). My other devices aren't affected. As I haven't gotten to the point of getting AntergOS running on the laptop, I don't know if AntergOS in general or only the LiveISO is affected.

**Comment by MinecraftPlaye** [comment]
Seems like the 18.4 iso isn't affected by this problem, so something which changed between those (18.4 and 18.8/18.9) iso's causes the issue. Using the latest cnchi (via auto-update) on 18.4 also doesn't cause this error.

**Comment by gchamon** [comment]
Also having problems with mx150. Probably issues with nouveau drivers, but I can't seem to disable it on live usb

**Comment by gchamon** [comment]
I successfully booted into a stable live session by pressing `e` on antergos boot selection and adding `modprobe.blacklist=nouveau` right where the configurations start
