### ISSUE TITLE
Installation fails with encryption enabled 

### ISSUE THREAD

**Issue by MinecraftPlaye** [Antergos/Cnchi#1090]
### Problem:
Whenever I try to install antergos with encryption enabled, cnchi fails to install the bootloader grub2.

### Steps To Reproduce:
1. Install Antergos with a custom partition setup.
2. Enable to encrypt the root and home partition (not boot /efi)
3. See error.

### Log Files
- cnchi.log: https://gist.github.com/MinecraftPlaye/ea439212e665690323b8c00af1647e18

### Additional Notes:
I'm trying to install antergos in a dual boot scenario with windows on the same disk.

**Comment by karasu** [comment]
Hi,

In fact, it does not fail to install the bootloader. See https://github.com/Antergos/Cnchi/issues/1098

I'll close this as it is the same bug. Thanks for reporting this!
