### ISSUE TITLE
cnchi compromised?

### ISSUE THREAD

**Issue by killajoe** [Antergos/Cnchi#1091]
![Alt Text](https://i.imgur.com/d8XIZiu.png)
![Alt Text](https://i.imgur.com/RI3EGJQ.jpg)

references:
https://forum.antergos.com/topic/10654/ads-in-the-installer-instead-of-the-typical-slides
https://forum.antergos.com/topic/10653/phishing-popup-in-cnchi-followed-by-crash/18

**Comment by Invisi** [comment]
There's some obfuscated code at `https://antergos.com/cnchi-installer-slideshow` which includes `stat.js` from `https://examhome.net`, it might be the culprit and seems to be down now.    
Domain was registered yesterday (2018-09-15T09:56:56Z) and uses nameservers at *.bitcoin-dns.hosting.

**Comment by rjmill** [comment]
Interesting, I ran across issues with the Antergos website earlier today, and tracked them down to some scripts from `cdn.examhome.net` (which weren't loading.)

Is the antergos.com website's code available anywhere? I couldn't find anything obvious in the Antergos github org. When I googled `examhome.net`, it brought up a bunch of other websites pointing to it, so I expect it's something along the lines of a compromised wordpress plugin.

**Comment by karasu** [comment]
>I expect it's something along the lines of a compromised wordpress plugin.

Yes, that was it. We disabled the compromised pluguin, while we try to fix it... If you go to antergos.com you will see some strange artifacts, and the download page is disabled.

Fortunately, our ISO was never compromised, as it is stored in another server.

**Comment by killajoe** [comment]
I do not get this with 18.8 ISO, and also not with 18.9, but i do have a proper secured system in front of my home network ;)

**Comment by karasu** [comment]
I decided to ditch the webkit component here and just use some local images that fade in and out. Is not as fancy but it just works. Already included in 0.15.x

**Comment by killajoe** [comment]
https://forum.antergos.com/topic/10658/no-info-in-regard-to-possible-compromise

Would be good to have a statement/clearyfication on the forum ;)
