### ISSUE TITLE
Installer gets stuck when installing in Quebec

### ISSUE THREAD

**Issue by SpectralMemories** [Antergos/Cnchi#1093]
**Describe the bug**
The cnchi installer displays a blank page on the "Select your timezone" section, with no possibility to go forward with the installation

**To Reproduce**
1. Boot antergos live CD
2. Launch the cnchi installer while in Quebec
3. Select your parameters
4. Get stuck on a blank page

**Expected behavior**
A map appears to select your timezone

**Screenshots**
[Screenshot](https://imgur.com/a/n9B7afO)

**Log Files**
[- Link to /tmp/cnchi.log output.](https://pastebin.com/fdiqNYpM)
- Link to /tmp/cnchi-alpm.log output: missing
- Link to /tmp/postinstall.log output : empty file

**Additional context**
Installed in a BIOS VM (virtualbox) with Arch 64bits presets. No proxy used

**Comment by karasu** [comment]
@SpectralMemories Could you please try again with version 0.16.1 ?
Just run the iso in a VM like you did, and wait for Cnchi to be updated... if for any reason it does not update, please update it yourself:
```
sudo pacman -Syy
sudo pacman -S cnchi
```
Thanks!

**Comment by SpectralMemories** [comment]
I still have the 0.14.475 cnchi, and running your pacman commands do not update it, I get File /var/cache/pacman/pkg/cnchi-0.16.1-1-any.pkg.tar.x.z is corrupted (invalid or corrupted package (PGP signature)). Do you want to delete it  (Y/n)
Answering either Y or n leads to a pacman error.

**Comment by Nepoxx** [comment]
I had this issue, it's fixed on 0.16.2 (now I'm stuck on "installing bootloader" :( )

**Comment by karasu** [comment]
@Nepoxx fixed in 0.16.3
Closing...
