### ISSUE TITLE
Enable parallel compilation by default

### ISSUE THREAD

**Issue by DanySK** [Antergos/Cnchi#1103]
**Is your feature request related to a problem? Please describe.**

Especially for installations using AUR helpers, it is frustrating to wait long times for package compilation, which is by default executed with a single job. Packages requiring a single-threaded compilation usually specify `-j` as option in `MAKEFLAGS`, making default parallel compilation viable and reliable.

**Describe the solution you'd like**
I propose to produce a default `/etc/makepkg.conf` where there is the following line, uncommented:
```bash
MAKEFLAGS="-j$(nproc)"
```
This would enable compilation with as many jobs as logical processors.

**Additional context**
I tested this with a "heavy" package as `kodi-pre-release`, and found the feature very beneficial.

**Comment by karasu** [comment]
Done in https://github.com/Antergos/Cnchi/blob/0.16.x/src/installation/post_install.py

Thanks!

**Comment by DanySK** [comment]
Grand, thanks
