### ISSUE TITLE
Minimal installation still requires 16gb like the full installation

### ISSUE THREAD

**Issue by mihaeu** [Antergos/Cnchi#1111]
**Describe the bug**
Minimal installation requires 16gb of disk space even though that's much more than the actual installation needs. This is a problem when using Antergos for small virtual boxes (which was my intent).

**To Reproduce**
1. Create a Virtual Box image with 10gb of disk space
2. Download and insert Antergos Minimal ISO
3. Start Cnchi
4. After selecting the language, one cannot continue to the third step because of the "minimal" requirements

**Expected behavior**
Realistical minimal requirements for a minimal installation (probably 5gb would still be more than enough)

**Screenshots**
![2018-11-04 12_36_51-window](https://user-images.githubusercontent.com/2168701/47964181-1598ee80-e036-11e8-8aca-daffd2a5975e.png)
![2018-11-04 12_37_11-window2](https://user-images.githubusercontent.com/2168701/47964182-17fb4880-e036-11e8-8627-559a7e35ca56.png)

**Log Files**
n/a

**Additional context**
n/a

**Comment by karasu** [comment]
Hi,

Close cnchi, open a terminal and run:
`sudo -E cnchi -dvn`

`d` for debug, `v` for verbose and `n`for skip testing (so the "16GB free" rule won't be mandatory, just press the > button)

**Comment by mihaeu** [comment]
Thanks, that works  :+1: 

Would it be worth fixing this?

**Comment by karasu** [comment]
Yes, I'll revert that change and go back to asking for 8GB
