### ISSUE TITLE
enable Wifi printer setup for new installations

### ISSUE THREAD

**Issue by killajoe** [Antergos/Cnchi#1118]
https://forum.antergos.com/topic/11189/wifi-printer-setup-for-new-installations

Avahi scans for wifi printers & provides local hostname resolution using nss-mdns package. 

Enable it as follows:

Install nss-mdns

Edit /etc/nsswitch.conf and change the hosts: line to include the following (inserted right before resolve and dns):

`mdns_minimal [NOTFOUND=return]`

Add user to sys

`sudo usermod -a -G sys [username]`

This could be added if user select printer support, and it will make it possible to add also network printers by default.

references:
https://wiki.archlinux.org/index.php/CUPS#Network
https://wiki.archlinux.org/index.php/Avahi#Hostname_resolution

**Comment by robgriff444** [comment]
I have to set this up, as above, manually every time I install Antergos even though I choose printer support in cnchi. My printer is Canon Pixma TS3100 but I don't think any wifi printers will work without the above changes.
