### ISSUE TITLE
Suggestion to avoid errors of packages in repositories during install

### ISSUE THREAD

**Issue by Portergos** [Antergos/Cnchi#1128]
Hi!
What about a packages.xml directly from Antergos comunnity as an option inside cnchi (one that moderators are free to change).

This would be like a workaround to avoid those packages that are renamed or are removed from repo from official packages.xml, causing the install to fail.

We know these errors are pushing people away from using Antergos, multiples unsussessfull installs.

Not sure if i made the idea clear enough…

Or maybe a command line option like `sudo cnchi --package-list /home/antergos/comunnity_package_list.xml`

**Comment by lots0logs** [comment]
Hi! Two things to note:

1. What you describe is already possible. 
2. Cnchi always downloads the packages.xml file from github, this it always uses the latest version.

**Comment by Portergos** [comment]
Nice! How can i direct cnchi to use an alternative packages.xml?

**Comment by lots0logs** [comment]
`sudo cnchi -p /home/antergos/comunnity_package_list.xml`

**Comment by Portergos** [comment]
Thanks!
