### ISSUE TITLE
~/.bashrc.aliases has problematic aliases

### ISSUE THREAD

**Issue by manuel-192** [Antergos/Cnchi#1133]
### Problem:
Some aliases (that will be added for all users including root) have problematic aliases defined in **~/.bashrc.aliases**.
Aliases that simply add **sudo** to a program name cause unexpected results.
Examples of problematic aliases:
alias systemctl='sudo systemctl'
alias journalctl='sudo journalctl'

### Steps To Reproduce:
1. Install Antergos
2. Log in as a normal user, start a terminal
3. Use any of the problematic aliases, e.g. **systemctl status lightd** (and press Tab key to expand)

### Log Files
N/A

### Additional Notes:
Using **sudo** in aliases this way should be avoided, not all commands work well with it.

Fortunately, this one is quite simple to fix.

**Comment by karasu** [comment]
@lots0logs likes them... :grin: I'll let him decide as it was him who added them.

**Comment by manuel-192** [comment]
Added a bit more info to problem description (step 4). So this problem shows itself especially on new installs.
But the alias with sudo causes other issues, e.g. with the --user option.

**Comment by lots0logs** [comment]
Considering the amount of time we've had them there and the fact that this is the first time it has come up as an issue I think the majority of people find them useful. Until such time that no longer appears to be the case we'll keep them. We can reopen this later if warranted.

**Comment by manuel-192** [comment]
I must disagree with this decision.
For me personally it is not a big problem since I can fix it locally, but many newcomers can be in trouble till they realize this is the reason for the odd behavior of some commands.
