### ISSUE TITLE
Package gamin moved to AUR, cnchi fails

### ISSUE THREAD

**Issue by manuel-192** [Antergos/Cnchi#1141]
### Problem:
Package **gamin** is moved to AUR, and that makes cnchi installer to fail when it checks available packages.

### Steps To Reproduce:
1. Try to install Antegos
2.
3.

### Log Files
N/A

### Additional Notes:
A workaround is to remove references to **gamin** and **xorg-mkfontdir** in **/usr/share/cnchi/data/packages.xml** and restart cnchi (as root):
<pre>
cnchi -p /usr/share/cnchi/data/packages.xml
</pre>

Note that the similar old xorg-mkfonfdir issue has come up again!

**Comment by karasu** [comment]
https://github.com/Antergos/Cnchi/commit/ad172e62c22017ec34980f5375e697331cd7d2bf
