### ISSUE TITLE
Anteregos Deepin DE - error deepin-grub2-themes package

### ISSUE THREAD

**Issue by Davidone97** [Antergos/Cnchi#1142]
**Problem:**

When I try to install Anteregos with the desktop enviroment Deepin, I always have this error towards the end of the installation. How can I do?

**Screenshot:**
![Alt Text](https://i.postimg.cc/jqWwJ2PS/IMG-20190327-223926.jpg)

**Comment by killajoe** [comment]
<pkgname>deepin-grub2-themes</pkgname> still in packages.xml

**Comment by Davidone97** [comment]
And?

**Comment by karasu** [comment]
@Davidone97 edit your data/packages.xml file, delete that deepin-grub2-themes line and rerun cnchi this way: `sudo -E cnchi -p /usr/share/cnchi/data/packages.xml`

**Comment by Davidone97** [comment]
> @Davidone97 edit `/usr/share/data/packages.xml` file, delete that deepin-grub2-themes line and rerun cnchi this way: `sudo -E cnchi -p /usr/share/cnchi/data/packages.xml`

Thank you for your help.
