### ISSUE TITLE
wpa_actiond moved to AUR, cnchi fails

### ISSUE THREAD

**Issue by manuel-192** [Antergos/Cnchi#1148]
### Problem:
Package **wpa_actiond** seems to have been moved to AUR. This makes Antergos installer to fail.

### Steps To Reproduce:
1. Try to install Antergos.
2. cnchi fails because of missing wpa_actiond.

### Log Files
N/A

**Comment by killajoe** [comment]
https://www.archlinux.org/packages/extra/x86_64/wpa_actiond/

**Comment by kebrx** [comment]
I've submitted a PR to antergos-packages to include wpa_actiond in the antergos repo.

**Comment by lots0logs** [comment]
The wpa_actiond package is no longer necessary. I already removed it from the package list. 

Ref: https://bugs.archlinux.org/task/61934
