### ISSUE TITLE
Installing MATE fails because of dependencies of package mate-mint-menu

### ISSUE THREAD

**Issue by manuel-192** [Antergos/Cnchi#1150]
**Describe the bug**
Cnchi fails when installing MATE. The reason is that a dependency **python2-keybinder2** of **mate-mint-menu** is now in AUR.

**To Reproduce**
1. Try to install Antergos with MATE.
2. Install fails with a problem with package mate-mint-menu.

**Expected behavior**
MATE installs properly.

**Screenshots**
N/A

**Log Files**
N/A

**Additional context**
A workaround to have it installed is to remove package mate-mint-menu (and some other packages) from packages.xml. But then there is no menu on the taskbar.

**Comment by killajoe** [comment]
still a bug.

**Comment by manuel-192** [comment]
MATE users could use **brisk-menu** instead.
