### ISSUE TITLE
Add full LVM support in advanced install

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#13]
Add full LVM support in advanced install

**Comment by Swipe650** [comment]
Do you have any plans to allow the advanced mode option in Cnchi to see inside a pre-created LVM VolumeGroup and chose an existing root and home partition to install to? 

The other option would allow the user to some choice of root and home partition size when opting for the Antergos LVM option.

**Comment by karasu** [comment]
Hi,

In advanced you should be able to select a pre-created lvm. Please, tell us
if it's not working for you.

El dilluns, 16 de maig de 2016, Swipe650 <notifications@github.com> va
escriure:

> Do you have any plans to allow the advanced mode option in Cnchi to see
> inside a pre-created LVM VolumeGroup and chose an existing root and home
> partition to install to?
>
> The other option would allow the user to some choice of root and home
> partition size when opting for the Antergos LVM option.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Antergos/Cnchi/issues/13#issuecomment-219430163>
>


-- 
Enviat amb el meu Iphone

**Comment by Swipe650** [comment]
Ah ok, I didn't realise that. Thanks

**Comment by stratus-ss** [comment]
This is a very old issue that I cannot reproduce. @Swipe650 if you still have problems please feel free to let us know and we can reexamine it
