### ISSUE TITLE
better pac.py error handling 

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#139]
I know the plan is to ultimately get download.py to a working state but I think fixing pac.py error handling goes with that goal :wink: 
<img src="http://antergos.info/noooo.png" />

I forgot to grab the damn log file before closing the VM :unamused:

**Comment by karasu** [comment]
A lot of debugging messages are going to cnchi.log from pac.py in 0.8, so this will help us debug possible failures. I'll leave this open because I think that the exception handling in pac.py should be improved to catch all this possible errors in a nice way for the user.
