### ISSUE TITLE
Integrate 'installation finished' on main window

### ISSUE THREAD

**Issue by faidoc** [Antergos/Cnchi#143]
Testing design

![cnchi-finish2](https://f.cloud.github.com/assets/331390/2347838/0281cf4e-a551-11e3-9d54-6da166025c67.png)

**Comment by karasu** [comment]
I did not implement this as I don't see the usefulness of it. Instead, I prefer a modal window showing that the installation has finished. Go figure.... Anyway, if somebody feels doing it, I'm not against it.
