### ISSUE TITLE
Not installing bootloader in advanced messes up Windows 7 MBR

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#145]
If you don't check the checkbox to install a grub bootloader to the HDD in advanced install, it actually messes up the Windows 7 MBR.

**Comment by lots0logs** [comment]
Testing referencing dev repo when fixing bugs. Please disregard. 

Fixed in lots0logs/cnchi-dev@1e49c15595b9b31fbc0b8b214b5d54854934f8ba

**Comment by karasu** [comment]
Closing this. If it's reported again we can reopen it.
