### ISSUE TITLE
Clarify the location screen message

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#146]
"Can you make it so that in cnchi I can select my country even though I chose english?
because right now I'm forced to select dutch or I can't get netherlands in the country list.(which is not helpful with logs....)"

http://forum.antergos.com/viewtopic.php?f=5&t=1488

**Comment by juancarlospaco** [comment]
Hello, I think I have the same Bug, at least a usability bug, this is my description, this is what I need:

- Country: Argentina.
- Language: English.
- Keyboard: English.
- Time Zone: UTC -3  Argentina/Buenos Aires
- Money: Argentine Peso.
- Units: Metric

I pick Argentina and it sets to Spanish with Spanish keyboard.
I pick USA it sets to Imperial and US Dollars.

:octocat:

**Comment by karasu** [comment]
Hi @juancarlospaco ,

I see your point. Help me with this one, please.

In your case, I think you should select:
- Language: English
- Country/Territory/Area: Spanish(AR)/Argentina (click "show all locations")
- Timezone: Argentina/Buenos Aires 
- Keyboard: English (US)

Cnchi selects Spanish keyboard if you choose Argentina, but it's only a suggestion.

With the options above, is everything all right? I mean,  is your system using metric and Argentine Peso?

Thanks!

**Comment by juancarlospaco** [comment]
Some desktops dont care about Metric and Argentine Peso, so may or may not be reproducible,
but for example KDE Plasma 5 does, its Apps too.

I clicked "show all locations"
Language: English
Country/Territory/Area: Spanish(AR)/Argentina

I end up in a Spanish desktop, I dunno why, I am testing on Virtualbox, from an official ISO of yesterday.
I pick KDE Plasma 5 as desktop but the CLI stuff is also Spanish. Keyboard is English.

**Comment by karasu** [comment]
Hi,

Can you put here the result of issuing the "locale" command in a terminal? Thanks!

**Comment by juancarlospaco** [comment]
![bug_local](https://cloud.githubusercontent.com/assets/1189414/12622830/f6782f32-c505-11e5-85dc-81dc2437e0d6.jpg)

Sorry its an screenshot, but basically is all `ES_AR.UTF-8`, you can see UI is spanish.
And `LC_ALL= ` empty, I dunno if thats bad ?

**Comment by karasu** [comment]
Thanks!

So it is clear now that location sets the language, numeric, monetary... everything.

I'm afraid Cnchi does not support this atm. We'll work on this. Thanks!

LC_ALL can be empty, do not worry (if it's not then it's value overrides all the other ones).
