### ISSUE TITLE
Add a 2nd progress bar on the install page showing  # of packages downloaded out of the total # needed to download

### ISSUE THREAD

**Issue by heavensrevenge** [Antergos/Cnchi#182]
On the "Installing Antergos" screen where the packages are downloaded one by one, each package uses 100% of the single progress bar in this stage.
Since packages are added to a "transaction" and populated in pac.py, can you add a 2nd separate progress bar above the one already present which shows the total download progresses as a % based on the packages downloaded so far/total packages needing to be downloaded or a (15/744) indicator?

That single progress bar isn't very telling on how much longer the download stage will approximately last and that would be my wish for this release to help make the install process a bit more clear.

**Comment by heavensrevenge** [comment]
Did you implement this @lots0logs ? :)

**Comment by lots0logs** [comment]
@karasu did it actually, it will be in v0.8 which is soon to be the new stable version :smile:

**Comment by heavensrevenge** [comment]
Well @lots0logs the addition is appreciated regardless of who actually wrote the code, so thank you for this :)
