### ISSUE TITLE
Error in line 1128 for UEFI

### ISSUE THREAD

**Issue by eeickmeyer** [Antergos/Cnchi#186]
txt = _("EFI ( /boot )")

Should read

txt = _("EFI ( /boot/efi )")

**Comment by xidoc** [comment]
I have a problem with /boot.
I would like to install antergos but I have an error in the grub.
When I go to see my settings bios, Antergos is not visible. I don't understand.
I installed manjaro with boot/efi as option, and it's work.
I am not a expert but I think boot/efi  is good for me.

**Comment by lots0logs** [comment]
The mount point has no effect on whether or not your system can boot. Please create a post in our forum so that we can assist you in resolving your issue. I'm closing this as a non-issue. If that changes at any point in the future we can reopen it.

**Comment by eeickmeyer** [comment]
@lots0logs I understand the rationale, but (and this might be a failure on my part), I did install the latest Antergos iso on my system (using /boot for my ESP) and it failed to boot. The ability to specify whether or not it mounts to /boot or /boot/efi in the advanced partitioned is still not there.

That said, I think Antergos is a great distro, you're doing a great job, but implementation for UEFI systems is an area where it's failing in a spot where few other distros fail.

**Comment by 13xforever** [comment]
Why was this issue closed? You still can't override the option, I still can't install it on my system (my ESP partition is only 200 MB, I can't put kernels in there, and I can't repartition my SSD without losing the data).
