### ISSUE TITLE
Error if root partition is already mounted

### ISSUE THREAD

**Issue by Holzhaus** [Antergos/Cnchi#218]
Cnchi always wants to format the root partition, but it can't if it's already mounted (e.g. due to a previous installation attempt that has been canceled).

This should be fixed, e.g. checking if the drive is mounted and unmounting it if that's the case.

Tested with antergos-2014.05.26-x86_64.iso.

**Comment by karasu** [comment]
Our recommendation is simply to reboot to avoid problems after a failed installation. There are cases that root can't be unmounted automatically because there're still processes using it.
