### ISSUE TITLE
[cli-installer] Kernel image not generated if custom mkinitcpio is empty

### ISSUE THREAD

**Issue by Holzhaus** [Antergos/Cnchi#219]
When installing Antergos, I accidently clicked the button to customize the mkinitcpio.conf. Because I didn't want to make any changes, I just closed the file and continued. Unfortunately, because of that, no kernel image was generated, leaving the system unbootable.

I had to chroot into the system, run mkinitcpio and update grub. This should not happen. If mkinitcpio.conf is empty, Cnchi should just use the default mkinitcpio.conf.

Tested with antergos-2014.05.26-x86_64.iso.

**Comment by karasu** [comment]
We're sorry but we're no longer maintaining the cli version of the installer. If you have any issues using the graphical post please open a new issue.
Thanks!
