### ISSUE TITLE
[0.6.11] Frozen at "Configuring your new system"

### ISSUE THREAD

**Issue by chrisvella** [Antergos/Cnchi#223]
File "./src/slides.py", line 199, in manage_events_from_cb_queue
    show.fatal_error(event[1])
  File "./src/show_message.py", line 42, in fatal_error
    error(message)
  File "./src/show_message.py", line 53, in error
    msg_dialog.format_secondary_text(message)
  File "/usr/lib/python3.4/site-packages/gi/overrides/Gtk.py", line 548, in format_secondary_text
    self.set_property('secondary-text', message_format)
TypeError: Must be string, not FileNotFoundError

Was not able to open a new terminal to grab the cnchi tmp log.

lscpu
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            21
Model:                 48
Model name:            AMD A10-7850K APU with Radeon(TM) R7 Graphics
Stepping:              1
CPU MHz:               1700.000
CPU max MHz:           3700.0000
CPU min MHz:           1700.0000
BogoMIPS:              7389.43
Virtualization:        AMD-V
L1d cache:             16K
L1i cache:             96K
L2 cache:              2048K
NUMA node0 CPU(s):     0-3
```

**Comment by stratus-ss** [comment]
The pastebin has been removed. Its hard to diagnose without logs

**Comment by lots0logs** [comment]
I am pretty sure this was fixed. If it turns up again we can reopen the issue.
