### ISSUE TITLE
Version 0.6.40 Fails to properly install the bootloader on UEFI Devices

### ISSUE THREAD

**Issue by WokSearedBacon** [Antergos/Cnchi#232]
My hardware is the Dell XPS 13 9333, with UEFI Secure Boot disabled.

While 0.6.12 Properly installed the Grub-efi bootloader on my computer, when installing with the 6.16 revision it seems that Cnchi fails to install the bootloader entirely, and the Antergos_Grub boot option doesn't even show up in the installed boot options as it does with 0.6.12. 

For clarity, I had set up my SSD's partition table the same way across both versions, with the /boot partition formatted as FAT32 and sized at 300MB. I have my BIOS setup so that it would allow the Bootloader Firmware to be installed- and had seen the 0.6.16 installer complete with no apparent error messages.

**Comment by vamega** [comment]
Hi.

This is still an issue, I just attempted to perform an install on the my Dell XPS 13 9333 as well. Secure boot was disabled. I was running Cnchi 0.6.45 I think.

I have my installer log at https://gist.github.com/6fee88fcd147248b78b1.
Seems to fail at the grub-install command. I was able to run that manually and have things work.

**Comment by WokSearedBacon** [comment]
Have you tried 'cnch-dev' at all? The current version of Cnchi has this issue fixed.

**Comment by WokSearedBacon** [comment]
As it turns out on my XPS 13 hardware, I am seeing this same missing bootloader issue on 0.6.40 yet again, with the same setup on which I had installed to successfully in recent versions. I'll check the logs and code ASAP.

**Comment by WokSearedBacon** [comment]
Would this have anything to do with downtime on our servers?

**Comment by WokSearedBacon** [comment]
Here are a few logs for the installation: 
/tmp/cnchi.log                                            http://ur1.ca/jjfi3
/tmp/pacman-boot.log                              http://pastebin.com/L5z82HRY

**Comment by lots0logs** [comment]
From the output that was logged, it appears that the grub install was successful. I see no indication of a problem. What happened when you rebooted after this installation?

**Comment by WokSearedBacon** [comment]
(Excuse the delay) After I installed with Cnchi (seemingly successfully) and restarted my computer it would only boot to the live media, even with the SSD OS given 1st boot priority. when I look through the UEFI listings after reboot I also don't see the 'antergos_grub' entry (or any new entries), when my setup would allow new UEFI entries to be added.

**Comment by lots0logs** [comment]
That's very strange. The logs indicate that the grub-install command completed without any errors. We'll have to wait for further testing or additional reports from users.

**Comment by lots0logs** [comment]
I am pretty sure this was fixed. If it comes up again we can reopen it.
