### ISSUE TITLE
GDM in Gnome

### ISSUE THREAD

**Issue by prescott66** [Antergos/Cnchi#245]
What about to replace lightdm with GDM at least in Gnome edition? It fixes problem with screensaver and unlocking pc after resume from sleep.

**Comment by anicake** [comment]
If you take a poll for this from all the people who love and stand by Antergos (including me) I would say you will get a categorical 'YES' on a question like "Does LightDM feel awkward as an entry for GNOME DE?"

**Comment by lots0logs** [comment]
Perhaps, but we'd get the same categorical 'YES' if we asked "Does GDM feel awkward as an entry for KDE/Cinnamon/Openbox/Insert-another-desktop-here".
