### ISSUE TITLE
In advanced mode lvm is not in the initcpio

### ISSUE THREAD

**Issue by ial-su3** [Antergos/Cnchi#256]
So after my initial and wrong pull request, I had another look.

It appears the "use_lvm" setting is in never set in advanced mode, even if root is on lvm.

**Comment by axaxs** [comment]
This is closer but not correct.  The setting you are looking for is blvm,
not use_lvm, at least for 'advanced' installs.

To my understanding, lvm2 only needs added to modules if boot partition is
lvm.  Is that not correct?  Based on your setup, you had /dev/sda1 as /boot
and lvm as /.  So does lvm2 still need to be added in this setup?

**Comment by ial-su3** [comment]
Yes, if root is on an lvm volume the initcpio must have lvm2 hook enabled to be able to detect and mount the root filesystem.

**Comment by axaxs** [comment]
Thanks, this helps a lot.  So your first change was on the right track.  If
you want to work on the pr, change the logic to(pseudocode) -

if "/" or "/boot"
    self.blvm = True
    if noboot:
        rest of logic about setting flags
