### ISSUE TITLE
English keyboard after installation in Gnome

### ISSUE THREAD

**Issue by prescott66** [Antergos/Cnchi#258]
In Cnchi installer i have selected slovak language and keyboard too, but after installation i have english selected in Gnome. it should by slovak default. Maybe you should think about integrating gnome-initial-setup tool, where can user configure basic things like these.

**Comment by Davidlinuxx** [comment]
A mí me pasó algo parecido, pues al instalar a pesar de que he probado con teclado español y Latinoamérica, una vez instalado me carga (como por defecto) el teclado de USA. Por ejemplo me impide escribir tíldes. (en este momento las escribo desde la versión Live a ver si pinchando en algún lado me carga como debe ser).

**Comment by I3ck** [comment]
same issue here
both when using the openbox and gnome version (german keyboard settings)

**Comment by karasu** [comment]
That's strange. I use a Spanish layout and works flawlessly here.

OK, as a workaround, create a text file in /etc/X11/xorg.conf.d named 10-keyboard.conf (if you don't have it) and setup your keyboard there. Mine looks like this:

```
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "es"
        Option "XkbVariant" "cat"
        Option "XkbModel" "pc105"
EndSection
```

You must change it to match your layout, of course.

We will do some checks on this asap.

**Comment by I3ck** [comment]
If I recall correctly, those settings were correct (it read "de" there)
what actually fixed my problem was:
localectl set-keymap de
setxkbmap de

**Comment by karasu** [comment]
Thanks @I3ck, I'll check our code to see if we're performing those commands (I'm sure about the setxkbmap command but not so sure about the localectl one).

**Comment by I3ck** [comment]
`setxkbmap de` only worked for the current session,
so I guess the missing other command might be the source of the problem

**Comment by I3ck** [comment]
still being reset after restart
I'll try to get it fixed tomorrow and report back

**Comment by I3ck** [comment]
on a side note: could someone unlock me on transifex (I'll delete this comment then)

**Comment by Davidlinuxx** [comment]
Muchísimas gracias.

2015-03-23 11:50 GMT-05:00 Martin Buck <notifications@github.com>:

**Comment by prescott66** [comment]
with latest cnchi 0.8.xx is this bug fixed for me...i think it can be closed

**Comment by karasu** [comment]
We've changed the keyboard selection code... it's nice it's working now. Thanks for reporting it!

**Comment by I3ck** [comment]
no problem, thanks for fixing it
