### ISSUE TITLE
Grub can't find windows 8.1

### ISSUE THREAD

**Issue by mouradxmt** [Antergos/Cnchi#265]
when I have installing antergos I look for windows in grub menu I don't find it , I have installing antergos in the past and no problem , but now the problem appear , how to resolve , I have tried sudo grub-mkconfig but without any news

**Comment by lots0logs** [comment]
There is a bug in grub/os-prober that prevents other OS's from being properly detected from the live media. Once you boot into your Antergos system, running grub-mkconfig should properly detect all of the OS's installed on your system: `sudo grub-mkconfig -o /boot/grub/grub.cfg`

Please let me know if it does not resolve the issue for you.

**Comment by mouradxmt** [comment]
I have tried it but without any result

**Comment by lots0logs** [comment]
Are you still experiencing this issue? If so, could you tell me whether or not you installed Antergos under UEFI boot or legacy boot?

**Comment by cpatrick08** [comment]
installed gnome desktop from antergos-minimal-2015.06.03-x86_64.iso, booted into desktop and ran  sudo grub-mkconfig -o /boot/efi/EFI/GRUB/grub.cfg and got same result as mouradxmt. Installed it under UEFI, Grub2 won't find Windows 10

**Comment by lots0logs** [comment]
The command should be `sudo grub-mkconfig -o /boot/grub/grub.cfg`. Though your EFI partition should still be mounted at `/boot/efi`.

**Comment by cpatrick08** [comment]
ran that command and I still have the same problem,and efi partition is mounted at /boot/efi
