### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#273]
- [x] Advanced Install Screen
  - [x]  The mount point check should say /boot (not /boot/efi)
  - [x]  Also the buttons seem oversized. Maybe adjust the styles a bit.
- [x] GTK css styles are not being used. Perhaps the move from src to cnchi caused this.
- [x] BG color of list boxes should be white.
- [x] Header bar bg image is not displayed.
- [x] Header bar on slides screen needs to be styled better.
- [x] Slides should fill the width of the window.
- [x] Prev/Next Buttons need style adjustments.

**Comment by karasu** [comment]
"Slides should fill the width of the window."
About this one... I worked a bit to manage that the image was centered. I supose I can have a look at it (I'll check margins in .ui file)

**Comment by lots0logs** [comment]
> (I'll check margins in .ui file)

Be careful, you know how GTK likes to grow the window without any reason :laughing: 



> Oh, about the buttons, I don't quite like them as they're now, stick one to another, but it's your call.

Well, I'm not 100% satisfied with them. I know for sure I dont like them on separate sides. The reason I have them together is to match the numix gtk theme. BUT like I said, I'm not 100% happy with the result. Let me play with it some more in the next day or two!

**Comment by karasu** [comment]
"Slides should fill the width of the window."

I've reduced the space but it's still noticeable. It's fine with me, but maybe for others (like you) is not enough :grin:

**Comment by karasu** [comment]
By the way, do you think that what remains of this issue is really a release blocker? I think we could release even with this style issues... leave them for 0.10

**Comment by lots0logs** [comment]
Yeah I think we are just about ready for release. I've started prepping for the new iso build today. There's still a few small things I want to touch up before the release but nothing major.
