### ISSUE TITLE
Remove CLI, restyle welcome page for only two buttons.

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#274]

**Comment by karasu** [comment]
I'll do this myself, it should not be that difficult.

**Comment by lots0logs** [comment]
Cool, thanks. I am very busy with my job today. Something else I noticed was that the language screen keeps the same subtitle as the welcome screen. It should have its own subtitle like "Choose Your Language" or similar.  I am writing it here so that one of us will remember to do it :smile:

**Comment by karasu** [comment]
Hi,
I've made a quick fix. It works, but imho there's too much margin left (the icons appear too near one from another). It's not ugly, but could be better.

I'll close this, as it works, if you have the time to make it pretier (and the will to do it) feel free.
