### ISSUE TITLE
Allow different language and keyboard layout combinations

### ISSUE THREAD

**Issue by I3ck** [Antergos/Cnchi#275]
Currently it's impossible to install Antergos in English, while having a German keyboard layout.

Maybe instead of only showing the fixed options which depend on the selected language,
add a `more` or `other` button which then allows to select any layout.

**Comment by karasu** [comment]
This is already done in v0.7.x (development), so it will be present in the 0.8 release. :grimacing:

**Comment by I3ck** [comment]
awesome
