### ISSUE TITLE
Slideshow does not work if WebKit2 is used in slides.py

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#276]
I did a test install on my PC, the slide show did not work. Only a gray screen is shown. The damn log was empty so I have no idea what caused the issue :unamused:

**Comment by karasu** [comment]
Maybe the webkit change was a bad idea. I ran slides.py and worked for me,
but I didn't perform a full instalation. I'll check it when I get home

El dimecres, 1 abril de 2015, Dustin Falgout <notifications@github.com> va
escriure:

> I did a test install on my PC, the slide show did not work. Only a gray
> screen is shown. The damn log was empty so I have no idea what caused the
> issue [image: :unamused:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Antergos/Cnchi/issues/276>.
>


-- 
Enviat amb el meu Iphone

**Comment by karasu** [comment]
Me again. Yep, it's broken in the installer. What I do not get is why it works when testing the screen alone. I'll go back to webkit1 (as I tested it and works) and leave this for 0.10

**Comment by karasu** [comment]
Using WebKit 3.0:
```
import gi
gi.require_version('WebKit', '3.0')
from gi.repository import WebKit
```

Works like a charm. Closing this.
