### ISSUE TITLE
[Bug] GUI installer (Cnchi) doesn't mount the correct logical volume with LVM if the volume group contains a hyphen

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#278]
There is a bug with the GUI installer Cnchi when the target partition is in a LVM. If the physical volume’ name contains ‘-’, it is replaced by ‘- -’ in /dev/mapper, but Cnchi doesn’t handle that.

For example, if I have a physical volume named “laptop-anthony”, with a logicial volume “root”. The volume will be in “/dev/mapper/laptop- -anthony-root”, but Cnchi will try to mount “/dev/mapper/laptop-anthony-root” (because it certainly concatenates the physical volume name and the logical volume name).

http://forum.antergos.com/topic/1851/bug-gui-installer-cnchi-doesn-t-mount-the-correct-logical-volume-with-lvm

**Comment by karasu** [comment]
More Info:
Yeah sure !
Here is an "incorrect" volume group name:
```
vgname: laptop-anthony
lvname: root
mount_source: /dev/mapper/laptop--anthony-root
mount_source_in_Cnchi: /dev/mapper/laptop-anthony-root
```
Cnchi tries to mount something that does not exist, so the installation fails.

Now with this:
```
vgname: laptop_anthony
lvname: root
mount_source: /dev/mapper/laptop_anthony-root
mount_source_in_Cnchi: /dev/mapper/laptop_anthony-root
```
It works.

Cnchi just has to replace all occurrences of `-` by `--` in the volume groupe name.

**Comment by axaxs** [comment]
I think I've fixed this, could use another set of eyes.
