### ISSUE TITLE
Keyboard layout that is automatically chosen doesnt work

### ISSUE THREAD

**Issue by pilppe** [Antergos/Cnchi#280]
This is pretty similar to the issue #279 
But this time, my keyboard layout was automatically chosen, but usually when its automatically chosen it should work right? On Cnchi i have to press "Finnish" again for it to work. Last time i installed Antergos it automatically chose Finnish and i was like ok, i immediately pressed Continue and i was wondering why it doesnt work. You have to manually press it again otherwise it just continues with USA even though it displays Finnish.

I dont know whats the reason for this.

**Comment by karasu** [comment]
Nice catch. I'll check it asap. Thanks!

**Comment by karasu** [comment]
Fixed in 0.9.x
