### ISSUE TITLE
Update translation

### ISSUE THREAD

**Issue by prescott66** [Antergos/Cnchi#284]
Please, update translations from transifex. I still dont see Cnchi v0.8.16 in my language (slovak). i have translated it 100% on transifex.i need to check out translation in real usage. thx

**Comment by karasu** [comment]
Yep, we know. We will do it tomorrow if nothing else comes up.

**Comment by lots0logs** [comment]
This is fixed as of v0.8.17. Let us know if you still have the issue.

**Comment by prescott66** [comment]
0.8.21 always in english.sorry...i can create a pull request here at github with my translation.that will be the best way i think...

**Comment by lots0logs** [comment]
All translations must be submitted through transifex. See here: http://antergos.com/help-translate-antergos/

**Comment by karasu** [comment]
@lots0logs : I think @prescott66 already did it, but it's not working. Did you download all translations?

**Comment by prescott66** [comment]
You can see that all translation was not merged few months ago to github.only asturian.

**Comment by karasu** [comment]
I think @lots0logs adds all translations to the cnchi package, but I might be wrong.

**Comment by lots0logs** [comment]
Just to confirm, the translations are pulled from transifex each time the cnchi package is built. The translations shown in github are not used (technically).
