### ISSUE TITLE
Offline installation

### ISSUE THREAD

**Issue by Mikaela** [Antergos/Cnchi#286]
It would be nice if there was support for offline installation as not everywhere there is fast connection and offline installation and it would also help with these occassional Chchi bugs which prevent installing entirely.

I am not sure on how much space it would take with all the current DEs as option, but at least here most of USB sticks are 8 GB and maybe there could be diferent images for different DEs or something. Or maybe only "offline base" option and let the user install whatever they wish afterwards?

https://github.com/Antergos/Cnchi/issues/81 might be helpful thinking about possible kernel updates between releases.

**Comment by karasu** [comment]
Hi Mikaela,

In fact there's been some time we've been preparing for something like this. As it is now, Cnchi can install all packages from the ISO, and only download those that have new versions on our servers.

If you check our latest ISO (not the minimal, of course), you'll see that's bigger than the old ones. That's because it has some xz packages that Cnchi can use :grin: 

What we always want is that the user ends with an updated system (so installing a frozen iso system is a no no for us).

I hope this are good news for you :grimacing:

**Comment by Mikaela** [comment]
So if I unplugged network cable while installing, I would get everything from the iso (no matter what desktop I chose)?

**Comment by karasu** [comment]
No, not as it is now. It needs the network to check if there are new versions of each package. If not, it will install that one from the ISO.

And in the ISO, I think that only the Gnome packages are left there.

**Comment by Mikaela** [comment]
But if I booted without network connectivity, it couldn't do that check?

So without connection the only option is Gnome. Is base/terminal still installable though or does it have some packages that aren't included in other options?

**Comment by karasu** [comment]
Nope, without connection you don't have any option, Cnchi won't work.

I haven't checked base with the new iso, this should be answered by someone else...

**Comment by lots0logs** [comment]
The ISO includes all the packages for a GNOME install. Though all desktops will benefit as the majority of the packages are used regardless of which desktop you choose. You will notice that install time is much faster than it was in prior versions since Cnchi only downloads packages that have newer versions available than what's on the ISO.

**Comment by tracphil** [comment]
I agree. Make a check box or something for an offline install, because right now the installer tells me that I don't have a network connection and I clearly do. I can use Chromium to surf the net. I am using the 2015.04.12 and 2015.14.18 iso's.

**Comment by Mikaela** [comment]
> right now the installer tells me that I don't have a network connection and I clearly do

This is https://github.com/Antergos/Cnchi/issues/303 which is fixed and will be auto-updated as soon as possible according to https://github.com/Antergos/Cnchi/issues/303#issuecomment-94838586 where you also find manual git install instructions.

**Comment by lots0logs** [comment]
Closing this issue as won't fix. See comments from @karasu for explanation.

**Comment by AbdealiJK** [comment]
Sorry, but why was this closed as wont fix ?

For some reason (probably unstable internet connectivity) cnchi hangs after about 40-50 packages - this is pretty frustrating, as it doesnt continue after that.

I wanted to just install whatever is there in the live CD and then later I would upgrade at leisure (as pacman wouldnt mind getting interrupted in between and will only download things left over - cnchi gets stuck and i need to force close it)

**Comment by aaomidi** [comment]
This is a stupid decision made from the Antegros team. Especially since if your internet just randomly drops and connects back it doesn't even try to resume downloading, its just stuck. 

The assumptions made for this installer is pretty annoying and optimistic.

**Comment by taheraxo** [comment]
I failed to install Antergos and ApricityOS for that reason. My internet connection isn't so fast and I can't wait all the day for the installer to get the newest packages. It ended up ruining my bootloader in both cases too.

I think Cnchi should provide the "right to choose" whether to update during installation or not. In Ubuntu I always do offline install and then update while my system is up and ready.

**Comment by mitsuzero** [comment]
hey... i only have a non working WIFI dongle. is not option for offline installer?? ...  Artergos2015_0818.iso the one with gnome!

**Comment by karasu** [comment]
No, there is no option for offline installation as it does not make sense. A rolling release distribution always has the latest packages (there're no security repositories like in Debian stable or Ubuntu), so if you plan to work with a RR you MUST have an Internet connection available to update your packages. Your system could become insecure (or even unstable) if you do not have the latest packages.

**Comment by mitsuzero** [comment]
offline but no when its installed (im currently uses it ..antergos) ...

2015-09-04 19:33 GMT-05:00 karasu <notifications@github.com>:

**Comment by sahalswappo** [comment]
IMO, should have Offline installer . You will need this option when installation always fail after download some stuff. At least we can make it successful Install first and update later if have offline installer option.

**Comment by howdoicomputer** [comment]
So if you need to take care your wireless driver post install you're out of luck? Great.

**Comment by Gibbz** [comment]
Does this still not have offline install? :|
I just downloaded it to try, guess thats a fail... Ill give Manjaro a whirl, thanks for pointing out that one does :)
