### ISSUE TITLE
Installer font

### ISSUE THREAD

**Issue by prescott66** [Antergos/Cnchi#292]
diacritics and special chars are not in your default font, that you use in Cnchi, so this chars are in different "default" font, so strings looks no pretty good.
you should consider to use font with special chars
my lang: slovak (central europe)

**Comment by lots0logs** [comment]
Actually, the extra characters are available for the font, we just need to add them.

**Comment by karasu** [comment]
"we just need to add them." How? I don't get this :grimacing:

**Comment by lots0logs** [comment]
Google fonts include only the Latin Subset by default. For cyrillic characters you must get the Extended Latin Subset instead of the default. (I simply downloaded the font and put it on the ISO..Cnchi doesnt have any part in it)

**Comment by karasu** [comment]
Thanks!!!!

**Comment by robertda** [comment]
Unfortunately, Lato **doesn't** cover all Latin characters ([show missing glyphs](https://www.google.com/fonts/specimen/Lato)).
Use Roboto, OpenSans, Source Sans Pro, PT Sans, Noto Sans, Ubuntu.
