### ISSUE TITLE
Fails with AttributeError after update

### ISSUE THREAD

**Issue by cathalgarvey** [Antergos/Cnchi#294]
Hi, trying to install Antergos tonight and after cnchi updates I'm getting this error (when I try to launch `cnchi` in Terminal, because it silently fails to launch when I tap icon):

    [antergos@Antergos-ISO ~]$ sudo cnchi
    Can't open /tmp/cnchi.log :  [Errno 13] Permission denied: '/tmp/cnchi.log'
    INFO:root:Using GTK v3.14.6
    INFO:root:Using pyalpm v0.7 as interface to libalpm v9.0.0
    WARNING:root:Could not find 'update.info' file. Cnchi will not be able to update itself.
    Traceback (most recent call last):
      File "/usr/share/cnchi/cnchi/cnchi.py", line 62, in do_activate
        import main_window
      File "/usr/share/cnchi/cnchi/main_window.py", line 42, in <module>
        import timezone
      File "/usr/share/cnchi/cnchi/timezone.py", line 37, in <module>
        import misc.tz as tz
      File "/usr/share/cnchi/cnchi/misc/tz.py", line 175, in <module>
        class Location(object):
      File "/usr/share/cnchi/cnchi/misc/tz.py", line 179, in Location
        'latitude': (GObject.TYPE_FLOAT, 'latitude', 'latitude', 0, GLib.MAXFLOAT, 1, GObject.ParamFlags.READWRITE),
      File "/usr/lib/python3.4/site-packages/gi/module.py", line 320, in __getattr__
        return getattr(self._introspection_module, name)
      File "/usr/lib/python3.4/site-packages/gi/module.py", line 139, in __getattr__
        self.__name__, name))
    AttributeError: 'gi.repository.GLib' object has no attribute 'MAXFLOAT'

**Comment by lots0logs** [comment]
Hi, unfortunately there were changes in GTK 3.16 that broke backwards compatibility so you will have to use the latest ISO which includes GTK 3.16. Sorry about that! :pensive:

**Comment by cathalgarvey** [comment]
OK, will do. Can we chalk this up as "Feature request: cnchi should check for breaking updates and not upgrade on such occasions"?

**Comment by karasu** [comment]
@cathalgarvey : It's not that. The problem is that if we do not update, then odd things can occur when using a new GTK version. On the other hand, if we do, then our installer does not work with old GTK libraries. All of this is because Antergos is rolling release, so we have to keep up with GTK version upstream.
