### ISSUE TITLE
Installation type dialog not working in vmware

### ISSUE THREAD

**Issue by hynner** [Antergos/Cnchi#296]
Hello, I downloaded antegros yesterday to try it in virtual machine. After start it downloads cnchi update and launches cnchi automatically, when I select install I get through several steps sucessfully but when I get to Installation type dialog it just doesn't work. 

If I select *erase disk and install antegros* it moves on and on the next page it asks me whether I want to continue - If I select yes nothing happens, if I select no nothing happens as well.

If I select *choose exactly where Antegros should be installed* it moves me to a blank page.

Cnchi log on [pastebin](http://pastebin.com/criGSun5)

**Comment by karasu** [comment]
Check that you're using an IDE or SATA virtual disk. (Some users have reported problems when using SCSI emulated disks).

**Comment by hynner** [comment]
You're right. I was using SCSI disk, which is the default option in vmware player. After changing it to SATA I was able to get on with the installation.
