### ISSUE TITLE
Updater randomly chooses between 0.7 and 0.8 branches

### ISSUE THREAD

**Issue by starks** [Antergos/Cnchi#299]
How do I control which version of cnchi I get?

**Comment by karasu** [comment]
You should always get the latest version, that is 0.8.x (don't remember the last number) but it should be 0.8 definitely.

**Comment by lots0logs** [comment]
If the updater is unable to successfully update cnchi it will launch the version that is on the ISO. In this case that's the last version from our most recent development cycle 0.7.x (which is equivalent to 0.8.0)

**Comment by Toseim** [comment]
tU can try clone the project in you /usr/share and replace the cnchi folder ,and U can get the latest version

**Comment by karasu** [comment]
So... we can assume that is a connection problem? Closing this then.
