### ISSUE TITLE
When I download the package, It was stuck

### ISSUE THREAD

**Issue by Toseim** [Antergos/Cnchi#300]
as Title. It has great chance when I finish all and downloading,it will be stuck.And I don't know how, I have try to install Antergos nearly 20 times.I think cnchi.log is OK. 
....sorry for my poor english

**Comment by lots0logs** [comment]
Hi, if you could post the cnchi.log file here that would be helpful. Thanks!

**Comment by Toseim** [comment]
OK, Thx, Tomorrow I will post that file

**Comment by Toseim** [comment]
I tried to install the system for getting the cnchi.log , but It works,and even faster.First of all Thx.!
But I have something else now, I haved installed twice


[2015-04-21 12:07:50] [chroot] DEBUG: Generating grub configuration file ...
Found theme: /boot/grub/themes/Antergos-Default/theme.txt
Found linux image: /boot/vmlinuz-linux
Found initrd image: /boot/initramfs-linux.img
Found fallback initramfs image: /boot/initramfs-linux-fallback.img
  /run/lvm/lvmetad.socket: connect failed: No such file or directory
  WARNING: Failed to connect to lvmetad. Falling back to internal scanning.
grub-probe: error: cannot find a GRUB drive for /dev/sdb1.  Check your device.map.
done
[2015-04-21 12:07:50] [bootloader] INFO: GRUB(2) UEFI install completed successfully
[2015-04-21 12:07:50] [process] WARNING: While installing boot loader Cnchi encountered this error: Can't convert 'NoneType' object to str implicitly

**Comment by karasu** [comment]
@Toseim : Which Cnchi version did you use?

**Comment by Toseim** [comment]
0.80.48

**Comment by karasu** [comment]
Even it seems so, the warning "WARNING: While installing boot loader Cnchi encountered this error: Can't convert 'NoneType' object to str implicitly" does not affect Grub installation. You're experiencing another issue.

Please, tell us:
- Are you using UEFI or a BIOS based system?
- Automatic installation or advanced?
- If Automatic, which options did you choose (Luks, lvm, /home) ?

Thanks in advance!

**Comment by Toseim** [comment]
OK!
UEFI, Advanced

**Comment by karasu** [comment]
Ok, i will test it and get back to you asap

**Comment by lots0logs** [comment]
@karasu  I don't think we are checking for mount points like `/var`

**Comment by Toseim** [comment]
But now why the EFI change to the /boot/efi and what should I do to make it pass :)

**Comment by Toseim** [comment]
I meaning， what should i do to get a /boot/efi，i already have efi file in my partition sda1.and sda1 has been mounted as /boot? please

**Comment by lots0logs** [comment]
Sorry for the delay. You should boot your existing EFI partition at `/boot/efi`. Be sure you **DO NOT** choose to "format" that mount point!

**Comment by Toseim** [comment]
thanks, I haven't found I can type in character. It works, perfect work
