### ISSUE TITLE
In minimal installation, /home/USERNAME/.config is owned by root

### ISSUE THREAD

**Issue by Kirek** [Antergos/Cnchi#301]
Just this, very weird things happen when applications cannot use this directory :)
The only file there is ~/.config/fontconfig/fonts.conf

**Comment by mattchewie** [comment]
I have experienced the same when I did a full KDE install. This caused several errors to be thrown on first boot.

Just out of curiosity, did you do a UEFI install with Gummiboot?

**Comment by mattchewie** [comment]
My GNOME install just finished. I can confirm that the .config in my home directory is correctly owned by the "user". So this looks like it might be an issue tied to non-gnome installs? I will try a XFCE install in a VM tomorrow to see if I get the same outcome as the KDE install.

**Comment by karasu** [comment]
@lots0logs : If I understand correctly, this is a minimal ISO issue, isn't it? Also KDE installation seems to be affected by this.

**Comment by mattchewie** [comment]
FYI : XFCE install also as the correct permissions

**Comment by axaxs** [comment]
This has been fixed in dev, not sure on policy on closing/commenting/testing so just leaving a comment here.

**Comment by lots0logs** [comment]
We need to backport the fix into stable.

**Comment by erikdubois** [comment]
i can confirm that as of today the bare installation STILL SUFFERS from the fact that .config is owned by ROOT. Users get error messages thrown by Spotify. Each time re-login. Variety wallpapers settings. Thunar Settings... etc. Any program that wants to write there, will sometimes give an error or just nothing but all your settings are not saved.

**Comment by karasu** [comment]
@lots0logs : Has this been solved in stable?

**Comment by erikdubois** [comment]
just tried the latest iso 20150516 this has still this issue!

**Comment by karasu** [comment]
Fixed in postinstall.sh. Closing!
