### ISSUE TITLE
misc.has_connection

### ISSUE THREAD

**Issue by wsxy162** [Antergos/Cnchi#303]
try:
        url = 'http://74.125.228.100'
        urllib.request.urlopen(url, timeout=5)
        return True

http://74.125.228.100 seems point to youtube.com ? In china , the government has blocked this IP ,so could we change this url to another one ?

**Comment by cowai** [comment]
I live in Norway and the ip is down for me too, so I couldn't install antergos. Having a backup IP to check with would be a good idea.

**Comment by Toseim** [comment]
Yes, you can change the url what points to the google, and replace by what you can get access to, and it can work

**Comment by karasu** [comment]
That IP is an alternative resource used only when Cnchi can't "talk" with the NetworkManager service. I'll add an option to bypass this to avoid this kind of situations.
Thanks for reporting it!

**Comment by Mikaela** [comment]
I am in (Kotka,) Finland and I am encountering this same issue. Web browser works without issues.

I don't understand why you are testing that YouTube is up. Why to not check something like 8.8.8.8 or 8.8.4.4 which is anycasted and not so depedent on single server? They of course also have censorship issues.

**Comment by karasu** [comment]
Neither do I :grimacing:  It's nice when once in a while I'm not the one who screws up.
We're back the old method (asking NetworkManager), so in the latest Cnchi release this is no longer a problem. Also a --no-check parameter has been added, just in case, that makes Cnchi continue even if it thinks that no Internet connection is available.
Closing.

**Comment by Mikaela** [comment]
When will the fix get to repositories or wherever Cnchi uses to update itself? Antergos is again not-installable.

**Comment by karasu** [comment]
As soon as possible ;)

Meanwhile, if somebody is in need to install, the latest version can be run cloning this github repository. From the ISO, close Cnchi and run this commands from a terminal:
```
sudo pacman -S git
sudo rm -rf /usr/share/cnchi
git clone https://github.com/Antergos/cnchi
cd cnchi
./run
```
Cheers!

**Comment by Mikaela** [comment]
@karasu I am linking people to your previous comment as workaround when asked on IRC. Could you add `--depth=1` to the end of `git clone` line so it won't clone the whole repo and is faster?

`git clone https://github.com/Antergos/cnchi --depth=1`

**Comment by karasu** [comment]
Done!
