### ISSUE TITLE
BTRFS Partitioning issues

### ISSUE THREAD

**Issue by Mikaela** [Antergos/Cnchi#304]
I am using MBR and the partitioning wants me to make the following partitions in mount check list before letting me forward:

* `/`
* `/boot`
* `swap`

* [ ] `/` and `/swap` get detected correctly, but `/boot` stays red and claims that it doesn't exist. 
* [x] Cnchi doesn't allow you to install grub to partition. Other distributions e.g. Ubuntu do this.
    * https://github.com/Antergos/Cnchi/issues/304#issuecomment-94860105
        * If it's not supported by Arch, why would Antergos support it?
* [x] Cnchi also shouldn't force me to make `swap` partition, because I prefer to use `swap` files.
    * https://github.com/Antergos/Cnchi/issues/304#issuecomment-94862068

Version: current git (ref: https://github.com/Antergos/Cnchi/issues/303#issuecomment-94838586).

**Comment by karasu** [comment]
>/ and /swap get detected correctly, but /boot stays red and claims that it doesn't exist

That's my mistake. As I said, my morning commit needs some testing...

> Cnchi doesn't allow you to install grub to partition. Other distributions e.g. Ubuntu do this

You shouldn't be installing grub into a partition. Read this: https://wiki.archlinux.org/index.php/GRUB#Install_to_partition_or_partitionless_disk

> Cnchi also shouldn't force me to make swap partition, because I prefer to use swap files.

That's totally right. It's a regression and my morning commit is at fault again.

Will repair all this as soon as possible.

Again, thanks for reporting it! This is very helpful.

**Comment by karasu** [comment]
> Cnchi also shouldn't force me to make swap partition, because I prefer to use swap files.

Oh, I've checked. It does not force to create one, you can continue even if no swap partition is defined.

**Comment by Mikaela** [comment]
> You shouldn't be installing grub into a partition. Read this: https://wiki.archlinux.org/index.php/GRUB#Install_to_partition_or_partitionless_disk

There are some weird cases where it's not possible to install it to anywhere else than partition, for example this laptop and I am still unable to understand why, but as long as it works...

> Again, thanks for reporting it! This is very helpful.

You're welcome, without reports things probably wouldn't ever get fixed.

> Oh, I've checked. It does not force to create one, you can continue even if no swap partition is defined.

I wasn't aware of this, because of the `/boot` issue (it's 512 MB and FAT32 by the way). Could it be possible to improve it by having yellow warning triangle instead?

What Ubuntu does is to warn you if you don't have swap partition and suggests that you return to partitioning, but if you are sure (or didn't even read what it said) it allows you to click continue.

**Comment by karasu** [comment]
> / and /swap get detected correctly, but /boot stays red and claims that it doesn't exist

Are you using MBR in an UEFI system or a BIOS based one?

You'll have to be more specific.

In a BIOS based one it does not ask for a boot partition, see for yourself:

![no_boot_ok](https://cloud.githubusercontent.com/assets/175797/7257395/b2832058-e855-11e4-8e47-f5735c48d80a.png)

Thanks again.

**Comment by Mikaela** [comment]
> Are you using MBR in an UEFI system or a BIOS based one?

MBR in BIOS system. The BIOS is Phoenix Award something from 2006-01-??.

**Comment by Mikaela** [comment]
What I see is the following:

![](http://i.imgur.com/nn02KqT.jpg)

I never turned off the PC when I came to report this.
