### ISSUE TITLE
Add a LAMP feature

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#308]
Be able to install and setup Apache+MariaDB(mysql)+PHP from Cnchi

**Comment by Mikaela** [comment]
I would prefer Nginx in place of Apache. Could there be choice for that?

**Comment by lots0logs** [comment]
:+1:  for Nginx...LEMP instead of LAMP has my vote :wink:

**Comment by karasu** [comment]
Geez... I had my students prepare a python script to install LAMP in a base Antergos install (I'm the teacher so they have to do what I say :grimacing: )
Now, I'll have to work a little bit now to change this to Nginx...

**Comment by MichaelTunnell** [comment]
Why not both? Apache has merit as well in some usecases. :)

**Comment by karasu** [comment]
Well... I'll add LAMP as it is already done... Nginx will have to wait a bit more, but it will be done for sure.

**Comment by axaxs** [comment]
Is this going to be on features screen?  Seems it should be asked on base installs ( or if we ever have some server centric install).  And of course, +1 for Nginx over Apache :p.

**Comment by karasu** [comment]
@axaxs : The idea is to add it in the features screen, yes. Maybe we can show it only if base install is chosen, I haven't decided anything yet.

**Comment by karasu** [comment]
It's done. It needs testing with other features https://github.com/Antergos/Cnchi/issues/359

As we have the other issue I'll close this one as done.
