### ISSUE TITLE
Internet connection not detected during installation from live usb

### ISSUE THREAD

**Issue by saikat-sengupta** [Antergos/Cnchi#309]
I was unable to proceed with installation as Cnchi could not identify the internet connection. I hope the following snapshot will be self explanatory -

![screenshot from 2015-04-22 22-51-50](https://cloud.githubusercontent.com/assets/11479802/7280736/6923754c-e914-11e4-901d-08385576ed9a.png)

**Comment by saikat-sengupta** [comment]
Linux Antergos-ISO 3.19.3-3-ARCH #1 SMP PREEMPT Wed Apr 8 14:10:00 CEST 2015 x86_64 GNU/Linux

**Comment by saikat-sengupta** [comment]
You can also notice that the option to close the window is also disabled

**Comment by lots0logs** [comment]
Hi,

It appears the installer is failing to update. Please close it and run the following command from a terminal:
```
sudo pacman -Syy cnchi
```
Now when you start the installer it should be updated to the latest version. Let us know if you still have trouble.

**Comment by karasu** [comment]
@lots0logs : Damn! You beat me!

**Comment by lots0logs** [comment]
:laughing:

**Comment by karasu** [comment]
I think that @saikat-sengupta didn't wait for the update to take place, and because of the "Internet" bug" Cnchi can't update itself

**Comment by saikat-sengupta** [comment]
@karasu I waited till I got the notification saying update is done. And then Cnchi started automatically.

**Comment by saikat-sengupta** [comment]
@lots0logs I am trying that now. Btw, great job guys :+1:

**Comment by saikat-sengupta** [comment]
Also getting notification windows repeatedly, is it latest Gnome functionality?? Kinda irritating :-/
