### ISSUE TITLE
Cnchi hung hence installation is not completed

### ISSUE THREAD

**Issue by saikat-sengupta** [Antergos/Cnchi#310]
I was trying to install Antergos from a live USB. Even though I performed all the steps properly and got the button "Start installation" but when I clicked that Cnchi became busy. I kept my system on for whole night even then also the same status. I had to terminate the session :-1:

**Comment by karasu** [comment]
We need the log to see what happened... It's always in /tmp/cnchi.log

**Comment by karasu** [comment]
I'll close this as I guess this was a mirror issue. I will reopen it if @saikat-sengupta gives more information.
