### ISSUE TITLE
Using encryption in advanced mode for /boot does not work

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#315]
Using encryption in advanced mode for /boot does not work

**Comment by karasu** [comment]
Reported by @Jbonnett

**Comment by Mikaela** [comment]
Isn't `/boot` supposed to be unencrypted, so you can decrypt other partitions when you use the device?

**Comment by karasu** [comment]
Yes ;)

**Comment by Mikaela** [comment]
I don't probably understand this issue then.

**Comment by karasu** [comment]
Hahaha... me neither. I posted this here without thinking because an user suggested it. Closing.
