### ISSUE TITLE
Advanced Screen UI Bugs

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#317]
- [ ] Mount checklist disappears when an extended partition is created.
- [X] Install Now button is too big

![screenshot from 2015-04-29 01-16-40](https://cloud.githubusercontent.com/assets/4675662/7383382/eee35c1c-ee0d-11e4-885c-aa9f9799c38d.png)

**Comment by karasu** [comment]
Delete a partition, root requirement disappears. :cry:

**Comment by lots0logs** [comment]
I didnt look at that yet. I was working on the Install Now button. I havent tested my latest changes for it. Did it look okay?

**Comment by axaxs** [comment]
Was this fixed?  If not, can someone explain what remains?  I'm still pretty familiar with the advanced logic, hopefully I can take a look soon.

**Comment by karasu** [comment]
Most of them. I do not recall fixing "Mount checklist disappears when an extended partition is created", though.
