### ISSUE TITLE
Cnchi Not auto detect existing swap partition

### ISSUE THREAD

**Issue by showcheap** [Antergos/Cnchi#320]
I have swap partition, and cnchi not detect it as swap. I should double click on that partition and click apply to make cnchi set that partition as swap.

![screenshot from 2015-05-01 16-16-39](https://cloud.githubusercontent.com/assets/1310895/7433149/ec092a46-f01d-11e4-9676-a972b6cbc034.png)

**Comment by karasu** [comment]
Cnchi can't know if a user wants to use an existing swap partition or not, and I do not like the idea of Cnchi using partitions without the knowledge of the user.

Anyway, let's see what other devs think.

**Comment by lots0logs** [comment]
It's not a good idea to use the same swap partition for multiple installations (whether they be different distros or the same) It can cause problems with hibernate/resume and although its rare, it could also cause problems in your live system.

**Comment by karasu** [comment]
Closing, then.
