### ISSUE TITLE
os-prober timesout again

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#321]
os-prober issues a time out again... I really don't know why.

More info:
https://github.com/Antergos/Cnchi/commit/7ad4f87484e5e612803a1ba62dda136d73d5292e#commitcomment-11011642

**Comment by karasu** [comment]
Now it's working. Geez...

**Comment by karasu** [comment]
And now it is not! Facing this now in a VM with two harddisks, installing from sda to sdb (whole disk installation). It freezes when trying to install the bootloader.

**Comment by karasu** [comment]
@lots0logs : By the way, ten minutes for a time out seems a bit overkill :laughing:

**Comment by lots0logs** [comment]
> By the way, ten minutes for a timeout seems a bit overkill

Actually, it may not be overkill. A user reported that os-prober does usually complete if given enough time to do so. They said the same bug is found on Debian Testing but within 5-10 minutes the process exits and everything is fine. I, myself never had the patience to wait and see if it does eventually exit. :laughing:

**Comment by karasu** [comment]
> I, myself never had the patience to wait and see if it does eventually exit

Hahaha... so I'm a guinea pig!  :laughing: 

Well, now we know it really exists.

**Comment by lots0logs** [comment]
So the 10 minutes is not overkill then? hahaha

**Comment by karasu** [comment]
I only experience this if I try to install to harddisk from another one (in a VM).

So if nobody else complains, I'll close it as it is not a normal procedure (users will always install from the liveCD).
