### ISSUE TITLE
antergos servers unresponsive 

### ISSUE THREAD

**Issue by theking2** [Antergos/Cnchi#323]
After a while the servers for me in CHE become unresponsive. After the fifth attempt to install antergos I decide to do a tail -f  /tmp/chchi.log just to see that downloading up and until gnome-documents went fast but after that re repository servers become unresponsive. 
Two things are required here
1) an indicator that shows the current download speed.
2) a way to select another mirror when download speeds go under a threshold
3) faster mirrors

After a while Errno 104 is reported "Die Verbindung wurde von Kommunikationspartner zurückgesetzt"

As the error does not include a hostname I can't tell you which one it is.
1) In the errno 104 exception text, include the actual hostname to enable trouble shooting

I can help you with faster mirrors if you require funding for that. 

Sofar I have not been able to install antergos. Which is a shame.

**Comment by karasu** [comment]
We've coded a new way of downloading the packages, that will help a bit (will show the download speed) in our development version (not yet released).
To select another mirror you can edit /etc/pacman.d/mirrorlist and /etc/pacman.d/antergos-mirrorlist by hand. Anyway, we can't do a lot when the mirrors do not answer or are not up to date.

Cnchi tries up to five different mirrors, if none of them works it finishes.

If you want to establish a mirror in your country we will be very glad to use it.

Please, can you retry with the latest released version here in github?

Thanks!

**Comment by lots0logs** [comment]
Closing this as we've rewritten the download code since it was originally reported.
