### ISSUE TITLE
Manual Installation /boot/efi

### ISSUE THREAD

**Issue by Eadword** [Antergos/Cnchi#324]
When on an UEFI system, it requires the /boot/efi partition. I believe that it should say "/boot/efi (fat32)" since it will not accept anything else.

**Comment by karasu** [comment]
Nice suggestion. I'll change it asap. Thanks!

**Comment by lots0logs** [comment]
@karasu I think it's better to have fat32 be automatically selected when `/boot/efi` mount option is chosen.

**Comment by Eadword** [comment]
Would that work if it was preformed as, say, ext4 by gparted?

**Comment by lots0logs** [comment]
Yes, but it would have to be formatted again. Though that's not a problem because if it was an existing EFI partition that the user wanted to keep it would already be fat32 (All EFI partitions are fat32, which is the only option the spec allows)

**Comment by karasu** [comment]
@lots0logs : So, what do we do? We need to change something or not? ;)

**Comment by lots0logs** [comment]
Make it so that selection of `/boot` as the mountpoint automatically selects `fat32` for the filesystem type  (for uefi systems only)
