### ISSUE TITLE
Error Log on Failure

### ISSUE THREAD

**Issue by mdickie** [Antergos/Cnchi#327]
Just interested is it possible to retrieve an Error Log on Failure? I had an installation error (minimal iso) but i couldn't remember it.

**Comment by karasu** [comment]
Of course, you have it in /tmp/cnchi.log (or if it managed to start installation, in your destination /var/log/cnchi-date.log)

**Comment by mdickie** [comment]
I apologize but I don't have it.

**Comment by mdickie** [comment]
Now I took the live is and it works.

**Comment by karasu** [comment]
Glad to hear it. Closing...
