### ISSUE TITLE
Chromium is also installed when selecting Firefox

### ISSUE THREAD

**Issue by robertda** [Antergos/Cnchi#328]
Since 0.8.100 (0.8.70 does not have that issue), Cnchi installer download and install Chromium too for Firefox scheme install. Same error on 0.8.15 too. 

![rsz_screenshot_from_2015-05-09_13-22-05](https://cloud.githubusercontent.com/assets/11921426/7549837/4ef3e6d0-f651-11e4-9b5f-02b8bb8efc94.jpg)

![rsz_screenshot_from_2015-05-09_13-32-18](https://cloud.githubusercontent.com/assets/11921426/7549838/5451d790-f651-11e4-9740-3fcea56150df.jpg)

**Comment by karasu** [comment]
Thanks for warning us. We will check this as soon as possible and get back to you.

Cheers!

**Comment by robertda** [comment]
Weird! Chromium is not installed after all, just chromium-pepper-flash, package required by chromium.

![rsz_screenshot_2015-05-09_13-53-03](https://cloud.githubusercontent.com/assets/11921426/7549885/dfc113b2-f652-11e4-9c27-6a6936aa2678.jpg)

**Comment by karasu** [comment]
It looks like some dependency issue. I think we're installing chromium-pepper-flash by error. Thanks again for sharing this.

**Comment by Wyn10** [comment]
Still happening in 0.10.5

**Comment by karasu** [comment]
Yep, we didn't fix this yet (the milestone is set to 0.12)

**Comment by karasu** [comment]
Fixed in 0.11.61
