### ISSUE TITLE
Not translatable "Save" button

### ISSUE THREAD

**Issue by prescott66** [Antergos/Cnchi#330]
In create user slide is in top right corner "Save" button, which i am not able to translate, so it is in english always.

**Comment by karasu** [comment]
Transifex has not been updated yet. Will do it asap. Thanks for the warning!

El dimecres, 13 de maig de 2015, Dušan Kazik <notifications@github.com> va
escriure:

> In create user slide is in top right corner "Save" button, which i am not
> able to translate, so it is in english always.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Antergos/Cnchi/issues/330>.
>


-- 
Enviat amb el meu Iphone

**Comment by prescott66** [comment]
You are welcome

**Comment by karasu** [comment]
Oh, I know I said I was going to update asap, but I prefer to wait until we have a new release to warn everybody to start translating, because we'll be adding/changing strings while developing... and that would annoy most of the translators, I'm sure! :grin:
