### ISSUE TITLE
Keyboard for Belgium should be be-latin1 not be

### ISSUE THREAD

**Issue by erikdubois** [Antergos/Cnchi#331]
During installation I tend to choose for bare installation. Then choose English Uk as language and Belgium as keyboard BUT I end up in QWERTY.

The whole country works with AZERTY keyboards.

Extra actions for users now:
sudo loadkey be-latin1 in order to have azerty KEYBOARD
We change also the following file to make it permanent
sudo nano /etc/vconsole.conf
We change our keyboard from "be" to "be-latin1"

Keyboard "be" does not exist!
Could you look into this?

**Comment by karasu** [comment]
https://github.com/lots0logs/cnchi-dev/commit/3f1ded8e654bc2f7f1dcd99f5ac2f3d3bc9f161e Fixes this.

**Comment by erikdubois** [comment]
better reopen 
still an issue see postings on
http://forum.antergos.com/topic/2280/testing-of-the-antergos-2015-06-03-x86_64-iso-gnome
http://forum.antergos.com/topic/2282/testing-of-the-antergos-2015-06-03-x86_64-iso-base

**Comment by Mikaela** [comment]
Did you try git version? https://github.com/Antergos/Cnchi/issues/303#issuecomment-94838586

**Comment by karasu** [comment]
It's fixed in dev version. We'll release it really soon 👍

El dimecres, 3 de juny de 2015, Mikaela Suomalainen <
notifications@github.com> va escriure:

> Did you try git version? #303 (comment)
> <https://github.com/Antergos/Cnchi/issues/303#issuecomment-94838586>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Antergos/Cnchi/issues/331#issuecomment-108372379>.
>


-- 
Enviat amb el meu Iphone

**Comment by erikdubois** [comment]
i used the version that is on the iso 
which seems to be cnchi 0.8.137

**Comment by erikdubois** [comment]
I did think I was working with the latest version possible...
how to get the really latest version then?

**Comment by karasu** [comment]
Hi,

For reasons that no longer apply, we had two source branches in different places. We will put both on them in Github shortly. Meanwhile, you can test the dev version installing the cnchi-dev package, but I'm afraid it's not always up to date.

As a guideline, even versions are "stable" whereas odd versions are development ones (not ready for release). We have 0.8.x as stable and 0.9.x as dev. (0.9.x will become next 0.10 when we feel is stable enough).

Cheers!
