### ISSUE TITLE
No Internet after bare installation

### ISSUE THREAD

**Issue by erikdubois** [Antergos/Cnchi#332]
Cnchi installs perfectly. Ethernet Controller functions fine and downloads come in. Then you reboot.

After bare installation there is no internet available but drivers are working.
After  the following lines everything works fine : 
sudo systemctl enable dhcpcd
sudo systemctl start dhcpcd

If it is an issue of choice. 

Could you give the choice in inxi in the installation screens. If not provide the bare installation with some kind of internet connection. The first you want to do after a bare installation is install software.

Possible choices are : 
dhcpcd
systemd-networkd
netctl

lspci : 02:00.0 Ethernet controller: Qualcomm Atheros AR8121/AR8113/AR8114 Gigabit or Fast Ethernet (rev b0)

**Comment by Mikaela** [comment]
I believe the base installation assumes that the user wishes to make the choice how to setup networking by themseles and I think it should be that way. Installing some DE has networking.

From the options listed, my favourite is [systemd-networkd](https://wiki.archlinux.org/index.php/Systemd-networkd).

**Comment by erikdubois** [comment]
my favourite too but how about a line in the installer so you know you will have to do that.

**Comment by Mikaela** [comment]
That could work. "Please note that networking is not automatically set up with base installation" or something.

**Comment by erikdubois** [comment]
great

**Comment by andrewbates09** [comment]
:+1: Having an option of networking tools out of the gate would be fantastic, as @erikdubois mentioned - at the very least a, "BTW refer to [ArchWiki](https://wiki.archlinux.org/index.php/Network_configuration) to get going on new installation," in the installer would be helpful.

To be fair, it probably only took 20 seconds to figure that out once I had installed Antergos Base.  I just came across this after looking around to see if it was common.

**Comment by karasu** [comment]
New release will use systemd-networkd and will try to setup all ethernet connections with dhcp. So still no wifi and no fixed ip's yet.

**Comment by karasu** [comment]
We'll suppose that if somebody is in need of a fixed IP he'll know how to setup it.
For wifi Cnchi will setup DHCP, too, but the user will need to setup its SSID and password, so it won't work out of the box.

**Comment by erikdubois** [comment]
That is super if you give it as a choice (slider) in cnchi since opinions are divided on that issue

Verstuurd vanaf mijn iPad

**Comment by Mikaela** [comment]
> New release will use systemd-networkd and will try to setup all ethernet connections with dhcp. So still no wifi and no fixed ip's yet.

Will `systemd-networkd-wait-online.service` be enabled so there is network connection immediately after boot (when you are allowed to login etc.)? In case connection doesn't get established there is 90s timeout.

* See also: https://wiki.freedesktop.org/www/Software/systemd/NetworkTarget/

**Comment by karasu** [comment]
@Mikaela : Nope, I wasn't enabling that service. Thanks for the tip!!! :wink:

**Comment by Mikaela** [comment]
You're welcome :smile:
