### ISSUE TITLE
Cnchi will not start after updating

### ISSUE THREAD

**Issue by erikdubois** [Antergos/Cnchi#333]
Cnchi gives message that it has been updated but will not start on its own.
Pressing the icon does not start the program.

I am installing now and did the following 

Opened a terminal and typed
sudo pacman -S cnchi
sudo cnchi

Then the startup screen was there and did a bare installation.

Version 0,8,118 is now installing.

Tried installing on a different pc and results is the same issue. Cnchi will not startup after update.
any logs i can post here ? Let me know.
for your information  if you install cnchi it says
python-parted and pyparted are in conflict remove pyparted y?
i removed it.

**Comment by erikdubois** [comment]
second try instead of using the above method went looking for cnchi
cnchi-dev
cp:  cannot stat '/usr/share/cnchi/scripts/testing.sh' no such file or directory
chmod : cannot access '/tmp/testing.sh'

works again like a charm once i did the above described procedure
this time around installing cinnamon - will check if there is a keyboard issue here like on the bare installation.

**Comment by erikdubois** [comment]
working on the iso from sourcforge of 20150516 
there cnchi 0.8.118 works fine

**Comment by ianks** [comment]
Same issue here.

**Comment by plumpudding** [comment]
this seems to be a pretty serious issue concerning the iso though. I noticed running "pacman -S cnchi" manually is enough to get it running. I also noticed pacman asks ":: python-parted and pyparted are in conflict. Remove pyparted? [y/N]", which is probably the reason for the update failing.

**Comment by karasu** [comment]
>python-parted and pyparted are in conflict. Remove pyparted? [y/N]

That's pretty much my fault. I renamed the package without warning  @lots0logs , who always takes care of the iso.

Let's wait until he finds the time to fix this (or tells me what I have to do to fix it).

**Comment by plumpudding** [comment]
So this is fixed in newer isos? Is @lots0logs informed now?

**Comment by lots0logs** [comment]
This is fixed in the images that are available on the build server. The images on the main download page will be replaced ASAP. Cheers!

**Comment by karasu** [comment]
Well, closing now. If any of you experience this issue again please warn us here.

Thanks!
