### ISSUE TITLE
If plasma and bluetooth is selected bluedevil is conflicted.

### ISSUE THREAD

**Issue by Wyn10** [Antergos/Cnchi#336]
bluedevil4 and bluedevil are in conflict if plasma is selected.  bluedevil4 for kde4 and bluedevil for plasma.

**Comment by lots0logs** [comment]
Are you sure? That should not pose a problem. Could you provide the log?

**Comment by Wyn10** [comment]
@lots0logs 

https://gist.githubusercontent.com/Wyn10/c532fe17c4b41c5bdb54/raw/gistfile1.txt

Also stated here: https://wiki.archlinux.org/index.php/Bluetooth#BlueDevil
