### ISSUE TITLE
Buttons alligment on welcome slide

### ISSUE THREAD

**Issue by prescott66** [Antergos/Cnchi#342]
While using slovak language of cnchi, i get this bad alligment on welcome screen - because description text above Install button ist little bit longer in our language :smile: 
![snimka obrazovky z 2015-05-19 09-22-36](https://cloud.githubusercontent.com/assets/735265/7697577/3a48c34e-fe09-11e4-81a4-edbb4803d99d.png)

**Comment by lots0logs** [comment]
This should no longer be an issue with the new UI in v0.14.0
