### ISSUE TITLE
Use systemd-networkd in base install

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#349]
systemd-networkd is a system daemon that manages network configuration. It detects and configures network devices as they appear, as well as creates virtual network devices. This service can especially be very useful to setup basic or more complex network settings for a container managed by systemd-nspawn such as VMs or containers. Again, but also works fine on simple connections.

[1] https://wiki.archlinux.org/index.php/Systemd-networkd
[2] http://dabase.com/blog/Good_riddance_netctl/

**Comment by Mikaela** [comment]
What is wrong with `systemd-networkd` which seems more simple to me?

**Comment by karasu** [comment]
OK,  I've readed positive comments about systemd-networkd

I will change this issue... ;)

Thanks for sharing your thoughts!

**Comment by Mikaela** [comment]
https://github.com/Antergos/Cnchi/issues/332 is probably also relevant issue.

**Comment by Mikaela** [comment]
GitHub doesn't show 34b5b3d as link for some reason, how was this fixed? Does Cnchi automatically detect what interfaces there are and write .network files for them to be DHCP? Or what does it do?

**Comment by Mikaela** [comment]
https://github.com/Antergos/Cnchi/issues/332#issuecomment-108561755

> New release will use systemd-networkd and will try to setup all ethernet connections with dhcp. So still no wifi and no fixed ip's yet.

understood :)

**Comment by karasu** [comment]
>GitHub doesn't show 34b5b3d as link for some reason, how was this fixed? Does Cnchi automatically detect what interfaces there are and write .network files for them to be DHCP? Or what does it do?

Well, you guessed it right. It just scans all detected network devices and creates a configuration file for each one, that always uses DHCP. ;)
