### ISSUE TITLE
Gummiboot + Encryption broken again

### ISSUE THREAD

**Issue by plumpudding** [Antergos/Cnchi#351]
I will take a look as soon as I have time
Just wanted to let you know
I don't have an exact crashlog, I just remember the log said something like "cryptAntergos" found but int required.

**Comment by plumpudding** [comment]
now tested a bit more

didn't work on my laptop, desktop and a vm (on which I'm testing atm

**Comment by karasu** [comment]
Thanks for the warnings, we will check this asap

About the code, yes, you can write whatever you want, then we will adapt it if necessary.

Cheers!

**Comment by plumpudding** [comment]
as far as I've looked into this the problem could be [here] (https://github.com/Antergos/Cnchi/blob/master/cnchi/installation/process.py#L781)

**Comment by lots0logs** [comment]
:triumph: haha it works. you see what I did @karasu? 

I am reopening this ticket, the above was just a test for something not directly related to this ticket.

**Comment by karasu** [comment]
Yep, https://github.com/lots0logs/cnchi-dev/commit/1107412afedc056064122de3483d78f0fe0eb792 fixes it!
