### ISSUE TITLE
Installation with LUKS not terminating properly / GRUB_ENABLE_CRYPTODISK not set

### ISSUE THREAD

**Issue by pldubouilh** [Antergos/Cnchi#352]
Last update of Cnchi doesn't work with LUKS encrypted parts, the parameter `GRUB_ENABLE_CRYPTODISK` is not set, and grub will throw an error, saying that it requires the parameter to be set `=1`. It's actually not working (see here > http://savannah.gnu.org/bugs/?41524), but setting it to `=y` solved it... Appending this to /etc/default/grub fixed the issue.

Should be quickly resolved implementing this (untested) :
```self.set_grub_option("GRUB_ENABLE_CRYPTODISK", "y")```
here : https://github.com/Antergos/Cnchi/blob/master/cnchi/installation/bootloader.py#L149

**Comment by karasu** [comment]
Will do! Thanks!

**Comment by karasu** [comment]
https://github.com/lots0logs/cnchi-dev/commit/a06904ce5d7a02753f9b56c27c9abe1154daf13e
