### ISSUE TITLE
grub-mkconfig hangs up (timeout) in VM base install

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#354]
Running grub-mkconfig takes 10 minutes... and then fails. (again)

I'm really pissed off with this issue (comes and goes).

@lots0logs : I know you looked into this some time ago, is that mounting problem again?

**Comment by lots0logs** [comment]
hmm..I will run a quick test and let you know!

**Comment by karasu** [comment]
Thanks! :sob:

**Comment by lots0logs** [comment]
Btw, did you see the commit I @ referenced you on an hour ago?

**Comment by lots0logs** [comment]
So I just did a test in a VM using the latest github master and there was no issue with grub installation :dizzy_face:

**Comment by karasu** [comment]
> Btw, did you see the commit I @ referenced you on an hour ago?
Yes! I see that you did nothing but you referenced that commit automatically. Is that it?

> So I just did a test in a VM using the latest github master and there was no issue with grub installation

mmm.... I think I got this bug again because I'm doing my tests with two harddrives (and I shouldn't be doing that, nobody will install from an HD to another HD). Closing...
