### ISSUE TITLE
Conflict between python-parted & pyparted

### ISSUE THREAD

**Issue by uiokdfsoigk** [Antergos/Cnchi#356]
I booted up a live ISO, and tried to install antergos from it.  I was greeted with an error in the installation, saying I did not have an active network connection and could not continue.  I tried to fix this by running cnchi-dev from the terminal, but was given an error saying cnchi-dev could not be updated as pyparted and python-parted are in conflict
   ```bash
[root@Antergos-ISO antergos]# cnchi-dev
Previous testing setup detected, skipping downloads...
Verifying that nothing is mounted from a previous install attempt.
Removing existing Cnchi...
python: no process found
Getting latest version of Cnchi from stable branch...
:: Synchronizing package databases...
 core                     122.3 KiB   132K/s 00:01 [######################] 100%
 extra                   1727.2 KiB   343K/s 00:05 [######################] 100%
 community                  2.7 MiB  1369K/s 00:02 [######################] 100%
 antergos                 402.4 KiB  1257K/s 00:00 [######################] 100%
 multilib                 125.8 KiB  1014K/s 00:00 [######################] 100%
resolving dependencies...
looking for conflicting packages...
:: python-parted and pyparted are in conflict. Remove pyparted? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: python-parted and pyparted are in conflict
```

Upon running pacman -R on pyparted and chchi-dev and re-running cnchi-dev I was able to successfully install cnchi, and this time it picked up my network connection.

**Comment by karasu** [comment]
This is already fixed in our servers, will be ok when a new iso is issued.

Thanks a lot for reporting it, though.

I'll leave it open as a reminder.

P.S. Are you aware that you have a testing iso in build.antergos.com ?

**Comment by Mikaela** [comment]
> This is already fixed in our servers, will be ok when a new iso is issued.

When will a new iso be issued? At IRC we are wondering issue #303 which was first reported in 2015-04-21 and it's on the current isos and the installation experience isn't so nice now that people have to use the workaround from #303.

The easiest fix would probably be releasing a new iso as soon as possible.

**Comment by lots0logs** [comment]
Agreed. :smile:
