### ISSUE TITLE
LVM crashes install

### ISSUE THREAD

**Issue by jkw** [Antergos/Cnchi#357]
Typing this from Antergos. Tried to install 5 times with LVM/Choose separate Home. But I got error that Installer was not able to partition. After a while I decided to try trial and error, removed the check for LVM and installation is now working properly so far. 

Downloading files now.

**Comment by dildosucker** [comment]
ya I have the same error

**Comment by karasu** [comment]
@jkw and @dildosucker , did you use UEFI or BIOS based systems? I've done several tests in a BIOS system and it's working here (with the dev version, 0.9.x)

Thanks!

**Comment by jkw** [comment]
Sadly can't remember that. 

Skickat från min Sony Xperia™-smartphone

---- karasu skrev ----

**Comment by karasu** [comment]
As I can't reproduce it in Cnchi 0.9.x, I'll close it.
Anyway, if this is reported again in 0.10.x we'll try to address it.
Thanks to both of you.
