### ISSUE TITLE
Check and fix all automatic installation options (LVM +/- LUKS +/- HOME)

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#358]
Check and fix (if necessary) all automatic installation options:

BIOS-MBR:
* [X] None
* [X] Encrypt
* [X] LVM
* [X] Home
* [X] Encrypt + LVM
* [X] Encrypt + Home
* [X] LVM + Home
* [X] Encrypt + LVM + Home

UEFI-GPT: (grub2)
* [X] None
* [ ] Encrypt
* [ ] LVM
* [ ] Home
* [ ] Encrypt + LVM
* [ ] Encrypt + Home
* [ ] LVM + Home
* [ ] Encrypt + LVM + Home

UEFI-GPT: (gummiboot)
* [ ] None
* [ ] Encrypt
* [ ] LVM
* [ ] Home
* [ ] Encrypt + LVM
* [ ] Encrypt + Home
* [ ] LVM + Home
* [ ] Encrypt + LVM + Home

**Comment by dildosucker** [comment]
hey LVM is not working, issue reported here https://github.com/Antergos/Cnchi/issues/357

**Comment by dildosucker** [comment]
also, I saw this on the "TODO" list "Encrypt home directory (needs testing)" can you add this option to the test builds for us to use?

**Comment by karasu** [comment]
>also, I saw this on the "TODO" list "Encrypt home directory (needs testing)" can you add this option to the test builds for us to use?

I'm afraid it needs more than just testing.... it's just raw code without any "security" tests at all, not ready even for testing.
