### ISSUE TITLE
nuke keys option

### ISSUE THREAD

**Issue by dildosucker** [Antergos/Cnchi#362]
https://github.com/offensive-security/cryptsetup-nuke-keys 

add this is an option if the user chose full disk encryption, I think that would be really cool.

**Comment by axaxs** [comment]
This is not the job of a distro nor an installer.

**Comment by dildosucker** [comment]
hmm.. but wouldn't it be possible after the luks process is finished to run the nuke patch and set it up through the installer?

**Comment by karasu** [comment]
After reading what cryptsetup-nuke-keys is I have to agree with @axaxs .

Sorry @dildosucker , I'll close this one.
