### ISSUE TITLE
RFE: GNOME: Allow using default theme

### ISSUE THREAD

**Issue by sils** [Antergos/Cnchi#364]
Would be great to be able to flick a switch to have the defauilt gnome experience (using GDM and Adwaita, extensions deactivated.) I know it can be work arounded easily but I at least would find that comfortable to have.

**Comment by Mikaela** [comment]
If I understand this issue correctly, this would be nice with other desktop environments too, I did base installation and only installed MATE afterwards, because I don't want mintmenu and what else has been changed with it.

**Comment by sils1297** [comment]
Sure, I didn't know there were customizations for the other systems, never
got to try them out yet.

2015-07-08 17:19 GMT+02:00 Mikaela Suomalainen <notifications@github.com>:

**Comment by karasu** [comment]
We discussed this a long time ago, the initial @faidoc 's idea was to provide two versions of each DE, one setup by us and a "vanilla" one. It was discarded as it was a lot of work and we wanted to provide an easy setup for our users, and leaving all vanilla is not a good option for newcomers.

Maybe we change our minds about this but don't hold your breath, honestly.

**Comment by Mikaela** [comment]
>  It was discarded as it was a lot of work and we wanted to provide an easy setup for our users, and leaving all vanilla is not a good option for newcomers.

Base install is always possible with exactly how we like it :)

I don't know about the option being left available and I have no idea about the background, but Cnchi could have small button "vanilla" under the real DE and when hovered over say something like "*Vanilla DEHERE without Antergos modifications, only for advanced users*".

**Comment by sils1297** [comment]
If this option needs maintaining I'd  actually advise against this option,
better do your stuff good than add other stuff. However given that your
modifications are only on top of vanilla you don't need to maintain two
configurations but just *not apply an extra one* right?

2015-07-08 20:29 GMT+02:00 Mikaela Suomalainen <notifications@github.com>:

**Comment by Yoshi2889** [comment]
I'm going to link this comment here:

https://github.com/Antergos/antergos-packages/issues/95#issuecomment-290356846

Because the benefit of using my proposal would be that there could be a switch like "Do not install the enhanced Antergos configuration for this DE", which would not install the antergos-{de}-config package.

**Comment by karasu** [comment]
As it is now, I think that not installing antergos-desktop-settings would suffice. I'll start working on this.

**Comment by lots0logs** [comment]
FWIW I do not think this should be an option in the installer. For one, we have enough options as it is. Installation is supposed to be simple. Its getting out of hand. Also, anyone who knows enough to want to change to the default GNOME experience surely knows how to do it themselves.

**Comment by karasu** [comment]
On second thought I agree with @lots0logs so I will close this one.
