### ISSUE TITLE
Cnchi doesn't install drivers present on live ISO

### ISSUE THREAD

**Issue by sils1297** [Antergos/Cnchi#365]
I booted up the live ISO on the Lenovo Yoga 3 Pro, everything worked just fine, including wifi with the driver from the antergos repository. However Cnchi didn't think of installing it for me leaving me stranded on my new system without WIFI and without ethernet because of the hardware.

Would be nice if you could guarantee that what works on the live CD also works on the real system.

**Comment by karasu** [comment]
New Cnchi version has hardware module rewritten, so maybe this has already been addressed.

Can you make me a favor? Just issue a `lspci -nnn` in your computer, so we can see which hardware you have and Cnchi does not detect.

**Comment by sils1297** [comment]
Sure, this is filtered with `grep Network` though:

01:00.0 Network controller [0280]: Broadcom Corporation BCM4352 802.11ac
Wireless Network Adapter [14e4:43b1] (rev 03)

2015-07-08 17:27 GMT+02:00 karasu <notifications@github.com>:

**Comment by karasu** [comment]
Thanks!

**Comment by karasu** [comment]
Fixed in 0.11.81
