### ISSUE TITLE
Cnchi freezes on package download

### ISSUE THREAD

**Issue by exadeci** [Antergos/Cnchi#366]
I'm trying to install Antergos with the minimal iso and cnchi gets stuck during the downloads, stay 15mins without changing from downloading message, my computer is plugged on ethernet on a fiber connection and when I did a :
sudo pacman -S package-name 
it got installed in a second but cnchi was stuck, trying to start another instance displayed an error message and the message stopped responding...

**Comment by lots0logs** [comment]
Hi,

If you could grab the installer log located in the `/tmp` directory when this occurs it would be much appreciated :smile:

**Comment by exadeci** [comment]
[cnchi.log ](https://files.zenhub.io/55a05018dc7f29585e18d2f9)

**Comment by exadeci** [comment]
So I changed my mirrors list with reflector before starting the install and it hanged again several times but it seems to be working I let it run all night (eu).

**Comment by pkaq** [comment]
I had this problem too

**Comment by jkw** [comment]
I can confirm this too. Very hard to reproduce though. "Just worked" after like 10th install in a VM.

**Comment by lots0logs** [comment]
@karasu I don't see any log output from the mirrorlist module. Did remove log messages from the module or is this something that needs to be looked into further?

**Comment by karasu** [comment]
The module you're looking for is download_urllib.py (in downloads dir). It only logs when an error or warning is detected. Cnchi 0.9 uses download_requests.py so I would recommend not to spend time trying to fix this now and wait until 0.10 is out (it should be in a few days).

**Comment by karasu** [comment]
Oh, or at least start testing 0.9 with this error... I'd guess is a mirror error but maybe our urllib call code is at fault.

**Comment by lots0logs** [comment]
@karasu I was referring to this: https://github.com/Antergos/Cnchi/blob/master/cnchi/rank_mirrors.py

**Comment by karasu** [comment]
@lots0logs : oh, that's your rank mirrors code ;) 

Anyway, I think we should release 0.10 and then try to fix this in 0.10.x code. download_requests.py (new download code that version 0.10 will use) and rank_mirrors have changed a lot.

**Comment by lots0logs** [comment]
@karasu : :laughing: Yeah I know, I was asking if perhaps you made a change to the logging because it was too noisy or something.

That plan sounds good to me. Let me know when you are ready to do it. We won't make an ISO since we are trying to keep updating those monthly (and I just updated it). Anyway, it shouldn't matter as long as the updater script does its job when the ISO boots.

**Comment by nanotux** [comment]
I think Cnchi on Minimal ISO freezes randomly, no pattern visible to me. I gave up. Internet/network is still working, but Cnchi is stuck ...

Now I will try to install with Live version (Full ISO).

@karasu : It would be better to remove Minimal ISO in the Antergos Download Section, till problem is solved. Thank you.

**Comment by karasu** [comment]
We're about to release Cnchi 0.10, so it's no use to try to fix this in 0.8, as the download code is totally different.

I'll leave this open to test and fix asap, and I'll post here my findings.

@nanotux: Yes, it would be very useful if you could tell me if you also find this behaviour in the live CD (full iso).

Thanks!
