### ISSUE TITLE
Antergos creates additional unnecesary partition.

### ISSUE THREAD

**Issue by ghost** [Antergos/Cnchi#370]
If this is intentional behavior, feel free to correct me, but I don't think it is?

I installed Antergos today, using the live install image, and it's partitioned my drive in a strange way. I let it fully erase the disk, but instead of creating 3 partitions (boot, /, swap), it's created 4. It has created a 1K /dev/sda3, which as far as I can tell contains no data, and is not mounted anywhere. If I try and mount it, it tells me "EXT4-fs (sda3): unable to read superblock". It's not in /etc/fstab either.

I'm using an old, ms-dos/MBR system, with grub2.

**Comment by karasu** [comment]
Hi,

Thanks for your report. Of course it's not intended, the partitioner must be doing something wrong. What I do not get is why you have an 1K partition, never seen this before.

Could you tell me exactly your harddisk specifications?

**Comment by oooze81** [comment]
320GB laptop drive, on a BIOS system. Unfortunately I had other issues with the Antergos installer, so I no longer have it installed. If there is some command to see hard disk information though I could run it?

**Comment by karasu** [comment]
Hi,

Knowing your disc geometry might be helpful. If you have a Linux installed or with the live iso, you can run hdparm to get it:
`sudo hdparm -g /dev/sda`

Thanks!

**Comment by oooze81** [comment]
Sure, I have another distro installed now.

/dev/sda:
geometry      = 38913/255/63, sectors = 625142448, start = 0

**Comment by karasu** [comment]
Silly me. Rereading this I see that @ghost was referring to the extended partition that Cnchi creates to store the swap partition inside it...closing.
