### ISSUE TITLE
Add Plasma 5 Desktop Environment

### ISSUE THREAD

**Issue by lasers** [Antergos/Cnchi#373]
"Note: In 2014, the KDE project changed the way it names and organizes itself. The older term KDE Software Compilation was discontinued and the versioning and development cycles of the frameworks and applications were decoupled from the Plasma desktop itself." 

"The KDE 4 Plasma Desktop is currently in maintenance mode, and is expected to reach EOL in August 2015."  https://wiki.archlinux.org/index.php/KDE#Installation

**Comment by MichaelTunnell** [comment]
This information is not verified and has no citation at all. I edited the line that makes the claim of EOL to request a citation because at this stage the only information provided for EOL is for 4.11.x and not for the entire setup of KDE4.

Hopefully, the person who made the claim will verify where they got that statement from.

**Comment by stratus-ss** [comment]
The only thing I can see is also for workspaces 4.11. However I have also found reference to the fact that KDE Workspaces 4.11 is the workspace version in KDE SC 4.14. Wikipedia (I know, I know....) and the [kde mailing list] (https://mail.kde.org/pipermail/release-team/2015-August/008835.html) both indicate that Plasma 4 is/was in LTS mode starting Aug 2013 and was only to be supported until 2015. This coupled with the fact that QT4 itself goes end of life this year is probably a strong indication that KDE is in fact going away

I am not sure that this means it should be removed from the installer yet though

**Comment by lots0logs** [comment]
A good indicator, IMO, is what version of KDE openSUSE ships by default in it's main/primary version. (So not Tumbleweed or Factory). Once they include plasma 5, its safe to consider KDE4 EOL (though I heard some rumors saying the Trisqel project might move from KDE3.x to KDE4 but I guess that wouldnt make a difference technically speaking)

**Comment by MichaelTunnell** [comment]
> Wikipedia (I know, I know....) and the kde mailing list both indicate that Plasma 4 is/was in LTS mode starting Aug 2013 and was only to be supported until 2015.

Maintained not **supported**

> The only thing I can see is also for workspaces 4.11

Yes, this is only for kdebase-workspaces which is 4.11.22 and while that questioned was posed on the Mailing List it was never actually answered so who knows if it truly will be the last release.

> Bottom line is that we'll continue to offer it in the installer for as long as installing it from the official Arch repos is possible. Cheers!

I agree and if anything, KDE4 and Plasma 5 could be provided as options for a little while simultaneously and then remove KDE4 when the time is right.

------

I think since Plasma 5 is technically not "production ready" yet then it wouldn't make sense for 5 to be used as the default option. Once KDE declares it "production ready" then it makes sense to offer both options and then once KDE4 fully reaches EOL then to remove it.

**Comment by lots0logs** [comment]
@MichaelTunnell My thoughts exactly! :+1:

**Comment by Mikaela** [comment]
[#kde](https://kiwiirc.com/client/chat.freenode.net:+6697) gives mixed response on is it considered as production ready.

* https://www.phoronix.com/scan.php?page=news_item&px=KDE-5-Is-It-Stable
* *It's a stable release series, not a beta.*

**Comment by Mikaela** [comment]
https://en.wikipedia.org/wiki/KDE_Plasma_5 doesn't seem to have any comment on it not being prodction ready either.

**Comment by karasu** [comment]
@Mikaela : My personal experience with Plasma 5 was nice in the beginning, but then strange problems appeared. I totally agree with the phoronix article. Plasma 5 is pretty and fast, but it's not production ready (imho). I had to restart kwin at least twice a day... that's not normal (what a beginner would think about our distro if it will hang so often?). And what's worse, for me 5.3 was better than 5.4... so to sum it up, I'm using Enlightenment now (which is also not bugfree, but at least it's not preventing me to do my work). I'm against switching to Plasma while KDE4 is still available in Arch repos, but I do not have a final word in this, of course.

Anyway, thanks for sharing your thoughts.

**Comment by Mikaela** [comment]
This seems to be the best answer from #KDE:

```
2015-10-22 21:21:26+0300 < *mynicks> <rdieter:#kde> Mikaela: Facts are that the kde4 *desktop* (kde-workspace) is no longer supported by kde.org, while plasma5 *is* actively supported.  Taking that in mind, what any distro chooses to ship is ultimately up to them.
2015-10-22 21:23:21+0300 < *mynicks> <rdieter:#kde> Mikaela: related fact: qt-project.org's support of Qt4 (which KDE4 depends on), is also end-of-life, with no new releases
```

Based on this it seems to me that Cnchi should offer KDE Plasma 5 instead of KDE 4.

**Comment by lots0logs** [comment]
@Mikaela Decisions like this must be made carefully, with all Antergos users in mind. To that end, we're going to wait until Arch drops KDE4 from the official repos before we make a move here. I know you do not agree with the decision, but I hope you can respect it. Thanks for your input, we do appreciate it :smile:

**Comment by MichaelTunnell** [comment]
I don't think the lack of kde-workspace support defines whether KDE4 is still being maintained. They are still making updates for KDE4 as a whole so just because one component is unsupported does not negate all of it, in my opinion.

**Comment by Mikaela** [comment]
> I know you do not agree with the decision, but I hope you can respect it. Thanks for your input, we do appreciate it ￼

This issue doesn't personally affect me (unlike #452). I was just suspicious of the claim *not production ready until otherwise stated* and wanted to figure that out. I can respect your decicion, but I think it's going to cause issues in the future with both KDE4 and QT4 being unsupported.

**Comment by Wyn10** [comment]
I think Plasma should be added with a beta DE notice, Plasma been my daily driver since the summer.  I restart kwin maybe once a week, and it's always been my fault for crashing it.

**Comment by MichaelTunnell** [comment]
> I think it's going to cause issues in the future with both KDE4 and QT4 being unsupported

KDE4 is **not** "unsupported", in fact it is still actively maintained. The component "kdebase-workspaces" is no longer actively maintained but that does not mean unsupported either. The rest of KDE4 is being maintained at the moment.

As for Qt4, I couldn't find any statements about when they end support for a major version. Qt4 is rather old so it is possible that could be an issue soon or even now, I'm not sure.

This will be a problem in the future, but really anything will have problems in the future. :)

I think Plasma 5 will be ready for Cnchi rollout with 5.5. I think 5.4 is very close but not quite there yet. **I'd vote for Plasma 5 to be added with 5.5** (provided it is as good as I am predicting it would be)

**Comment by Mikaela** [comment]
5.5 doesn't seem to be in near future. https://github.com/Antergos/Cnchi/milestones

**Comment by Mikaela** [comment]
* [Arch Linux - News: Dropping Plasma 4](https://www.archlinux.org/news/dropping-plasma-4/)

>  2015-12-12 - Antonio Rojas
Since the KDE 4 desktop has been unmaintained for several months and it's becoming increasingly difficult to support two versions of Plasma, we are removing it from our repositories. Plasma 5.5 has just been released and should be stable enough to replace it.

> KDE 4 installations will not be automatically upgraded to Plasma 5. However, we recommend all users to upgrade or switch to a maintained alternative as soon as possible, since any future update may break the KDE 4 desktop without prior notice. See [the wiki](https://wiki.archlinux.org/index.php/KDE#Upgrading_from_Plasma_4_to_5) for instructions on how to upgrade to Plasma 5.

**Comment by Wyn10** [comment]
Hallelujah!

**Comment by karasu** [comment]
Yep, I agree we have postponed this too far in time. We lack the manpower to do all the things we have in mind :cry: 

Cnchi 0.13.352 already has Plasma 5 on its DE options. Needs a lot of testing, though.

**Comment by Wyn10** [comment]
@karasu I've been trying to push Plasma since May in pull requests and issues, it makes me so happy :).
