### ISSUE TITLE
Review all logging messages and ensure appropriate level is being used.

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#378]
We need to use `WARNING` and `ERROR` only for things that are indicative of a real problem that we would want to investigate. Currently, `WARNING` is being used in places where it should really be `DEBUG` or `INFO` like for example some messages in `download.py`. 

Also while we are at it we should add any additional meta data to the log messages that might be helpful. @karasu I am assigning to you but I will help with this also :wink:

I don't think we should make logging messages translatable. `PEP 8` recommends using English for logging. Only strings that are displayed on the frontend of the application should be translatable. What are your thoughts @karasu ?

**Comment by karasu** [comment]
:+1:

**Comment by karasu** [comment]
Oh, what I meant is that I also think that we should use English for logging, and I agree that we have to use less logging.warning through all the code... that's my fault. :grin:

**Comment by lots0logs** [comment]
Cool..no worries. It's something we can easily change :wink:

**Comment by karasu** [comment]
I think we can close this. Maybe there's still some loggging.warning in some file that slipped my search, but we will be able to fix it in the future.
