### ISSUE TITLE
AttributeError in parted3/fs_module.py:172

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#379]
## Exception in Cnchi

**AttributeError** in **parted3/fs_module.py:172**
&#x27;NoneType&#x27; object has no attribute &#x27;lower&#x27;

[View on Bugsnag](https://bugsnag.com/antergos/cnchi/errors/55d6d43f6b8d2dd06f569263?event_id=55d6d86aed174cb4773ce77b)

## Stacktrace

    parted3/fs_module.py:172 - create_fs
    misc/misc.py:175 - helper
    installation/advanced.py:2180 - create_staged_partitions
    installation/advanced.py:2047 - store_values
    main_window.py:424 - on_forward_button_clicked

[View full stacktrace](https://bugsnag.com/antergos/cnchi/errors/55d6d43f6b8d2dd06f569263?event_id=55d6d86aed174cb4773ce77b)

**Comment by karasu** [comment]
create_fs is receiving a None parameter, but with only this I can't find out why. I added some logging to this function hoping we will be able to pinpoint what's going on.

Leaving it for 0.14
