### ISSUE TITLE
Conflict between lib32-nvidia-libgl and lib32-mesa-libgl in "graphics" feature

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#385]
Conflict between lib32-nvidia-libgl and lib32-mesa-libgl

**Comment by Yoshi2889** [comment]
I don't think this is an issue anymore, especially not with the libglvnd implementation in Arch now.

**Comment by karasu** [comment]
Ups! Thanks @Yoshi2889 for helping cleaning the house! It's really appreciated.
