### ISSUE TITLE
ffmpegthumbnailer in cinnamon

### ISSUE THREAD

**Issue by prescott66** [Antergos/Cnchi#387]
just suggestion: to get fully working(with video files previews) Nemo file manager in Cinnamon, there must by installed package "ffmpegthumbnailer". maybe you should consider, to put it in packages list

**Comment by karasu** [comment]
Will do!

**Comment by Wyn10** [comment]
@karasu 

Too slow :D

**Comment by prescott66** [comment]
it is fixed now isnt?! after wyn10s PR

**Comment by karasu** [comment]
@prescott66 : Yep! Thanks to @Wyn10 

Closing...
