### ISSUE TITLE
No bluetooth support in Cinnamon

### ISSUE THREAD

**Issue by prescott66** [Antergos/Cnchi#390]
With selected Bluetooth feature in Cnchi, there is not support of bluetooth in Cinnamon.
I think you should build package cinnamon-bluetooth from https://github.com/linuxmint/cinnamon-bluetooth  and add it to your repo.

**Comment by Wyn10** [comment]
@prescott66 gnome-bluetooth should be getting installed since Cinnamon is a fork of Gnome and also uses gtk.  It is not being installed?

**Comment by lots0logs** [comment]
Cinnamon has their own bluetooth app. If I remember correctly its called Blueberry or something to that effect. I will check on it. Cheers!

**Comment by Wyn10** [comment]
@lots0logs It's blueberry... https://wiki.archlinux.org/index.php/Cinnamon#Cinnamon_settings

**Comment by prescott66** [comment]
yes i know it is fork of gnome...gnome-bluetooth is installed, thats right but nothing is visible to control bluetooth

**Comment by prescott66** [comment]
blueberry works. jsut add blueberry package to packages.xml for cinnamon

**Comment by karasu** [comment]
Done in dev 0.11.49
Cheers!
