### ISSUE TITLE
cnchi does not pull in antergos/b43-firmware

### ISSUE THREAD

**Issue by djringjr** [Antergos/Cnchi#393]
cnchi does not pull in antergos/b43-firmware

**Comment by karasu** [comment]
Could you post here your lspci? (well, just the line with the broadcom interface will suffice).

And thanks for reporting this. Will check asap.
http://forum.antergos.com/topic/2769/cnchi-does-not-pull-in-antergos-b43-firmware

**Comment by djringjr** [comment]
The Broadcom BCM4312 is detected during installation, so wifi has Internet access, but firmware is not installed with install.  I tried two installs to confirm.  I installed GNOME then Openbox.

# lspci -nn
04:00.0 Network controller [0280]: Broadcom Corporation BCM4312 802.11b/g LP-PHY [14e4:4315] (rev 01)

# lshw

  *-network
                description: Network controller
                product: BCM4312 802.11b/g LP-PHY
                vendor: Broadcom Corporation
                physical id: 0
                bus info: pci@0000:04:00.0
                version: 01
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress bus_master cap_list
                configuration: driver=b43-pci-bridge latency=0
                resources: irq:18 memory:f4700000-f4703fff

**Comment by lots0logs** [comment]
> so wifi has Internet access, but firmware is not installed with install

I could be wrong, but I want to say that the firmware is only needed for building the driver from source. Since we build the package and provide it in our repo you shouldnt need the firmware package.

**Comment by djringjr** [comment]
My wifi card will not work unless I manually install:

antergos/b43-firmware 6.30.163.46-7 [installed]
    Firmware for Broadcom B43 wireless networking chip

I have done three installations of the most recent release to be sure it
wasn't an accident on my part.

I am using LTS kernel 3.14.51-1-lts.

Maybe the LTS kernel does not have the support for this firmware compiled
into it.

During installation from USB or DVD, this card's wifi is supported but
after installation it will not work until the b43-firmware is installed.

Then it works.

David

**Comment by karasu** [comment]
@lots0logs : Many years ago I had a Broadcom Wifi card (used b43 driver) and it didn't work without installing the firmware. The driver needs it.

**Comment by djringjr** [comment]
The previous versions of Cnchi pulled in the firmware and after I installed
Antergos, the system worked perfectly.  I have reinstalled several times
because I try different things out, sometimes I run into problems that
cannot be fixed without a lot of work, so I install again, preserving my
/home partition like most of the experienced users do.

ONLY with the last and current Cnchi do I have this problem.  Something
must have changed.

Thanks for all your efforts, Antergos is a pleasure to use.  I do wish that
the development team would also have a text installer that would work with
speakup for blind users.  Antergos is so much better than everything out
there.

Although blind users won't have the benefit of seeing the beauty in the
Antergos screens, such as the Plasma desktop, or the Log In Screen, they
will have an excellent system.

Also I understand that the problem with running Orca in Xwindows and
speakup in console has been solved: Users now can have speech in both
Graphical User Interface / GUI and the Command Line Interface / CLI.

Now to have a text installer that talks to make this accessible!

Thanks!

DR

**Comment by karasu** [comment]
@djringjr :

Geez.... I 'm terribly sorry but I can't reproduce this one. I've done some tests (even though I do not have a broadcom device) and it seems it's working fine here.

You don't have a log as I asked by any chance? It should be in /var/log

Thanks!

**Comment by djringjr** [comment]
http://qsl.net/n1ea/cnchi-20150829-155828.log

Does that help?

David

**Comment by karasu** [comment]
Yes, I think I know what's wrong... I need to fix it and test it.

Thanks!

**Comment by izzostar** [comment]
BCM4322, while installing wifi is there, after installation not anymore.
