### ISSUE TITLE
Using xfs or f2fs as root fs makes Cnchi fail.

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#396]
Using xfs as root fs makes Cnchi fail miserably. Another user has reported problems when using f2fs

I will test it again and post the log.

**Comment by karasu** [comment]
xfs works in VM, f2fs does not.

**Comment by lots0logs** [comment]
@karasu No, I don't think it is supported if `/boot` is on the same partition as `/` It should work with separate `/boot` partition that is not f2fs though.

**Comment by karasu** [comment]
OK, then we should issue a warning message telling the user that if f2fs is used, a /boot partition must be created. I'll leave this for 0.14

**Comment by karasu** [comment]
Check 0.13.34
