### ISSUE TITLE
Broadcom WiFi issue

### ISSUE THREAD

**Issue by prescott66** [Antergos/Cnchi#399]
After running Live CD(minimal 2015.08.18-i686) on HP notebook with BCM43xx wifi device, WiFi works out of the box (cool! :+1: ).
But after succesfull installation, WiFi dont works (missing drivers), so i have installed packages b43-firmware and broadcom-wl from your repo, and it works again.
Strange is, why is wifi not working after installation. maybe is needed to add these packages to packages.xml...

**Comment by karasu** [comment]
There's a bug in hardware module in Cnchi 0.10 that has already been fixed in 0.11

Thanks for reporting this anyway!

https://github.com/Antergos/Cnchi/issues/393
