### ISSUE TITLE
KDE4 hangs in splash screen

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#403]
>Freshly installed Kde 4 boots well, doesn’t present any error or warning message in tty, arrives to Kde splash screen… and hangs here

This could be anything... just check it's not a general error.

**Comment by Wyn10** [comment]
This issue is still being reported on the forums.

[Here](http://forum.antergos.com/topic/2834/testers-need-we-have-a-fresh-set-of-iso-images-and-need-a-few-testers-to-confirm-that-the-images-are-good/17).

**Comment by karasu** [comment]
But's only Just that reported this... and I can't replicate here. Have you tested KDE4?

**Comment by Wyn10** [comment]
@karasu 

Could not replicate in a vm.  But trying to replicate on actual hardware.

**Comment by karasu** [comment]
@Wyn10 : I think that is something wrong with Just hardware setup.... but who knows. If you can replicate it by all means tell us. Thanks!
