### ISSUE TITLE
Grub boot error message - install with auto partitioning and encryption

### ISSUE THREAD

**Issue by raneon** [Antergos/Cnchi#406]
When I install antergos with auto partitioning and encryption enabled I will see on the new system always during boot in grub an error message:
"Error: device name required"

If you wait some seconds or if you press a key then boot will continue nevertheless without any other issue.

**Comment by wywialm** [comment]
I confirm this issue, it happens exactly as OP put it.

**Comment by karasu** [comment]
https://forum.antergos.com/topic/2923/grub-boot-error-device-name-required/

**Comment by karasu** [comment]
Is your /boot encrypted? If not, try to comment it (just add # at the beginning):

# cryptomount -u ....

In /boot/grub/grub.cfg

**Comment by shaief** [comment]
My drive is encrypted and i also face the same issue.

Is there a recommended way to solve it for encrypted drives? (the [link above :point_up:](https://github.com/Antergos/Cnchi/issues/406#issuecomment-146571532) is for not encrypted drives.

**Comment by blizzz** [comment]
Run into this as well (with all encryptions, LVM and seperate home partition checked) and the solution as quoted by @karasu is quite right. 

The boot partition is typically not encrypted in this setup (according to an installation on Jan 1st):

```
blkid /dev/sda1 
/dev/sda1: LABEL="AntergosBoot" UUID="c9b7227e-0634-49aa-844f-1ffae629510b" TYPE="ext2" PARTUUID="2ba1d230-01"
```

To compare, my encrypted partitions looks like this:

```
blkid /dev/sda2
/dev/sda2: UUID="2ef591b4-5894-410a-b677-2bcde9bdc8a3" TYPE="crypto_LUKS" PARTUUID="2ba1d230-02"
```

Thus, the cryptomount for the boot partition does not make any sense and should be commented out.

**Comment by karasu** [comment]
This is not a Cnchi issue, but a Grub issue. As it does not prevent booting we'll leave as it is. Feel free to comment if you do not agree.
