### ISSUE TITLE
Download net speed is too slow in Antergos LiveCD

### ISSUE THREAD

**Issue by mudongliang** [Antergos/Cnchi#414]
In the mirrorlist I  put ahead "mirrors.163.com, mirrors.ustc.edu.cn" which is greatly fast in my area .
But the download net speed is too slow to install my system.  I see the net speed in system moniter is zero.
I am crazy about it. I don't know what's the point!

**Comment by mudongliang** [comment]
I can download things in "7 ~ 8 M/s" from "mirrors.ustc.edu.cn", I am curious why I can't download package in Cnchi. It is always zero in my several times trying to install antergos.
Maybe at last, I will give up this distribution!

**Comment by Wyn10** [comment]
Post cnchi log.  It's in ```/tmp/cnchi.log```

**Comment by mudongliang** [comment]
I have changed to Base(which is smaller) without any desktop environment. After several times trying to install,  I have finished installing AntergOS. 
Although I still don't know why it is too slow, AntergOS is OK now.
But when I install gnome, it is different from the default gnome in livecd.
How do I try to change gnome in repo to default gnome in livecd?

**Comment by karasu** [comment]
I'm afraid there's no way now to apply our Gnome settings to a vanilla installation atm. We're working on it.

**Comment by karasu** [comment]
>In the mirrorlist I put ahead "mirrors.163.com, mirrors.ustc.edu.cn" which is greatly fast in my area .
>But the download net speed is too slow to install my system

Cnchi chooses the best mirrors by default. It's strange what is happening to you. If you want to force using those mirrors, you have to call cnchi with the parameter `--disable-rank-mirrors`

Cheers!
