### ISSUE TITLE
Download speeds shown on slides screen are not correct

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#415]
It is showing speeds ranging from `50-130Mbps` but my internet connection is only `24Mbps` @karasu Do you have any ideas about what's causing this?

**Comment by karasu** [comment]
Yes, I accepted a pull request without checking it... my bad. I'll try to fix it asap.

**Comment by karasu** [comment]
In the end it was my fault. Fixed in 0.13.23
