### ISSUE TITLE
Deleteing lvm partitions before mounting them is a really bad idea.

### ISSUE THREAD

**Issue by ial0** [Antergos/Cnchi#418]
In install.py,
  * mount_partitions calls auto_partition.unmount_all, 
  * this executes wipefs on the lvm volume group setup earlier,
  * this wipes the lvm partitions which are about to mounted
Hence installation fails.

Using ISO 08-09-15 i686

**Comment by karasu** [comment]
Fixed in 0.13.25, now unmount_all just does what the function name says.

**Comment by karasu** [comment]
Fixed in 0.12.13 (stable)
