### ISSUE TITLE
lightdm stays configured to use lightdm-gtk-greeter

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#419]
In a new installation, lightdm tries to use lightdm-gtk-greeter.

Just reinstalling lightdm-webkit-theme-antergos fixes the issue.

How come it does not work the first time ?

**Comment by karasu** [comment]
@lots0logs : I assigned you because I remember that you did that configuration, but it could be that I broke something...

**Comment by lots0logs** [comment]
@karasu I have not seen this issue in any of the test installs I did during the last few days :confused:

**Comment by karasu** [comment]
I've got this error when testing the latest development version of Cnchi while installing Gnome DE (default features, automatic installation). I'll test it again asap, I want to see if it's lightdm setup what is wrong (by wrong I mean that it's not applied).

**Comment by karasu** [comment]
Tested again and.... it's working! I don't know what happened that time. Closing this... will reopen if it pops up again.

**Comment by lots0logs** [comment]
@karasu I don't think I remembered to cherry-pick my commits to postinstall.sh in stable for cnchi-dev :grimacing:
