### ISSUE TITLE
Install ZFS on root partition in Cnchi

### ISSUE THREAD

**Issue by rusty725** [Antergos/Cnchi#421]
Please add to the cnchi installer option to install zfs on root. I know zfs is cddl but looking at this https://www.phoronix.com/scan.php?page=news_item&px=ZFS-Debian-Libdvdcss-Packages article makes me think that it is possible on Antergos as well.

**Comment by karasu** [comment]
https://wiki.archlinux.org/index.php/ZFS
https://wiki.archlinux.org/index.php/Installing_Arch_Linux_on_ZFS

**Comment by rusty725** [comment]
I know I can install it that way but it would be nice to have it in the installer as an option.

**Comment by karasu** [comment]
@rusty725 : I know, I just put those links as a reference. Thanks :grin:

**Comment by lots0logs** [comment]
I promised this enhancement almost a year ago :grimacing:

**Comment by Yoshi2889** [comment]
Do you want to leave this open with the current ZFS implementation in cnchi?

**Comment by karasu** [comment]
Imho, as it is now, it's enough for the average user (root is installed in zfs). I know it uses the whole disk... but I don't see the point to use zfs in any other way.
