### ISSUE TITLE
In 0.12 graphic drivers feature is unavailable.

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#425]
In 0.12 graphic drivers feature is unavailable.

We need to update it (done) and test it for 0.14

**Comment by karasu** [comment]
AMD Catalyst is reported broken atm.

I'm thinking about completely ditching this, as it's going to be impossible to keep up with it.

**Comment by lots0logs** [comment]
@karasu I think we should only handle the proprietary drivers that are packaged by upstream Arch  (aka Nvidia) , at least for now (since we are spread pretty thin right now)

**Comment by karasu** [comment]
I'll try to add nvidia support and forget about AMD, as they don't keep up with the latest Xorg version and installing it means to keep an old version of Xorg installed, which makes no sense in a RR distro.

**Comment by karasu** [comment]
AMD support is removed (drivers are disabled). I need to test NVIDIA in a real machine, though.
