### ISSUE TITLE
Install fails because the mirror ranking process allows servers without 32bit multilib

### ISSUE THREAD

**Issue by TheRyanHowell** [Antergos/Cnchi#426]
Just tried the latest version, stable and Next. It looks like the ranking process of the mirrors from my location chose mirrors that are missing multi-lib packages, so the installation fails, it would be a good idea to include package checks in the ranking process, to include the fastest 64-bit servers and the fastest multi-lib servers.

**Comment by karasu** [comment]
@lots0logs Are there mirrors without multilib? I didn't notice.

**Comment by lots0logs** [comment]
To be honest I had no idea that mirrors could pick and choose which repos they serve. I will look into it!

**Comment by TheRyanHowell** [comment]
Just to clarify, it's not necessarily the problem that they don't have the multilib folder, but that it's missing important packages, in my use case they ether didn't have multilib, or they hadn't synced/updated since mid-2014, so things like the newest bash/systemd resulted in a 404.
