### ISSUE TITLE
Add acpid package both base and graphical installs

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#428]
Add acpid package both base and graphical installs

**Comment by karasu** [comment]
@lots0logs : Can this be done by just adding acpid to our packages.xml ?

**Comment by lots0logs** [comment]
@karasu yeah, I created the issue as a reminder to myself hehe

**Comment by karasu** [comment]
https://github.com/lots0logs/cnchi-dev/commit/e161a0683af8bd06eef5ea3141baf586933aca45
