### ISSUE TITLE
Error: remove_lvm() missing 1 required positional argument: 'device'

### ISSUE THREAD

**Issue by giovino** [Antergos/Cnchi#432]
Greetings,

Cnchi 0.12.22 seems to be failing to install within Virutalbox. Default partitioning options were chosen during install.

[Screenshot](https://i.imgur.com/8jiCylS.png)

Probably due to this commit:

https://github.com/Antergos/Cnchi/commit/0d818df3c2c1e0d7379752404d0a0e05dab86d0a

Maybe here, not passing a device parameter:

[auto_partition.py#L670](https://github.com/Antergos/Cnchi/blob/0d818df3c2c1e0d7379752404d0a0e05dab86d0a/cnchi/installation/auto_partition.py#L670)

Ref: [Antergos Forums](http://forum.antergos.com/topic/2941/failure-during-install-remove_lvm-missing-1-required-positional-argument-device)

**Comment by fionera** [comment]
I can confirm this, today where two other People in the IRC with the same Problem...

**Comment by giovino** [comment]
I can confirm this fixed the issue, closing.
