### ISSUE TITLE
Abort and notify user when unsupported ISO version is detected. 

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#439]
## Exception in Cnchi

**LogERROR** in **installation/automatic.py:46**
Cannot create Cnchi main window: /usr/lib/libdevmapper.so.1.02: undefined symbol: dm_hash_l\, version Base

[View on Bugsnag](https://bugsnag.com/antergos/cnchi/errors/560bcbae9556cbb85501a72d?event_id=560bcd55bb2c8f632126c734)
## Stacktrace

```
installation/automatic.py:46 - &lt;module&gt;
main_window.py:55 - &lt;module&gt;
cnchi.py:81 - do_activate
```

[View full stacktrace](https://bugsnag.com/antergos/cnchi/errors/560bcbae9556cbb85501a72d?event_id=560bcd55bb2c8f632126c734)

**Comment by lots0logs** [comment]
Define a minimum ISO version and when older version is detected notify user that installation cannot continue.

**Comment by karasu** [comment]
@lots0logs : Is there an easy way to obtain the ISO version?

**Comment by lots0logs** [comment]
@karasu Yes, the hostname contains the version. This is another issue I made as reminder to myself :grimacing:

**Comment by karasu** [comment]
@lots0logs : We should implement this asap. We're still getting bugsnag errors from old Cnchi versions. Maybe we should rethink the update method, as it's clear that in some cases it does not work (I really do not know why).

**Comment by lots0logs** [comment]
@karasu It is strange that we cannot reproduce a failure to update ourselves, not even once. I think the updater script is a sound method, however,  because the updater is an external script, I think the only way to ensure that we are getting the desired result is to make Cnchi aware of its own version and also the version that is currently in the package repo. That way we have both sides of the issue covered instead of just one (does that make sense)?

If Cnchi detects a newer version is available (which should not be the case if the update script was successful) then it should abort and explain to the user that an unknown error occurred while trying to update and advise them to run the updater manually. Thoughts?

**Comment by karasu** [comment]
@lots0logs I agree. As Cnchi needs an Internet connection, we can check against the latest stable version, if it is an older one, show a message warning and close. I'll do it asap.

**Comment by karasu** [comment]
Done ages ago (cnchi checks its own version, there is no need to check iso version). Forgot to close this. Closing.
