### ISSUE TITLE
Hardware module error: virtualbox.py:63

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#444]
## Exception in Cnchi

**LogERROR** in **/home/antergos/cnchi-dev/cnchi/hardware/virtualbox.py:63**
Unknown error in hardware module. Output: super(type, obj): obj must be an instance or subtype of type

[View on Bugsnag](https://bugsnag.com/antergos/cnchi/errors/55f5c3930f76499ec47fa162?event_id=5610f62dab2f066261833856)

## Stacktrace

    /home/antergos/cnchi-dev/cnchi/hardware/virtualbox.py:63 - post_install
    /home/antergos/cnchi-dev/cnchi/hardware/hardware.py:335 - post_install
    /home/antergos/cnchi-dev/cnchi/installation/install.py:991 - configure_system

[View full stacktrace](https://bugsnag.com/antergos/cnchi/errors/55f5c3930f76499ec47fa162?event_id=5610f62dab2f066261833856)

**Comment by karasu** [comment]
Fixed in https://github.com/lots0logs/cnchi-dev/commit/5f60d7de188175dd09e5864edd0ec524ddb39bb0
