### ISSUE TITLE
AttributeError in installation/advanced.py:746

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#451]
## Exception in Cnchi

**AttributeError** in **installation/advanced.py:746**
&#x27;NoneType&#x27; object has no attribute &#x27;get_iter_first&#x27;

[View on Bugsnag](https://bugsnag.com/antergos/cnchi/errors/562490329556cbb8552bc2ed?event_id=5624905d9df6dc0f3be114e6)

## Stacktrace

    installation/advanced.py:746 - on_partition_list_edit_activate
    installation/advanced.py:1338 - on_partition_list_treeview_row_activated

[View full stacktrace](https://bugsnag.com/antergos/cnchi/errors/562490329556cbb8552bc2ed?event_id=5624905d9df6dc0f3be114e6)

**Comment by karasu** [comment]
I'm unable to reproduce this. I'll add a check so it does not launch an exception, but I can't imagine in which situation where the combobox doesn't have a model.
