### ISSUE TITLE
Updating existing files

### ISSUE THREAD

**Issue by benwaffle** [Antergos/Cnchi#455]
I want to update `/etc/grub.d/10_antergos`. Is it safe to replace on an installed system? Are there any other files that are worth updating?

**Comment by benwaffle** [comment]
So I replaced it and it seems fine

**Comment by lots0logs** [comment]
Sorry about the delayed response. You shouldn't have any issues. That file will only be used if/when you update your `grub.cfg` using the `grub-mkconfig` command.  Cheers!

**Comment by benwaffle** [comment]
Are there any other files that are worth updating?

**Comment by lots0logs** [comment]
No, none comes to mind at the moment. Grub is really the only thing that was not being handled through the package manager.

**Comment by benwaffle** [comment]
ok thanks :+1:
