### ISSUE TITLE
Cnchi is not up to date 

### ISSUE THREAD

**Issue by leyenda** [Antergos/Cnchi#461]
Hello, I've downloaded Antergos(x86_64) from the official page and I'm getting the following message when trying to install it in virtualbox.  Any help wold be appreciated, thanks.

![Cnchi](https://sc-cdn.scaleengine.net/i/bc7fc6035dffe9bf910decf1f7429a361.png "Cnchi")

**Comment by AaronTakizad** [comment]
For now, here's what worked for me. In terminal, run:
`
sudo pacman -S --force cnchi-dev
`

**Comment by leyenda** [comment]
It is fixed now, thanks.
