### ISSUE TITLE
xdg-user-dirs-update is only run in GNOME

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#464]
Hi, after installing antergos using any desktop environment, i get english names of folders in my Home (Downloads, Music, etc.) it looks like “xdg-user-dirs-update” is not runned at first boot.

**Comment by karasu** [comment]
Looking at postinstall.sh, xdg-user-dirs-update is run in all DE's (except Openbox).

**Comment by karasu** [comment]
Problem: user-dirs.locale has C locale in it when using XFCE (I'm sure in other DE's is the same).

**Comment by karasu** [comment]
`xdg-user-dirs-update --force` fixes it.

**Comment by karasu** [comment]
I can't find out why xdg-user-dirs-gtk-update does not work, because it exists in /etc/xdg/autostart
In my tests (also in Gnome in our liveCD) running it manually works, but it refuses to autostart itself.

**Comment by karasu** [comment]
In /etc/xdg/user-dir-update-gtk.desktop
changing
`OnlyShowIn=GNOME;LXDE;Unity`
to
`OnlyShowIn=GNOME;LXDE;Unity;XFCE;Mate`

fixes the issue.

**Comment by lots0logs** [comment]
@karasu is that file provided by the package? If so, we should probably submit a bug report to arch. If the file is provided by the upstream developers and not arch packaging then of course the bug report should be sent upstream instead.

**Comment by karasu** [comment]
I must be stupid, because I can't find the file anywhere. Is it auto generated?

**Comment by karasu** [comment]
It's upstream. Gnome, in fact. xdg-user-dirs-gtk
But it seems that reporting it is useless:
https://bugs.freedesktop.org/show_bug.cgi?id=61341
https://bugs.freedesktop.org/show_bug.cgi?id=33107

**Comment by lots0logs** [comment]
Wow :unamused:

**Comment by karasu** [comment]
0.13.155 fixes it.
