### ISSUE TITLE
[Minor Enhancement] Add new emojis to pidgin

### ISSUE THREAD

**Issue by chrisvella** [Antergos/Cnchi#466]
This is a really trivial enhancement for pidgin. This adds a number of new emojii's to the chat. This specifically improves compatibility with Android, however ios is also available.

git clone https://github.com/nobuyukinyuu/pidgin-emoji
cp -r hangouts-color/ ~/.purple/smileys/hangouts-color
Tools → Preferences → Themes → Smiley Theme → Hangouts (This step will need to be adapted for the installer)

**Comment by karasu** [comment]
mmmm.... I think this should be a package and not something that Cnchi does on its own. @chrisvella , 
please, if you want this to happen, you can ask for a package here: https://github.com/Antergos/antergos-packages/issues
I'll close this one.
