### ISSUE TITLE
Cnchi is up to date but thinks to be outdated

### ISSUE THREAD

**Issue by Danysan1** [Antergos/Cnchi#468]
I'm trying to install Antergos (with the live image antergos-2015.11.14-x86_64.iso on an usb stick), and the notification says that Cnchi is up to date, but when I try to install it says tha it isn't up to date.

Here's a screenshot:
![schermata da 2015-11-21 09-19-32](https://cloud.githubusercontent.com/assets/8406735/11317771/4231761c-9032-11e5-9fe4-ac305be7849c.png)

Here's the content of /tmp/cnchi.log:
https://gist.github.com/Danysan1/328c5e295b80d10d21c3

**Comment by pythoneer** [comment]
related https://github.com/Antergos/Cnchi/issues/462

**Comment by Danysan1** [comment]
Sorry, didn't see the older issue.
