### ISSUE TITLE
Can't click next to get passed requirements screen

### ISSUE THREAD

**Issue by rrittenhouse** [Antergos/Cnchi#469]
I have a Lenovo T430 that I am trying to install Antergos onto. I downloaded the ISO last night via the torrent (I even checked the MD5). I wrote it to a USB Drive using USB-Writer for windows.

It boots up and is perfectly usable in live mode. When I click "Install Now" in Cnchi, it asks for my language which I select and then click ">" at the top. Next is the requirements screen. Everything has a green check besides the last one; it has a red circle with a slash through it and the text beside it says "Cnchi is up to date" and the ">" arrow is disabled and I can't move forward with the install.

I did end up letting it sit there for a while last night. I came back out of frustration to see that I could click "next" (about 30 minutes later) and it proceeded to install. However, when I got to the screen where I enter my username, password, first name, last name details (while its installing), any character that I typed, was either in some other language or it was garbled text that looked nothing like it should in my language (English).

I asked on IRC to no avail but Mikaela was nice enough to point me to the Antergos Github to file an issue. Please let me know if this is the incorrect spot to file this.

Thank you

**Comment by Wyn10** [comment]
Post the cnchi log.  It's in ```/tmp/cnchi.log```

**Comment by rrittenhouse** [comment]
I started having issues with my router today. I fixed those issues and now I was able to go through the screens with no issues at all. As a final resort last night, I launched the installer from the command line and did see that it was trying to rank the different mirrors, it just wasn't showing any errors.

Thanks again and my apologies for it being my issue!

**Comment by karasu** [comment]
@rrittenhouse No worries. Thanks for reporting it anyway. Glad you sorted it out. I hope you enjoy Antergos.

Cheers!
