### ISSUE TITLE
Package integrity check fails

### ISSUE THREAD

**Issue by szungy** [Antergos/Cnchi#473]
Hey guys

I'm trying to install Antergos but Cnchi fails right after downloading the packages with "Can't install necessary packages. Cnchi can't continue."

According to https://antergos.com/wiki/miscellaneous/frequently-asked-questions/ this is just a "pretty" error so I guess it will only make sense with a full log.

https://goo.gl/FwV5mE

I was using the latest iso from the official site (antergos-2015.11.14-x86_64.iso).
Both the full live ISO and the minimal ISO produce the same error.
I tried to install it on my regular hw and a virtual machine too, the results are the same.

At the very end of the log there are a few lines about the error, with more details:
http://pastebin.com/raw.php?i=17eNs2xC

This is the actual exception, breaking the installation:
2015-11-27 00:02:30 [ERROR] pac.py(161) finalize_transaction(): Can't finalize alpm transaction: transaction failed, pm_errno 33 (invalid or corrupted package), []

#367 Is somewhat similar to this. (Except that I don't see any signature errors.)
I tried installing a bunch of times and it looks like the package at which the corruption is detected is absolutely inconsistent.

**Comment by lots0logs** [comment]
I think that some of Arch's package maintainers are making minor changes to packages without bumping the `pkgrel`. It only poses a problem under our very specific use-case so there's no need to track down who is doing it. We will just handle the issue within Cnchi.

**Comment by lots0logs** [comment]
Tracking this on the original issue: #363
