### ISSUE TITLE
[Suggestion] Add music player and mail client to GNOME install.

### ISSUE THREAD

**Issue by artur9010** [Antergos/Cnchi#474]
https://wiki.gnome.org/Apps/Rhythmbox - music player
https://wiki.gnome.org/Apps/Geary - email client

**Comment by lots0logs** [comment]
We appreciate your suggestions. However, I don't think these are necessary. We want to keep the set of applications installed by default as minimal as possible while still providing all essential functionalities.

For GNOME we already include GNOME Music (and totem) for media playback. A desktop e-mail client 
is not something we consider essential for the majority of users. Of course, for those users who need a desktop email client, it's easy enough to install one using the package manager. 

In anycase, thanks for taking the time to give us feedback :smiley:
