### ISSUE TITLE
Some packages give a sha256 sum error, randomly (or so it seems).

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#477]
![antergos_sha256_error](https://cloud.githubusercontent.com/assets/175797/11457010/171ccc8a-969d-11e5-8ac9-16c464306599.png)

**Comment by karasu** [comment]
https://forum.antergos.com/topic/3272/can-t-install-necessary-packages-cnchi-can-t-continue-multiple-times

**Comment by lots0logs** [comment]
Tracking this on #363
