### ISSUE TITLE
Remove pidgin from gnome installation (or make optional)

### ISSUE THREAD

**Issue by artur9010** [Antergos/Cnchi#478]
I'm not using pidgin, make it optional or remove ;)

**Comment by lots0logs** [comment]
:laughing: ..Sorry I couldnt help myself. Obviously we arent going to remove a package because one person doesnt use it. Its easy enough to uninstall it and since antergos is a rolling release you should only have to uninstall it once :wink:

**Comment by artur9010** [comment]
https://github.com/Antergos/Cnchi/issues/474

"We want to keep the set of applications installed by default as minimal as possible while still providing all essential functionalities." ;)

**Comment by karasu** [comment]
I think it was added because we thought that having a chat client was an essential functionality.
Of course, this is debatable.

We will consider this (I myself don't use pidgin at all).

Thanks for sharing your point of view.

Cheers!
