### ISSUE TITLE
Pacman :: db.lck :: Pamac conflict

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#480]
Is Antergos ISO using pamac?

If the answer is yes Cnchi should stop pamac-daemon to avoid db.lck error when updating databases.

**Comment by Wyn10** [comment]
2015.11.14 iso includes pamac.

**Comment by lots0logs** [comment]
Its included on the ISO but its not enabled so it only runs if the user starts it manually.

**Comment by karasu** [comment]
I'll add a check to Cnchi anyway.

**Comment by Yoshi2889** [comment]
Has this check been added?
