### ISSUE TITLE
The Cnchi 0.12.46 installer stucks when Hostname is clicked

### ISSUE THREAD

**Issue by devtons** [Antergos/Cnchi#496]
When I was trying to install Antergos in VMware the installer got stuck when I clicked the Hostname textbox to edit it, therefor it was impossible to proceed the installation, because it stopped Antergos completely (as far as i know)

**Comment by lots0logs** [comment]
@devtons Please post a [paste2 link](http://paste2.org) for the installer log. You can find it in `/tmp/cnchi.log`. Thanks.

**Comment by devtons** [comment]
Sorry, but i got past the problem in some wierd way. I guess i just clicked around until it worked and changed my hostname and username in the terminal later. I'll see if I still have the /tmp/cnchi.log still. And btw, Antegros is lovely!

**Comment by stratus-ss** [comment]
@lots0logs this one looks like you can close it
