### ISSUE TITLE
Animation:: Loading animation is broken

### ISSUE THREAD

**Issue by 3xal** [Antergos/Cnchi#502]
When i open any program, circle loading animation does not work correctly.
![broke_animation](https://cloud.githubusercontent.com/assets/16667588/12265952/8c4567ae-b940-11e5-8ff7-159242fe9f72.jpg)

**Comment by karasu** [comment]
I'm sure this is not Cnchi's fault... 

@lots0logs do you know what this might be? I'm also seeing this in a laptop (nvidia, Gnome3).
Should we report this upstream? Is numix fault?

**Comment by lots0logs** [comment]
@karasu I'm not sure. Could you confirm whether or not it happens with the default Adwaita theme?

**Comment by karasu** [comment]
@lots0logs I can confirm it does NOT happen with the Adwaita theme. Just open Gnome3 session and change themes, open an Internet browser, you'll see what @3xal means.

**Comment by karasu** [comment]
@lots0logs https://forum.antergos.com/topic/3541/gnome-3-18-program-loading-icon-in-top-bar-is-distorted-video-example/2

**Comment by stratus-ss** [comment]
The thread has been marked Solved as it appears to have been a problem with the theme makers themselves (they needed to update their themes to support the latest version of GNOME).
