### ISSUE TITLE
Prevent boot errors for nvidia users by adding nouveau.modeset=0 option

### ISSUE THREAD

**Issue by polarathene** [Antergos/Cnchi#503]
Booted via usb and encountered a white screen followed by being reset into bios. Pressed `e` key at boot selection to add the `nomodeset` flag, this did not seem help like it has for previous distro's, but `nouveau.modeset=0` works great. 

If it's possible to detect nvidia cards or nouveau driver in use, perhaps add this to the boot parameters or provide an additional option for nvidia users? From what I've learnt the issue may only be with newer nvidia hardware that nouveau does not properly support yet. This only appears to be an issue during the live media/install process so I don't see any harm in doing this work around?

I realize most users trying out Antergos are probably the kind who can figure out this issue themselves or already know the solution like I did, but a quick fix by having an additional boot option with a clear description would be great and helpful to those who aren't aware of how to fix this and need to search community forums/google.

**Comment by lots0logs** [comment]
You are correct that the issue only occurs with the very latest nvidia cards. This is because there is a delay between the release of a new card and support for the card being added to nouveau. However, the majority of nvidia users will be using cards that are supported so adding the nomodset boot option as default is a no go. Sorry! Thanks for the feedback though, we do appreciate it :smile:

**Comment by polarathene** [comment]
@lots0logs Does it harm other nvidia users with the live install at all? Or as an option to select? I'm not advising this for the actual boot of the installed OS just for running the live image. My system works fine without adding `nouveau.modeset=0` to grub. 

My hardware is about 2 years old with no indication of how long until nouveau supports 8xx cards fully let alone users with 9xx cards. I was of the understanding that Arch was bleeding edge which would be attractive to users with newer hardware? Antergos being focused on providing a smooth setup/installation to getting Arch running, I'm confused why adding an additional boot option for troubleshooting nvidia users would be a problem? Do you have any stats on your userbases hardware?

I'm fine adding the parameter myself, it's not like I need to do it much. I just felt Antergos would benefit from the addition which would fit in with "[Users need not be linux experts nor developers in order to use Antergos](https://antergos.com/about/)", if you feel differently about that I can totally respect such :)

**Comment by lots0logs** [comment]
Using that boot option limits the resolution of the display, if I'm not mistaken, to 1024x600. Based on your feedback, I think its worth looking into further to ensure we are handling it appropriately (so I'll make sure we do look into it)

**Comment by polarathene** [comment]
I don't think I've experienced the 1024x600 resolution, but I'm on a laptop which has integrated graphics from intel which might have been the fallback? Glad to hear you're reconsidering this, it's one less frustration to encounter :)
