### ISSUE TITLE
System Config :: Fails With Error - timesyncd.conf not found

### ISSUE THREAD

**Issue by ShrewdSpirit** [Antergos/Cnchi#508]
Hello. I get [Error 2] No such file or directory: '/install/etc/systemd/timesyncd.conf' error when installing Antergos. My Cnchi version is 0.12.45
I've updated Cnchi using pacman -R cnchi && pacman -S cnchi

**Comment by lots0logs** [comment]
Hi, please post a [paste2 link](http://paste2.org) to the full installer log (located in the `/tmp` directory.

**Comment by ShrewdSpirit** [comment]
When I receive that error message, Cnchi clears the log file

**Comment by karasu** [comment]
That's odd. Are you sure there is no /tmp/cnchi.log file?

**Comment by ShrewdSpirit** [comment]
There is a cnchi.log file but with no contents in it. Lemme retry installing

**Comment by ShrewdSpirit** [comment]
Ok, this time it didn't clear the log file. But it's a big file and takes a while to be uploaded with my bad internet

**Comment by karasu** [comment]
@ShrewdSpirit : If you really have a bad Internet connection I'm afraid I can't recommend you using a rolling release distribution like Antergos. You'll have to download a big amount of packages... and each week a lot of new updates are published. Of course, do as you will... ;)

**Comment by ShrewdSpirit** [comment]
My upload speed is super low. I have no problems with download ;) Is all parts of the log needed or can I just give you the parts after installing packages? Looks like paste2.org doesn't allow uploading large files (23 megabytes)

**Comment by ShrewdSpirit** [comment]
Last parts of /tmp/cnchi.log http://paste2.org/XEMJgLf4
Whole file is ~23 megabytes and I cannot paste it

**Comment by karasu** [comment]
@ShrewdSpirit : Enable ntp in the time map screen. I think you have found a bug.

**Comment by ShrewdSpirit** [comment]
Though I'm using minimal ISO on virtual box and using a separate /var partition to avoid redownloading all of those packages ;)

**Comment by ShrewdSpirit** [comment]
I have tried with both NTP enabled and disabled and I still get the same error

**Comment by karasu** [comment]
My bad. You have a lot of missing file errors:
```
2016-01-15 08:29:03 [DEBUG] chroot.py(136) run(): chroot: failed to run command ‘systemctl’: No such file or directory
2016-01-15 08:29:03 [DEBUG] install.py(647) enable_services(): Service 'lightdm' has been enabled.
2016-01-15 08:29:03 [WARNING] install.py(649) enable_services(): Can't find service NetworkManager
2016-01-15 08:29:03 [DEBUG] chroot.py(136) run(): chroot: failed to run command ‘systemctl’: No such file or directory
2016-01-15 08:29:03 [DEBUG] install.py(647) enable_services(): Service 'ModemManager' has been enabled.
2016-01-15 08:29:03 [DEBUG] chroot.py(136) run(): chroot: failed to run command ‘systemctl’: No such file or directory
2016-01-15 08:29:03 [DEBUG] install.py(647) enable_services(): Service 'haveged' has been enabled.
```

We really need the full log.... :disappointed:

**Comment by Yoshi2889** [comment]
Is this still a bug?

**Comment by karasu** [comment]
Never got a follow up.... Closing.
