### ISSUE TITLE
Installation Font

### ISSUE THREAD

**Issue by robertda** [Antergos/Cnchi#509]
Futura Medium font does not contain all Latin-B characters, so, for Romanian language installation, latin-b characters ș / Ș / ț / Ț look ugly (U+0218, U+0219, U+021A, U+021B).

**Comment by lots0logs** [comment]
That font is not used on anything other than our logo (or at least it shouldnt be). If you are seeing it used in other areas please post screenshots. Thanks!

**Comment by robertda** [comment]
I was wrong - **all** Romanian specific characters (ă, â, î, ș, ț and uppercase) are displayed weird.

![captura de ecran din 2016-01-15 19-22-01](https://cloud.githubusercontent.com/assets/11921426/12359979/d741a8b0-bbbd-11e5-8374-315fbd3b5167.png)

![captura de ecran din 2016-01-15 19-22-52](https://cloud.githubusercontent.com/assets/11921426/12359984/dda11056-bbbd-11e5-9541-be6aa678e9fc.png)

![captura de ecran din 2016-01-15 19-23-33](https://cloud.githubusercontent.com/assets/11921426/12359986/e1bd53a2-bbbd-11e5-90d9-3b7f3b15fbd9.png)

**Comment by lots0logs** [comment]
I see..that's not Futura though. Its Lato. This is something I forgot :sweat_smile: . It's noted on #292
