### ISSUE TITLE
LXQT Metapackage typo

### ISSUE THREAD

**Issue by robertda** [Antergos/Cnchi#510]
Is not [pcmanfm-qt](https://github.com/Antergos/Cnchi/blob/master/data/packages.xml#L252)?

Update:
Sorry, didn't remember if LXQt was included on list of 6 default desktops :)

**Comment by karasu** [comment]
It is not, yet. But thanks anyway (I'll check it).

**Comment by karasu** [comment]
Fixed in development. Thanks!
