### ISSUE TITLE
Cnchi cannot install Antergos if Asturian and KDE are selected

### ISSUE THREAD

**Issue by enolp** [Antergos/Cnchi#511]
If you try to install Antergos with Cnchi and you select Asturian as language for the installer, KDE cannot be installed because there is no kde-l10n-ast package in the repository, unless Antergos developers build it.

![screenshot_20160116_204638](https://cloud.githubusercontent.com/assets/16736782/12374116/5311d800-bc92-11e5-89a6-37d85626bf82.png)

![screenshot_20160116_204649](https://cloud.githubusercontent.com/assets/16736782/12374117/532c1152-bc92-11e5-80e7-783dcd78df44.png)

**Comment by lots0logs** [comment]
Hi, it looks like Arch doesnt package `kde-l10n-ast`. I recommend submitting a bug report to request the package. 

Ref: http://i18n.kde.org/team-infos.php?teamcode=ast
Ref: https://www.archlinux.org/packages/?sort=&q=kde-l10n

**Comment by enolp** [comment]
I'm going to do that, but please don't close this bug until is solved from Arch.

Thank you for your support.

**Comment by enolp** [comment]
@lots0logs [kde-l10n-ast](https://www.archlinux.org/packages/extra/any/kde-l10n-ast/) is now in Arch Linux Extra repo. Can you undo your workaround in second post please?
