### ISSUE TITLE
Packages:: Support "Libre" Only Package Selection

### ISSUE THREAD

**Issue by ThePreviousOne** [Antergos/Cnchi#514]
I tried changing the pacman.conf in the Live System to Parabola but Cnchi failed (I forget how, this was like 6 months ago) could it be added as an option?

**Comment by karasu** [comment]
You can do a normal install and then make the change (I know it's not an ideal solution, but works).
https://wiki.parabola.nu/Migration

**Comment by ThePreviousOne** [comment]
Yes I know, but as you said not ideal and the first few times I did that I had problems. I'd create the PR myself if I knew python better and knew what to look for.

**Comment by karasu** [comment]
Thanks Greg. It's not that simple because we should check all our own packages (in Antergos repository) to check if they're "libre" or not, and then modify Cnchi to not to install those packages.

**Comment by Yoshi2889** [comment]
Is this really feasible to do, due to Arch's design? We'd essentially be making Antergos an installer for both Arch and Parabola if we put this through.

**Comment by karasu** [comment]
Yeah, I don't see it now. Antergos has too many "non-libre" packages in its repository. It has never been our goal to become a "libre" distro. Will close it as I don't think it makes sense now. Thanks!
