### ISSUE TITLE
[ERROR] partition_module.py(115) get_devices(): Failed to read partition table from device /dev/mmcblk0rpmb

### ISSUE THREAD

**Issue by Aufstand** [Antergos/Cnchi#517]
I had this problem the first time I installed Antergos three months ago. And happened again this night. Happens in automated install and if you choose where to install Antergos, again and again and again. 

I was able to install Antergos by making the partitions manually in gparted and selecting choosing where to install it. Everytime I flagged a partition as /, boot or swap, the error appeared. And everytime I clicked on the partitions. Cnchi was fully updated. I have a laptop, an Acer Aspire E11 ES1.

Here is the log, which is really full of text.

[cnchi.txt](https://github.com/Antergos/Cnchi/files/109314/cnchi.txt)

**Comment by karasu** [comment]
Hi @Aufstand ,

I'm sorry for your troubles. Stable version still does not support mmcblk devices (like yours). We've fixed our code in what is going to be Cnchi 0.14, but to be honest, we do not have any hardware to test it on, so it might still not work (so maybe I'll ask you some help in the future to test this out, if you don't mind).

Thanks for your patience and comprehension.

Cheers!

**Comment by Aufstand** [comment]
Actually, I'm writing from my laptop in Antergos, so I was able to install it after making the partitions with gparted. And this is the second time I do it (reinstalled to clean up the computer).

If I can serve as any help, just tell.

¡Un saludo!
