### ISSUE TITLE
Blog :: Release Post

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#521]
- [ ] Intro paragraph
- [x] v0.12 series usage stats.
- [ ] v0.14 dev cycle overview paragraph.
- [x] v0.14 dev cycle stats
- [x] Change log

**Comment by karasu** [comment]
@lots0logs This will have to wait until tomorrow morning (that is, if you want me to help with it) ;)

**Comment by lots0logs** [comment]
@karasu That's fine :+1: . (In fact it will have to wait because I have to work today so I won't have time)

**Comment by stratus-ss** [comment]
@lots0logs I believe given the age of this and the version of cnchi that this issue can be closed
