### ISSUE TITLE
Issue with Cnchi on the Antergos minimal iso

### ISSUE THREAD

**Issue by kkraku** [Antergos/Cnchi#530]
Just asking if anyone else had an issue where they get to any screen mentioning partitioning and the top bar goes black and the UI glitches? I was still able to click the required settings from memory but it was really annoying. All the UI elements dissapeared. I am on 0.12.47 - the latest version shipped with the minimal iso which I downloaded this morning.

**Comment by lots0logs** [comment]
Hi, could you try the minimal image that is in testing right now and let us know the result? Thanks!

https://build.antergos.com/browse/testing

**Comment by doeixd** [comment]
I can confirm this. This just happened to me with that iso

**Comment by 0x587669** [comment]
same here.

**Comment by pioutw** [comment]
same for me too (cpu 32bit non-SSE2)

**Comment by enno09** [comment]
The problem still exists with new antergos-minimal-2016.02.19-x86_64.iso
Tested on an asus n3150i-c mainboard with an intel celeron 3050 and integrated graphics.
The problem started with selecting the language.

**Comment by ikselven** [comment]
Can confirm this issue with antergos-minimal-2016.02.21-x86_64.iso, trying to install via usb key on a uefi system.

**Comment by theSoenke** [comment]
Same problem here with antergos-minimal-2016.02.21-x86_64.iso

**Comment by stratus-ss** [comment]
@theSoenke @ikselven @enno09 I cannot reproduce this with the latest minimal iso, can you confirm if this issue is still present?

Thanks

**Comment by ikselven** [comment]
Did a quick test installing Antergos in a virtual machine using antergos-minimal-17.1-x86_64.iso and everything worked fine. I cannot test it on real hardware though.

**Comment by kkraku** [comment]
No longer have that hardware or an Antergos install. I'll try that ISO on a Lenovo Ideapad soon.

**Comment by stratus-ss** [comment]
I also couldn't reproduce this. I am going to close this for now. We can reopen if it crops back up
