### ISSUE TITLE
[Testing] [ISO: 2016-02-08] [Arch: X86_64] Test Report

### ISSUE THREAD

**Issue by blackdevil72** [Antergos/Cnchi#534]
This is my first test with the ISO :

-> Iso was copied on an USB stick with Rufus 2.6 on Windows 7.
-> Hardware : 2010 HP EliteBook 8540p
-> Tested on Wifi 2.4GHZ ans 5GHZ with WPA-PSK [TKIP] + WPA2-PSK [AES] on both.

Issue :
-> Wifi 2.4GHZ can't connect if the WPA2 key include capital letters (work fine with lower case)
-> Wifi 5GHZ doen't work while the hardware support it
-> when cnchi reach 100% in the install process all the system freeze except mouse

cnchi :
-> cnchi start its update itself when connected
-> cnchi version after update is 0.12.47 (not sure if it's the last one)
-> cnchi when lookup everything is good state "cnchi is up to date" while the logo stay red like it isn't

options used :
-> language : french // location : france // time zone : Europe - Paris // keyboard : fench (alternative)
-> other : firefox // firewall // Steam + POL // bleutooh // print support // SMB // Libreoffice

Thats all I can say at the moment I will do other tests soon to have more details. The Wifi problem is quite annoying and might be caused by a miss configuration of the network manager.

-- Nekosan --

Forum nickname : nekosan

**Comment by karasu** [comment]
>cnchi when lookup everything is good state "cnchi is up to date" while the logo stay red like it isn't

We're working on this.Thanks!
