### ISSUE TITLE
[Testing] [antergos-2016.02.08-x86_64] Test report MATE

### ISSUE THREAD

**Issue by nitrogensky** [Antergos/Cnchi#538]
Loaded on a Dell Inspiron i5 in a VM using 2 cores and 2 Gigs RAM and 30 Gig HD.

1. Cnchi updated to 0.12.47
2. Could not find ZFS option when trying to partition manually (EXT3, EXT4, etc. were all there)
3. MATE worked perfectly. The only issues I found were known MATE bugs and have nothing to do with any issues resulting from the install. I tried every option in the Control Center, installed packages, themed, re-themed, customized themes, tried all panel options, tested video and audio and found no problems.

**Comment by lots0logs** [comment]
Hi,

If you would like to help us test ZFS, you can install the `cnchi-dev` package to the ISO. Close Cnchi when it starts and then open a terminal and run `sudo pacman -Sy cnchi-dev --force` We are tracking ZFS testing over on #524 

Thanks!

**Comment by nitrogensky** [comment]
Thanks. I'll give it a go.

**Comment by karasu** [comment]
Oh, and zfs is only available in automatic installation, not in advanced.

Thanks!

El divendres, 12 de febrer de 2016, nitrogensky <notifications@github.com>
va escriure:

> Thanks. I'll give it a go.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Antergos/Cnchi/issues/538#issuecomment-183181351>.
>


-- 
Enviat amb el meu Iphone
