### ISSUE TITLE
Kill Flash

### ISSUE THREAD

**Issue by 0x587669** [Antergos/Cnchi#540]
I cant fucking belive you have Flash installed by defualt not even an option in the installer, why would you install Flash the software which is like why many people get fucked in the ass from EKs. I noticed it was installed like a week after I installed Antergos completely shocked to say the least? I can go on and on why Flash is shit and what security risk you put your users through by doing this. I hope you take this seriously and remove it ASAP!

**Comment by lots0logs** [comment]
Btw, had you taken the time to perform a quick search of our github issues you would have noticed that this issue has already been addressed in our development version and will be released to stable soon. If you cannot communicate without being disrespectful and hostile please refrain from creating any further issues as they will be ignored. Thanks.
