### ISSUE TITLE
English Confirmation string

### ISSUE THREAD

**Issue by prescott66** [Antergos/Cnchi#544]
I get this Confirmation string in english, even it is translated on Transifex.
![snimka obrazovky z 2016-02-21 11-07-46](https://cloud.githubusercontent.com/assets/735265/13202051/02461380-d88c-11e5-8edb-a3301fe4aa5d.png)

**Comment by karasu** [comment]
@lots0logs Cnchi strings are updated automatically, aren't they? I've checked transifex and sk.po and @prescott66 is right, string is there. And we have _() surrounding that title text. I don't know whats wrong.

**Comment by lots0logs** [comment]
@karasu I'll take a look at it asap!

**Comment by prescott66** [comment]
i have many other strings in english.transifex shows 100% slovak translation and that is a mistake...maybe it is needed to take look, if POT is actual.

**Comment by lots0logs** [comment]
I checked and that string's translation is included in the MO file that is on the ISO. @prescott66 If you have other examples of strings that still aren't showing the translations please open a new issue for them.
