### ISSUE TITLE
Cnchi Proxy Settings

### ISSUE THREAD

**Issue by urdarinda** [Antergos/Cnchi#546]
1. Make the cnchi launcher use environment variables. It does not detect proxy settings automatically, we have to manually give it using terminal (sudo -E)
2. Change proxy on the fly, once cnchi has started there is no way to change proxy if we have to. It can read proxy variables every new download?

**Comment by danboid** [comment]
+1

I'd like to see this took a step further and, after (or on the same screen as) selecting the language for installation, cnchi should give the user the option to enter proxy settings before it checks for internet access. cnchi shoud be all about user-friendliness and it should require the user to remember the env var for setting proxies.

As a side note, I'm disappointed that the full Antergos ISO cannot be installed without a net connection. I can understand this being needed when using the minimal install iso but not being able to install the full (live) OS iso without a net connection kinda defeats the point of the full-fat version for me.

**Comment by gaborbernat** [comment]
is there a tutorial how to set this? 

I get now only failed retrieving file antergos.db, being behind a proxy ... :cry:

**Comment by kujaw** [comment]
Any update on this issue? I'm trying to install AntergOS and I'm behind company's proxy.

**Comment by gaborbernat** [comment]
@karasu it does not work for me :cry:

**Comment by karasu** [comment]
@gaborbernat I'm not sure, but could you try using those vars in their capitalized form? Like this:
```
export HTTP_PROXY=10.10.1.10:3128
export HTTPS_PROXY=10.10.1.11:1080
export FTP_PROXY=10.10.1.10:3128
export RSYNC_PROXY=10.10.1.10:3128
sudo -E cnchi
```

Obviously you have to change those values with the ones your proxy is using.

**Comment by gaborbernat** [comment]
nope, that does not work either; I've taken a look and it seems the proxy variables are stripped away at some invocation level, so I've replaced with a direct invocation after setting the proxies:

```
sudo -E python3 /usr/share/cnchi/cnchi/cnchi.py 
```

That made it work, it's running now, let me see if it finishes without errors.

**Comment by neel** [comment]
One more point to note. Sometimes cnchi refuses to quit properly. So next time you try to open you get an exception.

```
sudo rm /tmp/.setup-running
sudo -E python3 /usr/share/cnchi/cnchi/cnchi.py -d -v
```

**Comment by ruefo** [comment]
@gaborbernat now you can call the binary (paths changed):
```
sudo -E /usr/share/cnchi/bin/cnchi
```

**Comment by karasu** [comment]
There is now a proxy dialog that lets you setup your proxy settings. Closing.

**Comment by chummmer** [comment]
Sorry to intervene, but I cannot install Antergos 18.11 (cnchi 0.16.21) behind a corporate proxy on Virtualbox. It doesnot work either via setting the proxy as environment variable in the terminal, nor in the cnchi GUI installer. 

I tried to set up the proxy via root in the terminal as described above. I checked with wget and curl that I have internet access, all OK. Then I started cnchi from this terminal, and did not have an internet connection in the installer.

When I try to set up the proxy in the installer (Buttion: "I'm behind a proxy"), I enter the proxy settngs.
I have to provide a username and password, it is a corporate proxy.

proxy address:     <user>:<password, url encoded>@some-proxy-address 
Port :  3128 for http
port: 8080 for https

No internet connection.

When I click the left arrow in the cnchi gui (go back) and then going again into the proxy settings,  un the filed for the proxy server address only <user> is entered and the remaining address <password, url encoded>@some-proxy-address:3128 is in the <port> field.

I assume that internally cnchi is concatenating the proxy server url with ":" with the port and then splitting the whole address by ":" again. Which is obviously wrong.

**Comment by neel** [comment]
If you already have cnchi running close it 
`sudo rm /tmp/.setup-running`

After you set up the environment variables you need to run the actual python script with `sudo -E` that runs the program with root privilege with the environment variables of the current user.

To find out the actual python script run `which cnchi`. That you show you the actual path to the python script. You may open that file and check its contents. If its a single line file that runs a different `.py` file open that file instead. Ultimately you will get the path to the python script taking two command line options `-d -v`. The exact paths to the files may vary depending on the Antergos version. 

I installed in Feb 21 with the following path
`sudo -E python3 /usr/share/cnchi/cnchi/cnchi.py -d -v`

This might change in the current version.

**Comment by chummmer** [comment]
I was logged in as root. So it put the proxy environment settings as root and ran the cnhi script as root within the same shell. i ran the original python command /usr/share/cnchi/scripts/cnchi.py, it was not located in /usr/share/cnchi/cnchi as described above.

**Comment by neel** [comment]
I don't have an installer with me. If the file `/usr/share/cnchi/scripts/cnchi.py` only a few lines can you paste it's content ?
