### ISSUE TITLE
Systemd-boot problems with the latest version of cnchi v14

### ISSUE THREAD

**Issue by LiberteCzech** [Antergos/Cnchi#547]
### Problem:
Now I have to reinstall the system using the latest stable .iso media from 21.2. and cnchi v14 after being elected systemd-boot bootloader finishes installing and write on the screen that probably failed to install properly and not boot.

### Steps To Reproduce:
1.
2.
3.

###  

- Log

 Files
this is the part of chchi.log file: [http://paste2.org/M3y0KGdz]

![screenshot from 2016-02-26 10-15-44](https://cloud.githubusercontent.com/assets/13797292/13349498/9bedc89c-dc7a-11e5-8fa2-c5437b6bf034.png)

/boot … FAT32
/ … LUKS encrypted EXT4

![screenshot from 2016-02-26 00-34-52](https://cloud.githubusercontent.com/assets/13797292/13349289/21cf6544-dc79-11e5-999e-83b1539e15fc.png)
This image is in Czech language, but I think you know that it is a standard error message bootloader.

### Additional Notes:
It worked in the last testing .iso media releases with the latest version cnchi version v12.
Use UEFI-GPT.

**Comment by karasu** [comment]
We'll see, but I bet that with the last testing .iso it doesn't work now, because new systemd version.

I'll check it asap.
