### ISSUE TITLE
System check is not displayed

### ISSUE THREAD

**Issue by LiberteCzech** [Antergos/Cnchi#548]
### Problem:
System check is not displayed.

### Steps To Reproduce:
If no Internet connection, cnchi crashes which is correct.
If everything is all right it is also a blank screen, but continues with the installation.

### Log Files
![screenshot from 2016-02-26 10-12-54](https://cloud.githubusercontent.com/assets/13797292/13357136/43704a4e-dca9-11e5-9a0b-4d1337e0d075.png)

### Additional Notes:

Only a minor bug.

**Comment by karasu** [comment]
@LiberteCzech : I can't reproduce this. Do you mind trying again with:
`sudo -E cnchi -dv`
and post the log file here? (filename: /tmp/cnchi.log)

Thanks!

**Comment by LiberteCzech** [comment]
Here is the link, I hope will be helpful.
[http://paste2.org/ddF8AgM4](url)

**Comment by LiberteCzech** [comment]
Hi,
I tested cnchi-dev-0.14.62-1 and "system check" is fixed now.
Thanks for a repair.

**Comment by karasu** [comment]
Thanks to you for reporting it!
