### ISSUE TITLE
Antergos Installer Error on Macbook Air

### ISSUE THREAD

**Issue by elpagano3** [Antergos/Cnchi#554]
### Problem:

When it finished to downloaded all packages, it appears the message: Antergos Installer Error .
Im trying to install on a Macbook Air 2013 with BIOS Legacy mode. The Cnchi version is 0.14, the most recent version.

This is the second time that the problem appears, so i've decided after the first time to make a new installation usb.

**Comment by karasu** [comment]
First, check that you have the latest iso. Then, burn it to your usb with dd.

Try again, but if it fails, copy here the contents of the file /tmp/cnchi.log

Thanks!
