### ISSUE TITLE
Exception with GNOME selected

### ISSUE THREAD

**Issue by aklos** [Antergos/Cnchi#556]
### Problem:
Attempting install with GNOME 3 selected causes exception when all packages downloaded.

### Steps To Reproduce:
1. Select GNOME
2. Wait until all packages downloaded
3. Exception from corrupt package

### Log Files
- /tmp/cnchi.log output: http://paste2.org/E7sfCfM9

### Additional Notes:
Sometimes install goes through but it seems like the NVIDIA driver setup ends up broken because then neither lightdm nor gdm work.

Choosing a different shell like Cinnamon works completely fine, even when installing GNOME right after.

**Comment by karasu** [comment]
Thanks for reporting it. I'll check it asap

**Comment by stratus-ss** [comment]
I was unable to reproduce this inside of VirtualBox with installer 0.14.68

**Comment by karasu** [comment]
@stratus-ss : 
```
Can't finalize alpm transaction: transaction failed, pm_errno 34 (invalid or corrupted package
```
This means either a bad download or a "bad" mirror. In both cases we can't do anything about it.

Don't spend your time on this ;)
