### ISSUE TITLE
[question] disable downloading updates during installation?

### ISSUE THREAD

**Issue by riinav** [Antergos/Cnchi#558]
### Problem:

I am using full ISO to install antergos. After partitioning step it shows it's downloading lots of packages. 
The rank mirrors are usually slow (may be because of my location) and it takes forever to complete the downloading process.

Do we have any command line switch to disable package updates? We can always update the system once the installation is complete. why force us to download all the packages to complete installation?

since I am using full ISO, I have all the packages in the ISO to complete the installation.

**Comment by karasu** [comment]
Hi,

The installer always looks for the latest version of all packages. We should release an iso more often, to tell the truth. Did you use the latest iso?

You can bypass the rank mirrors process with:
`sudo -E cnchi -dv --disable-rank-mirrors`

So, first check /etc/pacman.d/mirrorlist and /etc/pacman.d/antergos-mirrorlist (they contain Arch mirrors and Antergos mirrors). Choose the ones that you think work/will be better for your location.
Then run cnchi with --disable-rank-mirrors (if not, cnchi will rearrange those files for you and you will lose all changes).

I hope this will help a little.

Cheers!

**Comment by stratus-ss** [comment]
The question has been answered and there has been no further discussion in more than 6 months... closing
