### ISSUE TITLE
Metalink for package virtualbox-guest-modules fails

### ISSUE THREAD

**Issue by DamonGant** [Antergos/Cnchi#560]
Because the package has been [superseeded by virtualbox-guest-dkms](https://www.archlinux.org/packages/community/x86_64/virtualbox-guest-modules/)

**Comment by lots0logs** [comment]
We need to hold off on taking any action on this right now. There is ongoing discussion on the Arch Dev mailing list regarding the change of virtualbox modules to dkms (and as of now it looks like they will be reverting the change)

**Comment by Psidium** [comment]
I manage to install today on the go by editing the line 53 in  `/usr/share/cnchi/hardware/virtualbox.py` from 
```python 
return ["virtualbox-guest-modules", "virtualbox-guest-utils"]
```
to
```python
return ["virtualbox-guest-dkms", "virtualbox-guest-utils"]
```
(Exactly what you've done in the master brach haha)
without having the hassle to update the whole cnchi to a dev version :stuck_out_tongue: 


(If you don't know how to change this line from terminal:
```shell
sudo nano /usr/share/cnchi/hardware/virtualbox.py
```
)

**Comment by toudi** [comment]
thank you so much! just in case, you have a minimal typo - the path is:

```
sudo nano /usr/share/cnchi/cnchi/hardware/virtualbox.py
```

**Comment by karasu** [comment]
@lots0logs as it easy to go back I changed it. Closing.
