### ISSUE TITLE
though you might want log file

### ISSUE THREAD

**Issue by n-a-m-e** [Antergos/Cnchi#561]
### Problem:
Install fail

### Steps To Reproduce:
1. bootup
2. wait for cnchi update
3. start install

### Log Files
http://paste2.org/fa35pPLk

### Additional Notes:
though you guys might want log file incase it helps with something, gonna keep on trying to install so far success record with cnchi is around 3/8 times

**Comment by DamonGant** [comment]
Are you behind a restrictive proxy or firewall? It seems like some packages downloaded failed to validate.

**Comment by n-a-m-e** [comment]
nope i wasn't behind any firewall or anything, when i retried it installed just fine :-)

**Comment by karasu** [comment]
This is either a mirror problem or a connection problem:
`can't finalize alpm transaction: transaction failed, pm_errno 34 (invalid or corrupted package), []`

Closing, as there is nothing we can do about it.
