### ISSUE TITLE
Cannot install inside VirtualBox, cnchi dies with "Can't find these packages: virtualbox-guest-modules"

### ISSUE THREAD

**Issue by stratus-ss** [Antergos/Cnchi#562]
### Problem:

cnchi crashes with Can't find these packages: virtualbox-guest-modules during installation in VirtualBox 5.0.14

### Steps To Reproduce:
1. Get the 2016.02.21 image
2. Boot image on VirtualBox 5.0.15_OSE
3. Run the installer select advanced partition options and gnome as the DE

### Log Files

[cnchi.log](paste2.org/mj2JyCtj)

### Additional Notes:

Found this while trying to reproduce [Issue 556](https://github.com/Antergos/Cnchi/issues/556)

**Comment by karasu** [comment]
Buff.... please Arch guys, make up your mind! :grinning: 

Now the dkms package is being used, but it's not clear this will stay or not...

**Comment by karasu** [comment]
@lots0logs What should I do? Change it to the dkms? Wait a bit more?

**Comment by karasu** [comment]
Well, I changed it in 0.14.67. We can change it back at anytime. Closing....
