### ISSUE TITLE
Cannot create download package list (metalinks)

### ISSUE THREAD

**Issue by satriani-vai** [Antergos/Cnchi#563]
### Problem:
'Cannot create download package list (metalinks). Check log output for details.'

### Steps To Reproduce:
1.
2.
3.

### Log Files
http://paste2.org/b3UPBOIe

### Additional Notes:
![virtualbox_antergos_09_03_2016_18_51_07](https://cloud.githubusercontent.com/assets/5981417/13644795/ec78a1f4-e627-11e5-8be0-ba6aad9b64df.png)

**Comment by karasu** [comment]
This is a duplicate of issue #562 
https://github.com/Antergos/Cnchi/issues/562
