### ISSUE TITLE
Need ability to install grub to whichever partition I want

### ISSUE THREAD

**Issue by scoronado12** [Antergos/Cnchi#568]
### Problem:

Need ability to install grub to whichever partition I want
### Steps To Reproduce:
1. Have a legacy MBR machine
2. Intend to install grub on to the same partition as the Antergos install.
3. Only see that installing to MBR is possible.
### Log Files

Not necessary

**Comment by slacka** [comment]
I agree with the decision to limit options when user does "Erase Disk and Install Antergos". However, when the user chooses "Chose Exactly Where". the kid gloves should come off. Ubuntu gets this and removes the limitations for power users in that part of the install. We should do the same. 

That said. Warnings are OK. But we should let the user break things if they know what they're doing.

**Comment by karasu** [comment]
From the Arch wiki:
"_Warning: GRUB strongly discourages installation to a partition boot sector or a partitionless disk as GRUB Legacy or Syslinux does. This setup is prone to breakage, especially during updates, and is not supported by the Arch developers._"

And we, Antergos developers, agree on this. If you are that expert, you can install without Grub installation, and before rebooting, install grub to the partition yourself. There are a lot of users that don't really know the difference between installing to disk or to a partition, so we prefer not allowing this "feature" to avoid hundreds of reports saying "my new Antergos installation does not boot".

Hope you understand.

Cheers!

**Comment by slacka** [comment]
Ubuntu also targets a novice crowd, but they do allow installing the bootloader to both "/dev/sdb" and "/dev/sdb1" in their expert install. If you put a warning, I doubt it would generate that many bug reports.

But if the devs have already agreed against this, please close as won't fix.

**Comment by karasu** [comment]
@slacka sorry I didn't answer sooner. I totally forget about this one. Anyway, as I said, we're not changing this (for the time being). Sorry.
