### ISSUE TITLE
LAMP feature needs an update (PHP7)

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#572]
i used your installer for the LAMP installation with the minimal installer.
It's a really great solution but you have to overhaul the file /etc/httpd/conf/mods-enabled/php.conf.

PHP is now in revision 7 so you should change:
```
LoadModule mpm_prefork_module /etc/httpd/modules/mod_mpm_prefork.so
LoadModule php5_module /etc/httpd/modules/libphp5.so
Include conf/extra/php5_module.conf
```
To:
```
LoadModule mpm_prefork_module /etc/httpd/modules/mod_mpm_prefork.so
LoadModule php7_module /etc/httpd/modules/libphp7.so
Include conf/extra/php7_module.conf
```
Otherwise Apache ( httpd.service ) wont run and send back following Error:
```
httpd: Syntax error on line 528 of /etc/httpd/conf ....
```

**Comment by Wyn10** [comment]
@karasu This can be closed :+1:.

**Comment by karasu** [comment]
ups... thanks!
