### ISSUE TITLE
Cannot create download package list (metalinks)

### ISSUE THREAD

**Issue by voepew** [Antergos/Cnchi#575]
Hello

Cnchi seems to be broken.
For now I can’t install any Antergos edition.

https://i.imgur.com/eRPBh2p.png

**Comment by locallycompact** [comment]
Also having this issue. The log seems to show this.

[ERROR] metalink.py(131) create(): Can't resolve these dependencies: python-gobject<3.20
[ERROR] download.py(145) create_metalinks_list(): Error creating metalink for package light-locker-settings. Installation will stop

**Comment by varlesh** [comment]
Also too #94

**Comment by mcnutty26** [comment]
Related forum topic from a few months ago (with temporary fix):
https://forum.antergos.com/topic/4072/antergos-installer-error

**Comment by JonathanReeve** [comment]
The temporary fix doesn't seem to work. As far as I can tell, Antergos is uninstallable.

**Comment by karasu** [comment]
@JonathanReeve and others. The error about "can't create metalinks" is a generic error. Therefore, many different things can cause it. A missing package in the repositories, a mirror that is not updated, ... 

You must check your log to see what's going on in your case.

**Comment by Wetrain** [comment]
I am also seeing this issue on the latest Cnchi

**Comment by karasu** [comment]
Hi, just to clarify, this issue does not depend on cnchi but on some problem in a mirror or even our server. @Wetrain would you be so kind to post here your log? It's created in the /tmp folder.

We've experienced some problems with our build server that have been solved recently. It could be that the mirror you're using still has the broken packages as it hasn't updated itself yet.

**Comment by Wetrain** [comment]
@karasu I managed to solve this by using only 1 mirror from the mirrors list in Cnchi.
