### ISSUE TITLE
Unable to install if repo is broken

### ISSUE THREAD

**Issue by ATrigger** [Antergos/Cnchi#580]
### Problem:
When you choose any DE except base you can encounter the problem when
repository is kinda broken and neither pacman nor cnchi cannot download neccesary packages.
Cnchi then aborts installation. 

### Steps To Reproduce:
You cannot reproduce it with 100% guarantee. It happens from day to day.
1. Choose any DE except base
2. Cnchi will not able to download some packages and just exit
3. ??????
4. Could do something better with this.

### Additional Notes:
Experience of the last installation - because of this i couldn't use pre-configured  MATE and could only use base installation.

**Comment by Wyn10** [comment]
You can find the installer log in /tmp/cnchi.log  Next time you receive the issue pastebin it so the issue can be seen and looked into.

**Comment by raul78** [comment]
I agree with ATrigger. I recommended Antergos to my friends, but some have abandoned it as the success of installation is just too random (bad repo -> downloading package fails -> broken installation). As for me, for the last few months every time I installed Antergos I ALWAYS copied my verified mirrorlist and antergos-mirrorlist to the pacman.d directory of the live installer, to avoid having to format and repeat the procedure. Hopefully cnchi has been (or will be) improved in the meantime.

**Comment by lots0logs** [comment]
This issue is not something we can control. Installation of plain Arch would also fail if there are mirror problems.

**Comment by Mikaela** [comment]
However plain Arch installation would only fail after all repositories specified in mirrorlist were broken. I have understood that Cnchi fails even if single one has a problem.

**Comment by karasu** [comment]
@Mikaela That's not correct. Tbh I do not recall how many tries it does to connect, and how many mirrors it tries (for the same file), too. Maybe the number of tries to different mirrors is too low, that could be changed. I'll look at it asap.
