### ISSUE TITLE
Cnchi screws up mkinitcpio.conf

### ISSUE THREAD

**Issue by Yoshi2889** [Antergos/Cnchi#589]
### Problem:
After installation, there are multiple MODULES and HOOKS entries. Cnchi treats the example entries as real entries and overwrites the lines, effectively uncommenting them and creating new, empty entries.

### Steps To Reproduce:
1. Install antergos
2. Check mkinitcpio.conf

### Log Files
Example:
- http://sprunge.us/EKCS

**Comment by karasu** [comment]
This is already fixed. Thanks for reporting it, though. 

https://github.com/Antergos/Cnchi/pull/576

**Comment by Yoshi2889** [comment]
I take it no new release has been put out, then? I installed today.

**Comment by karasu** [comment]
That's odd. Maybe Cnchi didn't update? I'll check it asap.

**Comment by Yoshi2889** [comment]
On the 4/22 ISO, I did get this error: __init__(): Cannot find /usr/share/cnchi/update.info file. Cnchi will not be able to update itself.

The version I used was 0.14.68.

**Comment by karasu** [comment]
0.14.68
That's an old version for sure.

We now use pacman to update Cnchi. That message is not a problem at all (it's from the old update method that now is not being used anymore).

I'll check our build server asap. Thanks!

**Comment by Yoshi2889** [comment]
Just checked, cnchi is listed as 0.14.68 in pacman here.

Op do 5 mei 2016 17:13 schreef karasu <notifications@github.com>:
