### ISSUE TITLE
Add SAMBA server feature

### ISSUE THREAD

**Issue by prescott66** [Antergos/Cnchi#594]
I am thinking for what is Samba function in Cnchi. Because after enabling Samba function while installation, samba server is not running nor is installed correctly(tried with MATE flavour).
Flavio Antonini created great tutorial, that could by implemented someway in Cnchi.

https://ws.forum.antergos.com/topic/3819/sharing-files-and-folders-with-samba-definitive-guide

**Comment by Arup65** [comment]
Cnchi enables Samba client, for Samba server you have to install it separately via sudo pacman-S samba and set the smb.conf file. Check Arch wiki.

**Comment by karasu** [comment]
@Arup65 is right, the feature was only intended to enable Antergos to navigate SMB resources with gvfs (so only act as a client).

Maybe we could add a new feature for SMB server installation.

**Comment by Arup65** [comment]
Instead of that why not do a script like Ubuntu where you right click folder to set sharing rather an all out home folder sharing.

**Comment by Mikaela** [comment]
> Maybe we could add a new feature for SMB server installation.

If you do that, will you also install `netatalk` and enable it so OS X users can access Antergos home directories from Finder (naturally providing username and password)?

**Comment by Arup65** [comment]
The issue with samba is that one has to be careful and implicit on whats being shared and what rights, so its better off to do it after install well understanding all the issues. Wouldn't mind a script from Antergos team that automates smb.conf config and with gui options to share folders with password or non password guest use.

**Comment by prescott66** [comment]
i thought this function enables and configures samba server...it would be nice to have one function merging samba client and samba server functionality

**Comment by slacka** [comment]
I agree with Arup65, installing Samba server by default opens up a whole can of security worms. We install ssh with installing a ssh server. We install chromium without installing a HTTP server. Samba should be no different. If the user wants it, it's a post install task.

**Comment by karasu** [comment]
OK, closing then.
