### ISSUE TITLE
mount: unknown filesystem type 'LVM2_member'

### ISSUE THREAD

**Issue by satriani-vai** [Antergos/Cnchi#595]
### Problem:
```
mount: unknown filesystem type 'LVM2_member'
You are now being dropped into an emergency shell.
sh: can't access tty; job control turned off

```

Options: LUKS + LVM

**Comment by satriani-vai** [comment]
Bootloader: systemd-boot

**Comment by ubergesundheit** [comment]
Can confirm. Tried to install with luks lvm systemd-boot

**Comment by ubergesundheit** [comment]
I solved it as follows:
- enter the systemd-boot menu by hitting up or down
- press `e` to edit the boot options
- modify the line to read `...... root=/dev/mapper/AntergosVG-AntergosRoot rw quiet` and press `enter`
- It should boot now.
- apply modifications made earlier to `/boot/loader/entries/antergos.conf` OR: Find out the uuid of your AntergosVG-AntergosRoot (`ls -la /dev/AntergosVG/`, `ls -la /dev/disk/by-uuid`)
- reboot
- reboot should work without issues

**Comment by satriani-vai** [comment]
Done
