### ISSUE TITLE
Systemd-boot repair bad kernel configuration for LTS

### ISSUE THREAD

**Issue by LiberteCzech** [Antergos/Cnchi#598]
### Problem:
When you select the installer cnchi I want LTS kernel, it installs the current LTS + current stable.
Current stable kernel is properly configured and starts.
LTS core has poorly assembled configuration file (line breaks) and systemd can not read.

*There are only illustrative demonstration.

esp/loader/entries/arch-lts.conf

**Thus, it should look**  like a conventional kernel
.......
title          Arch Linux (LTS)
linux          /vmlinuz-linux-lts
initrd         /initramfs-linux-lts.img
options        root=PARTUUID=14420948-2cea-4de7-b042-40f67c618660 rw
.......

**Thus creating cnchi post-installation configuration of the kernel LTS**
.......
title          Arch Linux (LTS)
linux          /vmlinuz-linux-ltsinitrd         /initramfs-linux-lts.imgoptions        root=PARTUUID=14420948-2cea-4de7-b042-40f67c618660 rw
........
Not exactly, but I hope it will be enough to describe the problem.
With the current kernel is not the problem.
If someone wants to install LTS, cnchi wrong to create a configuration directory (bad line break), and it does not boot.

### Additional Notes:

It should be easy to fix.

**Comment by karasu** [comment]
Which boot manager did you choose? Grub or systemd-boot ?
