### ISSUE TITLE
Installation hangs - Cnchi 0.14.95

### ISSUE THREAD

**Issue by satriani-vai** [Antergos/Cnchi#609]
### Problem:
Cnchi hangs

### Log Files
```
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/antergos/Downloads/Cnchi-master/cnchi/installation/process.py", line 93, in run
    self.create_metalinks_list()
  File "/home/antergos/Downloads/Cnchi-master/cnchi/installation/process.py", line 64, in create_metalinks_list
    self.pkg.create_package_list()
  File "/home/antergos/Downloads/Cnchi-master/cnchi/installation/select_packages.py", line 109, in create_package_list
    self.select_packages()
  File "/home/antergos/Downloads/Cnchi-master/cnchi/installation/select_packages.py", line 206, in select_packages
    xml_root = eTree.fromstring(packages_xml)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
```

**Comment by karasu** [comment]
My fault. I'll fix this asap

**Comment by lots0logs** [comment]
@karasu You sure? I think I was the last one to make changes to that part of the code :grimacing:

**Comment by karasu** [comment]
I edited packages.xml so I thought it was my fault. I'm not near a computer
atm to check it

El diumenge, 5 de juny de 2016, Dustin Falgout <notifications@github.com>
va escriure:

> @karasu <https://github.com/karasu> You sure? I think I was the last one
> to make changes to that part of the code 😬
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Antergos/Cnchi/issues/609#issuecomment-223803972>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAKutdPav2QQ6j3q2JpVthHNKmQYccqLks5qIqIpgaJpZM4IuT6B>
> .
>


-- 
Enviat amb el meu Iphone

**Comment by lots0logs** [comment]
Okay, I will take a look in a few minutes.

**Comment by karasu** [comment]
I think I fixed it. Please @satriani-vai , test it when you have the time.

@lots0logs I can't remember if we wanted to give priority to packages.xml from our server or from Cnchi itself.

**Comment by lots0logs** [comment]
@karasu Priority goes to the server copy. Local copy only used when we cant get it from server for whatever reason.

**Comment by karasu** [comment]
@lots0logs then I did it right. Thanks!

**Comment by satriani-vai** [comment]
I would like to test, but [this issue](https://github.com/Antergos/Cnchi/issues/595) prevents me :stuck_out_tongue_winking_eye:

**Comment by karasu** [comment]
issue #595 should be resolved. Needs testing, the same as this one :grimacing: 

ZFS+LUKS: We have not started on this, yet. I'm afraid there's no eta either, sorry.

**Comment by satriani-vai** [comment]
Everything works well :smiley:
