### ISSUE TITLE
NTP and MATE

### ISSUE THREAD

**Issue by prescott66** [Antergos/Cnchi#614]
MATE desktop has not integrated automatic time control, so i am wondering, if can be integrated and enabled NTP service as default.

**Comment by Mikaela** [comment]
IIRC MATE has it somewhere and I think Cnchi does it by itself.

To confirm you could paste the output of `timedatectl`. If it says `Network time on: no` or `NTP syncrhonized: no`, you can enable it with `sudo timedatectl set-ntp true`.

* * * * *

```
% LANG=C timedatectl
      Local time: Sun 2016-06-12 13:04:51 EEST
  Universal time: Sun 2016-06-12 10:04:51 UTC
        RTC time: Sun 2016-06-12 10:04:51
       Time zone: Europe/Helsinki (EEST, +0300)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```

**Comment by prescott66** [comment]
aha.i dont knew, there is an another solution :smile:
so, cnchi sets time from internet at the installation?

**Comment by karasu** [comment]
Yes, if you leave the selection on (it's on by default).

As @Mikaela says, it uses systemd-timesyncd (thanks again for your suggestion :grimacing: ).
