### ISSUE TITLE
Modifying Packages.xml

### ISSUE THREAD

**Issue by ThePreviousOne** [Antergos/Cnchi#632]
### Problem:
any changes I make to packages.xml are ignored during install

### Steps To Reproduce:
1. Edit data/packages.xml
2. Start cnchi & install antergos

**Comment by karasu** [comment]
Hi,

By default, Cnchi uses the packages.xml that is stored in the Antergos server. To change this behaiviour, use the -p parameter:

`sudo cnchi -dv -p /usr/share/cnchi/data/packages.xml`

Cheers!

**Comment by Wyn10** [comment]
The readme also shows how the -p parameter is used... https://github.com/Antergos/Cnchi/blob/master/README.md
