### ISSUE TITLE
Features :: Package Conflict Caused By One Or More Of Optional Features

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#633]
### Problem:
https://github.com/Antergos/Cnchi/issues/605#issuecomment-233841124

**Comment by karasu** [comment]
I'll do some tests right now

**Comment by GeoffreyVDB** [comment]
Seeing the same issue here, trying to install antergos with cinnamon using cnchi 0.14.113.
Optional features are chromium, google fonts, flash, aur, cups and bluetooth.
[cnchi.log](https://pastebin.com/3gsGwrAP)

**Comment by GeoffreyVDB** [comment]
This is the log without any optional features: [cnchi:log](https://pastebin.com/9n4u8PBB)

**Comment by karasu** [comment]
@GeoffreyVDB Thanks!

**Comment by JAAdrian** [comment]
Hey everyone,

as I am also affected by this: this is my [cnchi.log](pastebin.com/3KBpjYqp)
I unchecked all packages except for the printer support.
