### ISSUE TITLE
Cnchi keyboard

### ISSUE THREAD

**Issue by davidhijomaria** [Antergos/Cnchi#634]
### Problem:

_cnchi installation not install the la-latin1 keyboard_
### Steps To Reproduce:
1. Start the installing of antergos
2. When you need to choose the keyboard  select Spanish latin american...
3. When you open yor desktop and try to write "tildes" or "ñ", you have "{" and ":" respectively.  
### Log Files

-Don't know what file or line needs the correction.
### Additional Notes:

Thank's.

**Comment by davidhijomaria** [comment]
Hello!

I've reinstalled Antergos with care of selecting correctly the keymap (Spanish Latin American), in other pc (Hp Pavilion). I've proved it with cnchi tester.

When I have finished the keymap is English!!!!!!!!!!!!!!!

I can't write in Spanish!

**Comment by davidhijomaria** [comment]
Listing keymaps from terminal

[caduarte@Hplinux ~]$ localectl list-keymaps
ANSI-dvorak
amiga-de
amiga-us
applkey
atari-de
atari-se
atari-uk-falcon
atari-us
azerty
backspace
bashkir
be-latin1
bg-cp1251
bg-cp855
bg_bds-cp1251
bg_bds-utf8
bg_pho-cp1251
bg_pho-utf8
br-abnt
br-abnt2
br-latin1-abnt2
br-latin1-us
by

**Comment by davidhijomaria** [comment]
This answer works perfect, I can use "ñ"(without copy-paste), and á é í ó ú!, let's see: 

Re: Problema Teclado en Espa;ol Latino
Mensajepor Ouroboros » 13 Feb 2010, 03:20

joanzare escribió:
configuralo manualmente:

Abre una terminal y ejecuta el siguiente instruccion:

CÓDIGO: SELECCIONAR TODO
setxkbmap -layout latam


donde:
> setxkbmap: esel comando para cambiar el teclado
> -layout: es la opcion para cambiar el idioma
> latam: es el idioma a cambiar, o sea Español Latinoamericano :D.

puedes investigar como se ejecutan aplicaciones al inicio en openbox, y agregar la instrucción que te acabo de comentar,
para que no lo escribas diariamente, aunque pues no es mal repetirlo muchas veces el comando para que te lo aprendas.

Esto es valido para todos los entorno de escritorio como lxde, fluxbox, openbox, etc etc. 

Espero haberte ayudado :D.

Naguara gracias por la ayuda :D :D :D :D :D , andaba loco sin poder usar la ñ en el teclado, no tienes idea cuantas veces tuve que reiniciar probando un monton de cosas que no servian.

**Comment by davidhijomaria** [comment]
Esto funciona, pero al reiniciar no está cargado el teclado Español Lat, sino que debo reingresar desde consola:

setxkbmap -layout latam

Ayuda!

**Comment by karasu** [comment]
Which DE are you using? You have to setup your keyboard with it. In Gnome you'll find the keyboard layout settings in the region and languages setting panel. Go to the user menu, choose System Settings, then Region and Language, then switch to the Layouts tab.

**Comment by davidhijomaria** [comment]
Hello, Thank you very much!

With your instruccion: "In Gnome you'll find the keyboard layout settings in the region and languages setting panel. Go to the user menu, choose System Settings, then Region and Language, then switch to the Layouts tab."

Was more than perfect. 

Acabo de reiniciar mi sistema y vean: me cargó la los caracteres propios de mi teclado español-latinoamericano.

Estoy en Gnome, no en open box. ¡Gracias!

**Comment by kneipp** [comment]
Hi there! 
Fresh install here and i can confirm similar problem in gnome:

# Problem:
In brazilian Portuguese Cnchi is setting /etc/vconsole.conf KEYMAP with br but this entry doesn't exists.
```
cat /etc/vconsole.conf 
# File modified by Cnchi

KEYMAP=br
```


## Logs
`sudo systemctl`
● systemd-vconsole-setup.service                                                               loaded failed failed    Setup Virtual Console

`sudo systemctl status systemd-vconsole-setup.service`
set 09 14:23:27 PSArch systemd[1]: Starting Setup Virtual Console...
set 09 14:23:27 PSArch systemd-vconsole-setup[353]: cannot open file br
set 09 14:23:27 PSArch systemd[1]: systemd-vconsole-setup.service: Main process exited, code=exited, status=1/FAILURE
set 09 14:23:27 PSArch systemd[1]: Failed to start Setup Virtual Console.
set 09 14:23:27 PSArch systemd[1]: systemd-vconsole-setup.service: Unit entered failed state.
set 09 14:23:27 PSArch systemd[1]: systemd-vconsole-setup.service: Failed with result 'exit-code'.

## Solution
Change /etc/vconsole.conf entry to one of this:
br-abnt
br-abnt2 (most common)
br-latin1-abnt2
br-latin1-us

I'd like to make a PR but dont know how can start a hotfix
cnchi/modules/keymap.py is this guy?

**Comment by karasu** [comment]
@kneipp Let me check it and I'll get back to you asap... we're kinda busy lately with our jobs.

**Comment by stratus-ss** [comment]
@kneipp I believe you are looking for install.py, the relevent code is here I think

`    def set_vconsole_conf(self):
        """ Set vconsole.conf for console keymap """
        match = {
            "ca": "us",
            "gb": "uk",
            "latam": "la-latin1",
            "pt": "pt-latin1"
        }
        keyboard_layout = self.settings.get("keyboard_layout")
        keyboard_variant = self.settings.get("keyboard_variant")
        vconsole = match.get(keyboard_layout, keyboard_layout)
        # Write vconsole.conf
        vconsole_path = os.path.join(DEST_DIR, "etc/vconsole.conf")
        with open(vconsole_path, 'w') as vconsole_file:
            vconsole_file.write("# File modified by Cnchi\n\n")
            vconsole_file.write("KEYMAP={0}\n".format(vconsole))
        logging.debug("Set vconsole to %s", vconsole)
`

**Comment by stratus-ss** [comment]
Related to #648
