### ISSUE TITLE
Cnchi gets stuck at fetching last item

### ISSUE THREAD

**Issue by Akkowicz** [Antergos/Cnchi#637]
### Problem:
*Wanted to install Antergos today (English language, en-US locale, Polish keyboard layout, Cinnamon DE, latest Cnchi version), but installer is getting stuck at fetching last item, rebooted and tried 3 times with different optional packages, it's always the last one that gets stuck and it's completely random package. Also when it happens, the second progress bar disappears.*

### Steps To Reproduce:
1. Boot Antergos image
2. Select Cinnamon during installation 
3. Wait till the last item is being fetched

### Log Files
- [cnchi.log](http://paste2.org/4XCzd0Ls)
- [Screenshot](http://i.imgur.com/DUChJPX.png)

### Additional Notes:
Sorry if something is missing etc, it's my first issue, that I've submitted.
(Tried with XFCE now and same happened)

**Comment by lots0logs** [comment]
@Akkowicz There is no sign of the error that is causing Cnchi to hang in your log. Could you try starting it from the terminal and let me know if the error shows up in the output there? Use this command to run it in the terminal: `sudo -E cnchi -dv -s bugsnag`

@babarnescocke Could you post a link to your log here? Thanks!

**Comment by Akkowicz** [comment]
http://paste2.org/OUDchwIe
It starts installing and then fetching again? 

Also there is a [topic ](https://forum.antergos.com/topic/4818/cnchi-stalls-at-final-package-logs-debug-included)on antergos forum bout this issue:

**Comment by babarnescocke** [comment]
http://pastebin.com/N1k6m5AW

**Comment by Jebtrix** [comment]
Like the rest, any installation combination:
IndexError: list index out of range

I had some luck forcing cnchi to stay at ISO version 0.14.113, but not all window managers make it all the way.
