### ISSUE TITLE
v0.14.133 - New bug encountered, Error 217470: Setup cannot detect size of your device...

### ISSUE THREAD

**Issue by Jebtrix** [Antergos/Cnchi#638]
### Problem:
![screenshot from 2016-07-31 22-35-23](https://cloud.githubusercontent.com/assets/1848435/17282338/cc72bcd4-5772-11e6-9f0e-c2377087546e.png)

Just tried new 0.14.133 version in same empty vbox VM I was using to debug older cnchi version problems. Now I am getting error 217470: Setup cannot detect size of your device.....

### Steps To Reproduce:
1. New Virtualbox (v5.1.2) VM 8GB Ram, 50GB HD, everything else defaults, started from same empty snapshot
2. Cnchi 0.14.133 - All defaults, just next next next...
3. Bug not present with Cnchi v0.14.113, v0.14.130

### Log Files
- Link to /tmp/cnchi.log output.
http://pastebin.com/YHWyQWtq

**Comment by lots0logs** [comment]
@Jebtrix Has this same error occured more than once (across multiple boots)?

**Comment by Jebtrix** [comment]
Tried it 3 times from same snapshot. Just did 3 with reboots after failure, no snapshot restore, same result.

**Comment by Jebtrix** [comment]
Also tried blank drive, and one pre-partitioned from forcing 0.14.113 to not update. Both failed with same error.

**Comment by lots0logs** [comment]
I cannot reproduce the issue using Virtualbox VM. Could you tell me what reference number is shown in the failure error dialog (I can use it to access debugging details)? Thanks!

**Comment by Jebtrix** [comment]
217470

**Comment by Jebtrix** [comment]
Trying on my laptop quick, see how much Murphy's Law is in affect..

**Comment by Jebtrix** [comment]
Same problem on laptop. Same error message different code: 217577

**Comment by Jebtrix** [comment]
With laptop, I mean actual laptop, not VBox on laptop :smile:

**Comment by lots0logs** [comment]
Thanks..I had spoke too soon in my previous comment. I can reproduce it, I am doing some testing now to determine what's causing it. Thanks for your patience.

**Comment by Jebtrix** [comment]
No problem, I'm here to help. I'll be up for bit yet lurking

**Comment by Jebtrix** [comment]
I see a got a 2 for 1 bug smash :laughing: 

Python is next on my todo list. Im curious,  what was device_name = call(["basename", device]) variable being populated with? Empty string?

**Comment by lots0logs** [comment]
> Im curious, what was device_name = call(["basename", device]) variable being populated with? Empty string?

Actually, that's the weird part. The log output showed that the command was returning the expected value (which in this case was `sda`) but the check for the path's existence was still failing. I didnt dig into it much deeper because that code needed to be updated anyway (we must have missed it when we went through and removed all unnecessary uses of shell commands)
