### ISSUE TITLE
Error 217624 w/ base install and ZFS

### ISSUE THREAD

**Issue by babarnescocke** [Antergos/Cnchi#639]
### Problem:
*Replace this line with a brief summary of the problem.*
cnchi  pops up an error message and won't let me continue.

### Steps To Reproduce:
1. Cnchi with ZFS, base and AUR

### Log Files
- http://pastebin.com/1FsbzDFn

### Additional Notes:
'collections.OrderdDict' object has no attribute 'read_grp'
Please reference the following number when reporting this error: 217624

**Comment by lots0logs** [comment]
This was fixed in b25ce64e4492d8cef9b118112010f2c0234e3e57 The cnchi package will be updated here shortly.
