### ISSUE TITLE
Systemd-boot loader.conf should not be overwritten (or at least should have a timeout)

### ISSUE THREAD

**Issue by fpqc** [Antergos/Cnchi#640]
### Problem:

When antergos is installed or reinstalled, it writes a single line /boot/loader/loader.conf that just says 
`default antergos`
### Steps To Reproduce:
1. Reinstall antergos with systemd-boot as the bootloader
### Additional Notes:

This setting causes direct-boot into antergos, just like gummiboot, and disables the ability to select antergos-fallback or Windows (if installed).  Generally speaking, if someone already has systemd-boot installed, loader.conf should not be edited just to set their defaults, but if you absolutely must, you should at least add another line

`timeout 3` 

that sets a 3 second timeout on the bootmenu to allow people who multiboot, or who have driver problems, to get to their choice of OS or the antergos fallback image.

**Comment by chaos7theory** [comment]
I agree with this, as this also makes having the LTS kernel option useless without a timeout.

**Comment by SuperKingZ** [comment]
I can confirm the problem.  Without the "timeout 3" you don't have access to the boot loader menu for choosing what operating system to boot. 

After adding "timeout 3" the boot menu was available and could choose between Windows and Antergos
