### ISSUE TITLE
Unable to boot to install Antergos

### ISSUE THREAD

**Issue by USBA** [Antergos/Cnchi#647]
### Problem:
*Can't boot the ISO of antergos-2016.09.03 to install using an USB drive.*

This is the error massage :

`Waiting 30 seconds for device /dev/disk/by-lable/ ...`
`ERROR: ' /dev/disk/by-lable/' device did not show up after 30 seconds...`
`      Falling back to interactive prompt`
`      You can try to fix the problem manually, log out when you are finished`
`sh: can't access tty; job control turned off`
`[rootfs ]#`
  

Please help me.
Thanks.

**Comment by karasu** [comment]
Duplicated https://github.com/Antergos/antergos-iso/issues/67
Closing.
