### ISSUE TITLE
Cnchi sets KEYMAP in vconsole.conf to non-existing value "at"

### ISSUE THREAD

**Issue by puenka** [Antergos/Cnchi#648]
Following problem occured on my first install of antergos (arch newbie here):
I am from Austria and have hence installed antergos with the Austrian languague configuration.
From the first boot on, I got an error message, that systemd-vconsole-setup failed during the boot sequence:
`systemd-vconsole-setup[195]: /usr/bin/loadkeys failed with error code 1.` (amongst others)

After some research I came across a solution:
The file /etc/vconsole.conf contained only a comment stating that the file was modified by Cnchi and the entry `KEYMAP=at`.
Since `localectl list-keymaps` did not list an entry `at`, I decided to try the languagewise similar (if not identical) `de` keymap, which then seemed to work.

I do not know whether this also happens with other locales, which use a language that has its main speaking population in another country (as with more Germans speaking German than Austrians), but in my case this problem appeared, so it might be worth having a look at...

**Comment by stratus-ss** [comment]
@puenka What did you set your keyboard layout to?

The cnchi code uses the keyboard layout to set the vconsole values

**Comment by puenka** [comment]
Well, I did, indeed, set the keyboard layout to "Deutsch (Österreich)" (German (Austrian)), which would correctly correspond to de_AT, I think.

Still, I guess the KEYMAP setting should not be set to "at", if it doesn't actually exist.

**Comment by stratus-ss** [comment]
@puenka since I am not really familiar with the best match, do you have a suggestion for that? i can do a PR to match your keyboard layout with the best vconsole selection

**Comment by puenka** [comment]
As mentioned before, I would like to suggest linking it to "de", which to my knowledge should have the same keyboard layout as de_AT.

**Comment by karasu** [comment]
https://github.com/Antergos/Cnchi/commit/e49e60ff54cc79001defa6bbe97c640ee992c51e should fix this once and forever.
(Cnchi version 0.14.186)
