### ISSUE TITLE
Cnchi does not start and eats all memory up

### ISSUE THREAD

**Issue by pointhi** [Antergos/Cnchi#651]
### Problem:
* after starting Cnchi it eats up all memory (about 8GB) and no window appears

### Steps To Reproduce:
1. Start Cnchi
2. look onto the system-monitor
3. wait

### Fixes

downgrading to ```cnchi-0.14.178-1-any.pkg.tar.xz``` fixes the issue (installed was ```cnchi-0.14.180-1-any.pkg.tar.xz```

```
sudo pacman -U /var/cache/pacman/pkg/cnchi-0.14.178-1-any.pkg.tar.xz
sudo cnchi --disable-update
```

### Additional Notes:

related to: https://github.com/Antergos/antergos-iso/issues/70

**Comment by lots0logs** [comment]
Hi, with which ISO did the issue occur? Was it the latest testing image or the current released version on our website?
