### ISSUE TITLE
Installation error 281386: Unable to create the packages list to download (metalinks)

### ISSUE THREAD

**Issue by santagu** [Antergos/Cnchi#655]
### Problem:
I am trying to install antergos in the company where I work from live usb, but when I’m in the step of the introduce the user data, a error appears:
 Unable to create the packages list to download (metalinks). Provide error reference 281386 (or something like that, because the original message is in spanish and is: “No se puede crear la lista de paquetes a descargar (metalinks). Facilite esta referencia del error 281386”).

### Steps To Reproduce:
1. Run the installation live usb.
2. I follow all the installation steps, select to install the default software packages
3. After the installation summay step, introducing user data, the error appears

### Log Files
- Link to /tmp/cnchi.log output: http://paste2.org/svKz5kcX
- Link to /tmp/postinstall.log: it's empty
- Link to /tmp/pacman-boot.log: http://paste2.org/bppyhsfc

### Additional Notes:
I’ve updated the pacman databases from terminal with pacman all goes well but after this in the installation process the same error appears. (pacman -Syy)

The computer is a HP EliteDesk 800 G1 SFF and it’s connected by ethernet to internet.

Thanks very much

**Comment by lots0logs** [comment]
I think this is caused by some out of sync mirrors with GNOME 3.22 being moved into stable just yesterday. Could you try it again and let us know the result?

**Comment by santagu** [comment]
ok, thanks, i'm going to trying it again...

**Comment by santagu** [comment]
Solved!!! Thanks very much. I've installed all. Congratulations for this great distribution!!! Simple, fast. Thanks very much.
