### ISSUE TITLE
Can't install necessary packages (286857)

### ISSUE THREAD

**Issue by ositanachi** [Antergos/Cnchi#657]
Attempted to install Antergos XFCE but I am greeted with error message 286857 (cnchi version 0.14.187).

Log file for /tmp/cnchi.log: https://paste2.org/Z0Wx97Wh

**Comment by stratus-ss** [comment]
I believe this issue has also been corrected. This can happen when alpm has a problem compiling a list of packages appropriate for the install. I wasn't able to reproduce this
