### ISSUE TITLE
Cinchi gets caught in a loop when using some LVM partitioning schemes

### ISSUE THREAD

**Issue by jrboothe** [Antergos/Cnchi#66]
The installer fails when using a fairly basic LVM layout and trying to set mount points for the volumes. The layout I was using is the following

One VG (system) with a single physical partition (/dev/sda1).
Three LVs
/dev/system/root - 15G
/dev/system/swap - 256M
/dev/system/home - All remaining space except 15G kept as free extents for snapshotting

When setting the mount points all goes well until I try to proceed to the next step. A notification box pops up saying the home partition will be modified. Clicking on ok does nothing but pop up the same message and makes proceeding impossible. This happens regardless of whether the home partition is previously formatted or if format partition is selected in the partitioner tool.

**Comment by lots0logs** [comment]
@karasu This has been fixed, right?

**Comment by karasu** [comment]
I have not been able to reproduce it :disappointed: 
I'll try again asap.

**Comment by lots0logs** [comment]
Nah, don't worry about it. With no other reports since it was opened in 2013, I think its safe to say this is no longer an issue :bowtie:
