### ISSUE TITLE
Cnchi does not recognize network connection

### ISSUE THREAD

**Issue by qw3ry** [Antergos/Cnchi#661]
### Problem:
When I start cnchi on my machine (about 4 years old, desktop pc, wired network connection) it tells me that there is no network connection and i can't continue

### Steps To Reproduce:
1. start latest antergos minimal iso from usb stick
2. `sudo -E cnchi -dv`
3. choose language and click next
4. I think cnchi freezes at this point, i cannot go back to the language screen and i cannot use the x to close it anymore

### Log Files
I did not figure out how to put the logfiles online from the minimal iso - no web browser, I have no second USB Stick and it seems that I cannot access the files on the stick itself from another installation (The live-file system is probably packed somewhere, but i could not find it).
I can provide photos of the screen though:
![image](https://cloud.githubusercontent.com/assets/3729858/19382575/1378759c-9201-11e6-84ce-0af78bf2b557.png)

### Additional Notes:
I tried to track down the issue by myself:
- it seems the upstream of my connection is used constantly (the full bandwith available for me is used)
- in extra.py i found that cnchi is trying to connect to 3 http servers. I tried to ping those - 1 of them timed out. The other two do not seem to accept connections on port 80 - http://the-ip-of-the-server did return an error 404
- the other option in extra.py to check for a network connection did throw an exception when I re-programmed it (I later noticed that the exception is logged as well): `org.freedesktop.DBus.Error.InvalidArgs: No such property 'state'`
- if you have an idea how to get the log files here I can do so.

**Comment by qw3ry** [comment]
I _kind of_ fixed this by changing the argument `'state'` to `'State'` in `/usr/share/cnchi/cnchi/misc/extra.py`. Will open a PR in a few seconds.
The 404 and the timeout do both still happen, but I was able to install Antergos now.

**Comment by qw3ry** [comment]
I will not close this issue by myself in case anyone still wants to have a closer look at the 404 errs.

But the issue bothers me no more as cnchi uses the "workaround"-Network detection (at least in my fix) and I could successfully install Antergos, therefore whoever is responsible for this repo may close this as well.

**Comment by lots0logs** [comment]
Thanks for the PR. This was working previously so I'm guessing the property name must have changed to be capitalized recently? Could you modify your PR to use the new property only we fail to get it with the old one?

**Comment by karasu** [comment]
@lots0logs It's been a while that these "warnings" are being logged in bugsnag, but as they were not fatal I've ignored them. Thanks @qw3ry for fixing it 😬

**Comment by qw3ry** [comment]
@lots0logs sorry, I'm not that much of a python guru... I'm more familiar with the C/C++/Java side of things, so I guess it would be easier if you do that by yourself.
TBH I did not even noticed the problem by myself, @cmd-johnson gave me the hint

**Comment by lots0logs** [comment]
@karasu On second thought, I dont guess its necessary to maintain backwards compatibility..what do you think?

**Comment by karasu** [comment]
@lots0logs you're right, it is not. We can add the PR change "state" to "State" without any problems, as if it does not work we have the ping check (this should be tested, though, as I thought it was working).

**Comment by qw3ry** [comment]
If I'm not mistaken the ping check is the first test, and the NM-'State' already the fallback
