### ISSUE TITLE
F2FS crc32

### ISSUE THREAD

**Issue by ntfs1984** [Antergos/Cnchi#662]
Hello. Non critical bug, but...

If we choosed F2FS partition for installation, additional modules should be added into /etc/mkinitcpio.conf (and initrd should be rebuilt) :

MODULES="f2fs crc32 libcrc32c crc32c_generic crc32c-intel crc32-pclmul"

Without them, newly installed Antergos **will not mount root partition, and will not boot**.

**Comment by karasu** [comment]
https://github.com/Antergos/Cnchi/commit/e8b290b974e5c920aae51e5ba9bd0cf182a1f9f9
