### ISSUE TITLE
Cnchi is frozen

### ISSUE THREAD

**Issue by adoello** [Antergos/Cnchi#665]
### Problem:

_Cnchi frozen in the step ._
### Steps To Reproduce:
1. Open Cnchi with sudo cnchi //or// sudo -E cnchi -dvne
2. Select Next > Next until System Check. All items it's OK
3. Cnchi is closed
### Log Files
- /tmp/cnchi.log --> http://paste2.org/w8A54v30
### Additional Notes:

![captura de pantalla de 2016-10-31 00-37-22](https://cloud.githubusercontent.com/assets/3196299/19840961/3c7cc0d4-9f02-11e6-9b0a-f5efdf2eaa49.png)

**Comment by lots0logs** [comment]
Hi, could you check your ip address using [this tool](http://mxtoolbox.com/blacklists.aspx) and let me know if its on any blacklists? Thanks.

**Comment by adoello** [comment]
"We notice you are on a blacklist"
Any advice?

**Comment by lots0logs** [comment]
We'll have to update cnchi so that it can continue without getting in touch with our server. That's not a problem. Though you are likely to experience other issues on the web due to having a blacklisted ip address. If I were you I would contact my ISP and request a new IP address :neckbeard:

**Comment by adoello** [comment]
I contact to my ISP. Thanks to you first advice, I see more problems with my connection. 
I hope in the next hours, the problem have been fixed. 
Thanks you very much.
