### ISSUE TITLE
got Error: 337522

### ISSUE THREAD

**Issue by postadelmaga** [Antergos/Cnchi#670]
### Problem:
I have tried to install antergos on mibook, installation starts but it stuck on the end while say `Loading packages...` 
The Cnchi gives me this error 337522 'Can't install necessary packages. Cnchi can't continue.

### Log Files
- Link to [/tmp/cnchi.log](http://paste2.org/HVxZAV64) output.
- /tmp/postinstall.log is empty

**Comment by lots0logs** [comment]
Looks like a corrupt package download. A new ISO is currently building, it will include all the latest packages on it so you dont have to download them during the installation. I recommend giving it a try once its ready. You can check on the [build server](http://build.antergos.com/repo/browse/testing) for it in about an hour from now. Let us know how it goes :smiley:

**Comment by postadelmaga** [comment]
I just recreated the usb installer (with the same image) and I successfully completed the installation.
Probably the previous usb creation got some error. 

Sorry for the not useful bug report.
