### ISSUE TITLE
Replace yaourt/pamac with pacaur/pamac

### ISSUE THREAD

**Issue by fpqc** [Antergos/Cnchi#677]
Yaourt is widely distrusted because it fails many parsing and other tests.  Pacaur is considered to be much better and is similarly easy to use.  

There is a package up on the AUR https://aur.archlinux.org/packages/pamac-pacaur/ that reconfigures pamac to use pacaur as its AUR client instead of yaourt.  This might be a good change.  If users complain, you could replace /usr/bin/yaourt with a symlink to pacaur.

**Comment by Yoshi2889** [comment]
This issue is invalid now that pamac seems to handle building packages on its own.
