### ISSUE TITLE
dependencies should contain efibootmgr

### ISSUE THREAD

**Issue by yevmel** [Antergos/Cnchi#684]
### Problem:
step where cnchi tries to install grub fails with `efibootmgr not found`. 

### Steps To Reproduce:
1. pacman -S cnchi
2. run cnchi from command line (so you can see logs on stdout/stderr)
3. try to install antergos/arch to a external disk (at least in my case it was a external disk)
4. "install grub" step never finishes, you have to close cnchi.

### Log
[WARNING] run_cmd.py(116) call(): Error running ['grub-install', '--target=x86_64-efi', '--efi-directory=/install/boot/efi', '--bootloader-id=antergos_grub', '--boot-directory=/install/boot', '--recheck']: Installing for x86_64-efi platform. grub-install: error: efibootmgr: not found.

### Additional Notes:
i think `pacman -S cnchi` should have installed efibootmgr.

**Comment by stratus-ss** [comment]
I dont think that efibootmgr is a hard dep of cnchi as there are still a ton of legacy bios devices in the wild. It's probably more appropriate to make sure it is installed inside the the **grub2.py**, specifically under  **install_efi()** method
