### ISSUE TITLE
Hunspell Installed Without a Dictionary

### ISSUE THREAD

**Issue by slacka** [Antergos/Cnchi#686]
When Antergos is installed with LibreOffice, we install hunspell-en. However if it's not installed we still install hunspell, but not any dictionary. This causes apps like Words to report that the spelling is working  and checked but nothing is checked. 

Cnchi asks for the language information. Could this be used to install the associated dictionary? For example if English was selected, then install 'hunspell-en'. This would save users some hassle troubleshooting and make a more polished install. 

Here is the full list of [available languages in Extra](https://www.archlinux.org/packages/?sort=&q=hunspell-&maintainer=&flagged=) and here is [a list of community](https://www.archlinux.org/packages/?sort=&repo=Community&q=hunspell-&maintainer=&flagged=) and [finally AUR](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=hunspell-&outdated=&SB=n&SO=a&PP=250&do_Search=Go).

If we're going to install hunspell by default, at a minimum, it would be good to bundle it with the most common languages like:

"hunspell-en" - English 
"hunspell-es" - Spanish
"hunspell-de" - German
"hunspell-fr" - French
"hunspell-ru" - Russian

**Comment by slacka** [comment]
It seems we don't do any language detection and everyone gets `hunspell-en` if they [select the office package](https://github.com/Antergos/Cnchi/blob/master/data/packages.xml). Would you accept moving this out and into the `locale_fonts` section? 

Something along the lines of:
```
<fonts lang="en">
			<pkgname>hunspell-en</pkgname>
</fonts>
<fonts lang="es">
			<pkgname>hunspell-es</pkgname>
</fonts>
...
```

**Comment by karasu** [comment]
Thanks! Done in f274de8ca39f568158e3f28b562bfb08d5304491
