### ISSUE TITLE
XFCE - remove xscreensaver from packages.xml

### ISSUE THREAD

**Issue by spinktvis** [Antergos/Cnchi#689]
Hi, first off my compliments to the team, it's been a pleasure working with Antergos these past couple of weeks. First tested a Gnome install with the 20-11-2016 ISO stable, and now I've switched to XFCE with a test build ISO 03-01-2017. Both the installs went without a hitch (although my gufw firewall was lacking any rules with my Gnome install, sorry didn't save the logs).

Now that I'm on XFCE I noticed that both xscreensaver and light-locker are installed by default. Please remove the xscreensaver from the package list as it's been made redundant by light-locker.

**Comment by karasu** [comment]
Thanks! Done in f274de8ca39f568158e3f28b562bfb08d5304491
