### ISSUE TITLE
Change lightdm-webkit2-greeter, please

### ISSUE THREAD

**Issue by Noxbru** [Antergos/Cnchi#693]
As seems to be typical... webkit2gtk breaks things... again...
https://bugs.archlinux.org/task/52615
And there's been at least 4 people with issues in the IRC channel. Surely more to come, and even more that we don't know about.

Proposal:
- Change lightdm-webkit2-greeter with something that is more stable.

Given the machinery that is already in cnchi I guess that you could even install a greeter per DE.

**Comment by Yoshi2889** [comment]
4 people is an understatement. The past few days about 90% of support requests have been about black screens with cursors.

**Comment by terriblespider** [comment]
Has been fixed since yesterday so I think there shouldn't be any problems now.

**Comment by Noxbru** [comment]
@terriblespider even though that is true, lightdm-webkit2-greeter has a tendency to break. So the question is 'for how long are we free of problems?'

Note: I use gdm, so I don't mind what happens, but it's sad to see that from time to time users have problems and it is due to this package.

**Comment by terriblespider** [comment]
If there's a better alternative for lightdm-webkit2-greeter I wouldn't say no ;)

**Comment by Noxbru** [comment]
@terriblespider there are alternatives. As I said, I use gdm, others use sddm... The problem is that the devs would have to maintain a theme for each one. But I think that this should be at least explored because it is a problem that with certain frequency lightdm-webkit2-greeter breaks.

**Comment by lots0logs** [comment]
This is not something we would even consider at this time. You have to understand that we've put a ton of effort into the development of our greeter. Is it perfect? Absolutely not. However, the issues that have come up are certainly not frequent. It's not like it breaks every other week or even every other month. Sadly the issues that have come up have been out of our control (upstream issues). With that in mind we are currently working on moving to QtWebEngine as the backend (which is based on Chromium). Our hope is that QtWebEngine will prove to be more stable than WebKitGTK has been.
