### ISSUE TITLE
cdrkit has been replaced by cdrtools

### ISSUE THREAD

**Issue by Noxbru** [Antergos/Cnchi#695]
Arch has removed the package cdrkit and it has been replaced by cdrtools. So every installation that tries to download that package will fail when creating metalinks (gnome, cinnamon, xfce, mate and openbox are affected).

Proposed fix:
Change all the instances of 'cdrkit' in packages.xml with 'cdrtools'.

**Comment by philwyettreb** [comment]
Pull request for this is at:

https://github.com/Antergos/Cnchi/pull/696
