### ISSUE TITLE
Cannot create download package list (metalinks) - again

### ISSUE THREAD

**Issue by taiki3ro** [Antergos/Cnchi#697]
### Problem:
*Replace this line with a brief summary of the problem.*

### Steps To Reproduce:
1. Selected Cinnamon DE
2. Chose only the AUR ( tried with no selection as well )
3. Erase disk and auto-partition with /home in a different partition
4. At the user and passwd step if gives error 432562 ( I have time to set them up but even if I do save or just wait it gives the error )

### Log Files
- Link to /tmp/cnchi.log output.
http://paste2.org/vVayg0En
- Link to /tmp/postinstall.log.
File is empty

**Comment by lots0logs** [comment]
The issue was caused by a package name change in the Arch repos. Try again in about an hour or so. Cheers!

**Comment by taiki3ro** [comment]
I will. Thanks
