### ISSUE TITLE
Cannot create Download list(metalinks)

### ISSUE THREAD

**Issue by jmaris** [Antergos/Cnchi#698]
### Problem:
The Installer does not complete successfully

### Steps To Reproduce:
1. Run the Installer
2. Select AUR, Firefox, Printing Support, Gnome
3. Continue with Setup

Appears not to be able to find gstreamer : 

`Can't find these packages: gstreamer0.10-plugins `
### Log Files
- Link to /tmp/cnchi.log output. : http://paste2.org/g34GZV3d
- Link to /tmp/postinstall.log. => empty

**Comment by karasu** [comment]
Thanks for reporting it! Fixed.

Please, wait a few hours before retrying.

**Comment by ramirio** [comment]
Apparently, the package was removed from arch repostory.
[https://www.archlinux.org/todo/phasing-out-gstreamer010/](https://www.archlinux.org/todo/phasing-out-gstreamer010/)

**Comment by karasu** [comment]
Thanks again!

**Comment by jmaris** [comment]
Thank you for your hard work !
