### ISSUE TITLE
Stuck at "Getting package list..."

### ISSUE THREAD

**Issue by marconi** [Antergos/Cnchi#702]
### Problem:
Can't continue installation, stuck at "Getting package list...".

### Steps To Reproduce:
1. Download and boot from ISO https://mirror.freedif.org/Antergos/iso/release/antergos-17.1-x86_64.iso
2. Follow installation wizard
3. Get stuck at "Getting package list..." after following all the steps

### Additional Notes:
I don't have any logs because I encountered this as I was installing this system I'm currently using.

Basically for some of us with dynamic IPs, Cloudflare will throw in captcha challenge from time to time and when it happens, the installer won't be able to fetch the package xml which on my case was `http://install.antergos.com/package-14.xml`. Instead it'll download the Cloudflare challenge page and of course that's not the intended xml so the xml parser will break.

To continue my installation, I had to manually download the xml and bypass [this condition](https://github.com/Antergos/Cnchi/blob/master/cnchi/installation/select_packages.py#L220) so it'll always read from a local file I've downloaded.

### Possible solution
For dependency files, consider direct access to them as opposed to via Cloudflare.

**Comment by karasu** [comment]
@lots0logs ?

**Comment by marconi** [comment]
Yay! thanks :tada:
