### ISSUE TITLE
CPU microcode

### ISSUE THREAD

**Issue by archusr** [Antergos/Cnchi#704]
Should `extra/intel-ucode` be installed (and configured in the boot loader) on Intel machines?

**Comment by stratus-ss** [comment]
I think this is a good idea. I'll mark this thread

**Comment by karasu** [comment]
I thought we already did this... I'll check it out.

**Comment by lots0logs** [comment]
We are already doing this..actually there is no special configuration needed other than installing the `intel-ucode` package.

**Comment by archusr** [comment]
Ok, thanks. It did not automatically get installled/configured on my X220, though.

**Comment by lots0logs** [comment]
Actually looks like we need to check into it further...

**Comment by Yoshi2889** [comment]
It requires a new initrd entry for systemd-boot. GRUB should detect it automatically.

Adding it after line 104 here would be fine:
https://github.com/Antergos/Cnchi/blob/0b03d460fc4a9ab7f2cf1527dc89426b66dc4424/cnchi/installation/boot/systemd_boot.py#L104

**Comment by karasu** [comment]
>Also note this is only applicable to Intel processors. AMD already has their microcode in linux-firmware and the kernel loads it automatically.

Does this mean we can't add it in AMD processors, so we must check if an intel cpu or an amd one is used?

**Comment by Yoshi2889** [comment]
AMD is handled automatically, I think adding Intel microcode for all
processors won't hurt though (it checks if the microcode has to be updated
for the processor model).

**Comment by karasu** [comment]
Thanks @Yoshi2889 !
