### ISSUE TITLE
Cnchi sets time to GMT in Plasma5 but I selected GMT+1

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#707]
### Problem:
Time is wrong (it's GMT in Plasma, but it should be GMT+1)

### Steps To Reproduce:
1. Select GMT+1 and automatic ntp
2. Install Plasma5
3. Open preferences, time is GMT instead of GMT+1

**Comment by Yoshi2889** [comment]
Can confirm this, while selecting Xfce as DE.

**Comment by karasu** [comment]
I think I fixed this, but it hasn't been released yet. /etc/localtime wasn't updated. Hopefully it will make April's iso.

**Comment by karasu** [comment]
You need 0.14.263+
Here's the fix: https://github.com/Antergos/Cnchi/commit/e4da9b7d315f5ca498e77fc3b1554960d4631c92
