### ISSUE TITLE
The latest cnchi seems disable zfs option by default

### ISSUE THREAD

**Issue by netroby** [Antergos/Cnchi#708]
I am play antergos live media inside vmware + efi boot. 
I want to install antergos on my vmware box. but i can not see the zfs option enabled. it was disabled by default.

**Comment by karasu** [comment]
Yes, we're in the process of fixing the spl/zfs hook bug (in fact, we managed to write a workaround that  only needs to be fully tested). Meanwhile we have disabled the zfs option to avoid users facing this bug. Sorry. When it is tested we will activate the option again.
