### ISSUE TITLE
Do not set $BROWSER if none would be installed

### ISSUE THREAD

**Issue by Noxbru** [Antergos/Cnchi#712]
Cnchi adds code to /etc/profile that sets $BROWSER to chromium, even if it will not be installed.

Solution: Do not add that code.

**Comment by karasu** [comment]
https://github.com/Antergos/Cnchi/commit/61b473949de0c426455ef3022cd8e6f75ba15dbc

I'll leave this open until a second pair of eyes have a look at my changes.

**Comment by Noxbru** [comment]
I'm going to ask for something that is related to this:

Is there a list somewhere of all the changes/modifications that Cnchi makes after the installation, or should I just read the 'post install' script?

**Comment by Noxbru** [comment]
Humble ping?

**Comment by karasu** [comment]
hahaha... sorry! I readed this and forgot to answer 😬 

Well, there is no "offical" list. You should look not only the postinstall script as you have guessed, but also configure_system() function in https://github.com/Antergos/Cnchi/blob/0.14.x/cnchi/installation/install.py

**Comment by karasu** [comment]
Oh, and I'll close this as it's already done.
