### ISSUE TITLE
libgnome-keyring missing in fresh GNOME install

### ISSUE THREAD

**Issue by amilopowers** [Antergos/Cnchi#713]
libgnome-keyring missing in fresh GNOME install

1. I installed Antergos with GNOME.
2. I installed owncloud-client
3. I entered my Owncloud password and expected it to be saved in the Seahorse 3.20.0 keychain.
4. After every reboot I had to re-enter the Owncloud password. OC said that there was no keychain available in the system. 
5. I installed `libgnome-keyring` and OC doesn't ask for a password anymore.

Proposed fix: Add "libgnome-keyring" to default install.

I found the fix here: https://github.com/owncloud/client/issues/3726
@tvannahl gave the hint.

**Comment by karasu** [comment]
https://github.com/Antergos/Cnchi/commit/373d978ce7cd8d2698f08f8c704d854e6c25ea3f
Thanks!
