### ISSUE TITLE
Cannot install pip install failed

### ISSUE THREAD

**Issue by Thamaraiselvam** [Antergos/Cnchi#715]
After downloaded i cannot install requirements

```
pip install -r requirements.txt 
Collecting bugsnag (from -r requirements.txt (line 1))
  Using cached bugsnag-3.1.0-py2-none-any.whl
Collecting jinja2 (from -r requirements.txt (line 2))
  Using cached Jinja2-2.9.5-py2.py3-none-any.whl
Collecting pyalpm>=0.7 (from -r requirements.txt (line 3))
  Could not find a version that satisfies the requirement pyalpm>=0.7 (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for pyalpm>=0.7 (from -r requirements.txt (line 3))

```

Also cannot run it 

`root@tom:/usr/share/cnchi# ./run 
Traceback (most recent call last):
  File "/usr/share/cnchi/cnchi/cnchi.py", line 31, in <module>
    from _initial_imports import *
  File "/usr/share/cnchi/cnchi/_initial_imports.py", line 16, in <module>
    from whither.app import App
ImportError: No module named whither.app
cat: /tmp/cnchi.pid: No such file or directory`

**Comment by karasu** [comment]
Hi,
Use 0.14.x branch if you want to run it from git
These are the packages you need to install (use pacman not pip):
```
python pyalpm python-gobject python-dbus python-requests python-cairo
python-parted webkitgtk upower python-mako iso-codes encfs pam_encfs gptfdisk upower
```

**Comment by stratus-ss** [comment]
This bug has been answered and the OP has not responded in a month. I am closing this, it can be reopened if required
