### ISSUE TITLE
Cannot create donwload package list (metalinks) >lib32-mesa-libgl

### ISSUE THREAD

**Issue by killajoe** [Antergos/Cnchi#718]
### Problem:
I am not able to install antergos on my laptop, using live usb, when trying install error: cannot create donwload package list (metalinks) appears.
In cnchi log file i see: Can’t find these packages: lib32-mesa-libgl.
I tried to update mirror lists and running sudo -E cnchi -dv --disable-rank-mirrors, but same error appears

Copy from here: https://forum.antergos.com/topic/6342/cannot-create-donwload-package-list-metalinks/8

### Steps To Reproduce:
1. try to do a install with latest ISO 17.3 
2. nothing special chossing, Gnome or KDE same issue
3.Installation failed

Package lib32-mesa-libgl has namechange to lib32-mesa i think...

### Log Files
will follow...
- Link to /tmp/cnchi.log : http://pastebin.com/1YGsGSyk
- Link to /tmp/postinstall.log :

**Comment by Noxbru** [comment]
Okay, possible fix for now based on one succesfull installation in IRC:

Steps:
1. Start your liveUSB and let cnchi update.
2. Wait for it to start again, close cnchi.
3. Go to /usr/share/cnchi/cnchi/hardware/modules (or something similar)
4. Edit i915.py or nouveau.py or radeon.py, or something.py (depends on your graphics card)
5. Look for a like with the text "lib32-mesa-libgl" and remove that (the string inside the list, not the line)
6. Save the file and close it
7. Launch cnchi and it should work

**Comment by karasu** [comment]
Fixed by https://github.com/Antergos/Cnchi/commit/4449ddcda72e485b1a5d5f1343c45fe90be9cb24

Closing!
