### ISSUE TITLE
LogWARNING: Can't find service smbd

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#720]
## Error in Cnchi

**LogWARNING** in **installation/install.py:780**
Can't find service smbd

[View on Bugsnag](https://app.bugsnag.com/antergos/cnchi/errors/58765f70a6d6b708d8ffd5d7?event_id=58cb4e8469cc4c11004b8e7a)

## Stacktrace

    installation/install.py:780 - enable_services
    installation/install.py:895 - setup_features
    installation/install.py:1381 - configure_system
    installation/install.py:316 - start
    misc/extra.py:191 - helper
    installation/advanced.py:2398 - run_install
    installation/process.py:107 - run
    summary.py:196 - store_values
    main_window.py:430 - on_forward_button_clicked
    cnchi.py:536 - <module>

[View full stacktrace](https://app.bugsnag.com/antergos/cnchi/errors/58765f70a6d6b708d8ffd5d7?event_id=58cb4e8469cc4c11004b8e7a)

**Comment by karasu** [comment]
smbd never was needed because we're not installing samba server... my bad.
