### ISSUE TITLE
Cannot create download package list (metalinks). Error: 518345

### ISSUE THREAD

**Issue by mhingston** [Antergos/Cnchi#721]
### Problem:
Cannot create download package list (metalinks). Error: 518345

### Steps To Reproduce:
1. Following the installer wizard, get to the create user screen

### Log Files
[/tmp/cnchi.log](http://pastebin.com/1eUEXagR)

### Additional Notes:

Seems to be relating to `lib32-mesa-libgl`

    2017-03-18 09:45:57 [ERROR] metalink.py(124) create(): Can't find these packages: lib32-mesa-libgl
    2017-03-18 09:45:57 [ERROR] download.py(145) create_metalinks_list(): Error creating metalink for package lib32-mesa-libgl. Installation will stop`

**Comment by karasu** [comment]
You're using and old version of Cnchi. When you run the iso, wait a bit until Cnchi updates itself.

Latest version is 0.14.256

**Comment by mhingston** [comment]
Thanks, there seem to be issues updating...

[antergos@ant-17.3 ~]$ sudo pacman -Sy cnchi
error: could not register 'multilib' database (database already registered)
:: Synchronizing package databases...
 antergos is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
resolving dependencies...
looking for conflicting packages...

Packages (1) cnchi-0.14.256-1

Total Download Size:    4.25 MiB
Total Installed Size:  10.24 MiB
Net Upgrade Size:      -0.02 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from repo.antergos.info : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from mirrors.antergos.com : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from sourceforge.net : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from wynsrv.antergos.info : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from mirrors.ustc.edu.cn : The requested URL returned error: 404
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from mirrors.tuna.tsinghua.edu.cn : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from mirror.bjtu.edu.cn : The requested URL returned error: 404
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from mirrors.nic.cz : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from mirrors.dotsrc.org : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from cinnarch.polymorf.fr : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from eu.mirrors.coltondrg.com : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from www.mirrorservice.org : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from mirror.de.leaseweb.net : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from ftp.cc.uoc.gr : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from mirror.nl.leaseweb.net : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from ftp1.nluug.nl : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from ftp2.nluug.nl : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from mirror.yandex.ru : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from softlibre.unizar.es : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from mirrors.tuxns.net : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from mirror.us.leaseweb.net : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from mirror.umd.edu : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from mirrors.acm.wpi.edu : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from antergos.x86innovations.com : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from repo.antergos.info : Maximum file size exceeded
error: failed retrieving file 'cnchi-0.14.256-1-any.pkg.tar.xz' from mirror.freedif.org : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.

**Comment by mhingston** [comment]
I was able to update cnchi by downloading the package manually from one of the mirrors and installing it with pacman. After updating the install completes successfully.
