### ISSUE TITLE
Timezone is not correctly set up in a VirtualBox VM.

### ISSUE THREAD

**Issue by FredBezies** [Antergos/Cnchi#724]
### Problem:
I used antergos 2017.03 minimal ISO. I noticed that cnchi found the correct timezone, but it did not generate a correct link.

I had to modify in a terminal /etc/timezone symbolic link to make it point to the right timezone. It was set to UTC instead of Europe/Paris (in my case).

### Steps To Reproduce:
1. Grab 2017.03 minimal ISO
2. Launch it in VirtualBox
3. Choose another timezone than UTC / or found by cnchi to be the right one.
4. Wait until installation is finished
5. Reboot and look at time shown in lightdm...

### Log Files
None.

### Additional Notes:
I tried with Mate-Desktop to reproduce this bug.

**Comment by karasu** [comment]
@FredBezies Yep, I've checked and you're right. Thanks for reporting it.

**Comment by FredBezies** [comment]
You're welcome :)

**Comment by Yoshi2889** [comment]
Does this only happen in VirtualBox or also in other systems and hypervisors?

**Comment by FredBezies** [comment]
Did not try in Qemu. Will try do to this asap this weekend.

**Comment by karasu** [comment]
Hi!

This has already been fixed in Cnchi 0.14.263

See here: https://github.com/Antergos/Cnchi/commit/e4da9b7d315f5ca498e77fc3b1554960d4631c92

If you guys are so kind and want to test it, use at least this version.

Closing it for now.

**Comment by FredBezies** [comment]
Thanks !
