### ISSUE TITLE
 The features screen is really full as it is now. Any ideas how to redesign it?

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#73]
The features screen is really full as it is now. Any ideas how to redesign it?

**Comment by Yoshi2889** [comment]
Would it be possible to divide the options in categories?

So you would have for instance a page "Additional applications" with stuff like Firefox et al, "Drivers" with Bluetooth, CUPS, NVIDIA proprietary etc, "System Tools" with AUR.

This would also allow adding more options, while having less clutter.
