### ISSUE TITLE
NVIDIA Fallback on ISO is failing

### ISSUE THREAD

**Issue by ccavanaugh** [Antergos/Cnchi#733]
I tried to install using antergos-17.4-x86_64.iso.  The video card in the system is an Nvidia GTX 1060.

When trying to boot with the NVIDIA Fallback option thinking it would help with a missing cursor issue, I get the boot error below.

```
Error loading \EFI\archiso\vmlinuz: Not Found
Failed to execute Antergos.x86_64 (NVIDIA Fallback) (\EFI\archiso\vmlinuz): Not Found
```

**Comment by Jbonnett** [comment]
I can also confirm this, on 17.6

**Comment by lots0logs** [comment]
Issue moved to [Antergos/antergos-iso #89](https://github.com/Antergos/antergos-iso/issues/89) via [**ZenHub**](https://www.zenhub.com/)
