### ISSUE TITLE
Error 525700

### ISSUE THREAD

**Issue by jkw** [Antergos/Cnchi#739]
### Problem:
Installer throwing error after a while of downloading / installing files

### Steps To Reproduce:
1. Install making partitions etc
2. Install boot loader to wrong MBR
3. Install again by only pointing to partitions created earlier.

### Log Files
- /tmp/cnchi.log - https://paste2.org/aODUpdOU
- /tmp/postinstall.log - empty.

### Additional Notes:
None.

**Comment by karasu** [comment]
Hi,

Logs show a problem with `grub2-theme-antergos`. I'd guess that you already had those those files in your disk from the previous install.

When you select your partitions created earlier (step 3) you have to click on the format check box if they have a "dirty" installation.
