### ISSUE TITLE
Cannot create download package list (metalinks).

### ISSUE THREAD

**Issue by chengyi** [Antergos/Cnchi#744]
### Problem:
Cannot create download package list (metalinks).

### Steps To Reproduce:
1. choose desktop cinnamon

### Log Files
- https://paste2.org/PAMmOeBN

**Comment by adoussot** [comment]
Same error here with desktop environment: xfce. 

- [log File](https://paste2.org/JfG40tj7)
- The cnchi installer quit and can't be reopen until reboot

**Comment by Jebtrix** [comment]
Just a fyi, If Cnchi updates itself, and it errors out or you close it. You have to launch it from the terminal afterwards. No reboot required. That's a separate bug already in issues.

**Comment by bryce-lynch** [comment]
Same error here with xfce. The reported error number is 0. The cnchi.log complained it couldn't create metalinks for an xorg- package, can't remember the name though.
