### ISSUE TITLE
Cnchi fails trying to install any DE

### ISSUE THREAD

**Issue by Jebtrix** [Antergos/Cnchi#745]
### Problem:
Cnchi fails to install ANY desktop environment, only Base will install

### Steps To Reproduce:
1. Just try to install with any DE

### Log Files
2017-05-07 01:59:24 [ERROR] metalink.py(124) create(): Can't find these packages: xorg-server-utils 
2017-05-07 01:59:24 [ERROR] download.py(145) create_metalinks_list(): Error creating metalink for package xorg-server-utils. Installation will stop
2017-05-07 01:59:24 [ERROR] download.py(177) create_metalinks_list(): Can't create download set. An exception of type InstallError occured. Arguments:
('Error creating metalink for package xorg-server-utils. Installation will stop',)
2017-05-07 01:59:24 [ERROR] process.py(128) run(): 'Cannot create download package list (metalinks).'

### Additional Notes:
Any DE will fails with "Can't find these packages: xorg-server-utils "
Tried on bare metal, vmware workstation, and virtual box just to be thorough
Confirmed by another on #Antergos IRC

**Comment by Jebtrix** [comment]
Apparently xorg-server-utils removed from arch
https://bbs.archlinux.org/viewtopic.php?id=225932

**Comment by leanvix** [comment]
I think I've found a workaround (it passes the building of packages list and fetches all packages at least, still installing to verify).
1. Wait for cnchi to update, then close cnchi
2. Open terminal
3. Grab the packages.xml from https://raw.githubusercontent.com/Antergos/Cnchi/master/data/packages.xml
4. Remove the line <pkgname>xorg-server-utils</pkgname>
5. Add the following lines (the dependencies from the 7.6-4 xorg-server-utils pkgbuild I found in my cache on another install):
<pkgname>xorg-iceauth</pkgname>
<pkgname>xorg-sessreg</pkgname>
<pkgname>xorg-xcmsdb</pkgname>
<pkgname>xorg-xbacklight</pkgname>
<pkgname>xorg-xgamma</pkgname>
<pkgname>xorg-xhost</pkgname>
<pkgname>xorg-xinput</pkgname>
<pkgname>xorg-xmodmap</pkgname>
<pkgname>xorg-xrandr</pkgname>
<pkgname>xorg-xrdb</pkgname>
<pkgname>xorg-xrefresh</pkgname>
<pkgname>xorg-xset</pkgname>
<pkgname>xorg-xsetroot</pkgname>
6. start cnchi again with sudo -E cnchi -dv -p packages.xml

Install should continue as expected.

**Comment by Jebtrix** [comment]
Created a pull request with the change. Thanks for helping leanvix on #Antergos IRC!

**Comment by Tiedemanns** [comment]
All the packages mentioned are in the "xorg-apps", so unless I'm missing something I don't think there's any point in adding them to the file. Only removing the "xorg-server-utils" works here.

**Comment by InterGenStudios** [comment]
ditto: just dropping xorg-server-utils allows it to install w/out any further issues.

**Comment by piter2268** [comment]
I think that xorg-server-utils should be replaced with xorg-apps. This is what most of arch installers do now.

**Comment by karasu** [comment]
@piter2268 We were already installing `xorg-apps`. Thanks for the recommendation, though.

Cheers!

**Comment by triinoxys** [comment]
For people stil having trouble, please refer to this: https://github.com/Antergos/Cnchi/issues/845#issuecomment-374779410
