### ISSUE TITLE
Cannot create download package list (metalinks).

### ISSUE THREAD

**Issue by jeantonalli** [Antergos/Cnchi#749]
### Problem:
I tried to install antergos, and in the last step it tells "Cannot create download package list (metalinks)." So, the installation stops.
### Steps To Reproduce:
Choose Gnome desktop
No matter if i don't chose any package, it still stops
### Log Files
https://paste2.org/cmEEOptB

**Comment by bryce-lynch** [comment]
related to https://github.com/Antergos/Cnchi/issues/744

**Comment by karasu** [comment]
https://github.com/Antergos/Cnchi/commit/f6f4ef5e8dd616b022dbdead4b4e1af1c0471678 fixes it.
