### ISSUE TITLE
Cannot create download package list (metalinks). Error: 603053.

### ISSUE THREAD

**Issue by karambaq** [Antergos/Cnchi#751]
The problem looks exactly like #745. But fix from that topic doesn't solve it. 

- Link to /tmp/cnchi.log output.
https://paste2.org/JHe5tV46

UPD:
Can't find these packages: antergos-gsettings

**Comment by karasu** [comment]
`antergos-gsettings` is a new package. I should have wait a little so all mirrors got updated.

It should work by now. Tell us if it still doesn't.
