### ISSUE TITLE
Add ssh support as an option in the installer

### ISSUE THREAD

**Issue by Noxbru** [Antergos/Cnchi#756]
Hi, would it be possible to add (and enable) ssh support by some kind of option in the installer? In some cases of login problems (or, as we have found today in IRC, a keyboard not working) it would be very useful to connect to the machine having problems from outside and check it's logs and packages and all.

Thanks in advance!

**Comment by karasu** [comment]
That's a really nice idea and fairly easy to do. Consider it done.

**Comment by karasu** [comment]
https://github.com/Antergos/Cnchi/commit/cdb19434094ab7a4f9789803db54542ca8e58692

Haven't got time to test it, though.
