### ISSUE TITLE
Install TLP by default

### ISSUE THREAD

**Issue by tenten8401** [Antergos/Cnchi#759]
As the title says, I think Antergos should have TLP installed & configured by default, because installing this on a laptop reduces battery life quite a bit from what a windows/configured tlp install would provide

**Comment by stratus-ss** [comment]
Marking this as an enhancement. I agree with this as long as there is a way to detect laptops in a reliable fashion. Installing extra packages on a desktop is less desirable given the nature of Arch

**Comment by ZimbiX** [comment]
You could just detect the presence of a battery?

**Comment by stratus-ss** [comment]
Not really, I mean for that could work but you are going to hit edge cases, if you are like me, you have a UPS for your desktop due to brown outs in your area. I have 4 UPS' within 15 feet of my desk.

**Comment by tenten8401** [comment]
Even if we don't have a battery in the device, it's always good to have it installed for power savings. Manjaro installs it even if it's a desktop or a laptop.
