### ISSUE TITLE
"Impossible d'installer les paquets nécessaire. Cnchi ne peut pas continuer." ref:640219

### ISSUE THREAD

**Issue by TitouanT** [Antergos/Cnchi#760]
### Problem:
Sorry for the title in french but I tried the installation in french.
The installation was almost done (like really really close), and then I got this message (in the title).

### Steps To Reproduce:
1. downloaded the iso from the antergos website (on which I can't log in by the way).
2. make a bootable usb with rufus.
3. followed these two tutorials:
+ https://antergos.com/wiki/install/how-to-dual-boot-antergos-windows-uefi-expanded-by-linuxhat/
+ https://antergos.com/wiki/hardware/graphics/bumblebee-for-nvidia-optimus/
4. and I think additional checked packages were: firefox, flashplayer, AUR, things with printer, and maybe another one but I don't think the issue comes from there any way.
5. I am trying to do a dual boot with windows.

### Log Files
- Link to /tmp/cnchi.log: https://paste2.org/m7sNjNJM.
- Link to /tmp/postinstall.log: I didn't find this file.

Additionnal Links:
- /tmp/cnchi-alpm.log: https://paste2.org/V81Uptbb (just the end of the file because it was too big)

### Additional Notes:
It seems to me that the install failed because of non matching sha256sum of the package openssh7.5.

**Comment by TitouanT** [comment]
I also checked the gnome environnement if that's any help.

**Comment by karasu** [comment]
At first, you didn't have network connection:
```
2017-06-07 23:46:00 [WARNING] extra.py(429) has_connection(): <urlopen error [Errno 101] Network is unreachable>
```
I'd close cnchi first, then check I have a working connection and then start cnchi again.

We just released a new ISO, could you try it again with this new one? Thanks!

**Comment by TitouanT** [comment]
I will try as soon as it's downloaded. It was certainly failing to connect at the begining and then ask for a connection which worked since I got the logs for this issue with it.

**Comment by TitouanT** [comment]
The installation perfectly worked with the last iso, thanks !
