### ISSUE TITLE
Cnchi can't download package list (667566)

### ISSUE THREAD

**Issue by capoderra** [Antergos/Cnchi#770]
### Problem:
Cnchi stops with error 667566 when it tries to download package list (metalinks)

### Steps To Reproduce:
1. boot live installer and wait for cnchi to update
2. after successful update, choose openbox as DE
3. at about 70%, installer halts with error 667566

### Log Files

- Link to /tmp/cnchi.log output.
https://hastebin.com/afonocegay.scala
- Link to /tmp/postinstall.log.
https://hastebin.com/qavodugufo.rb

### Additional Notes:
using latest iso "antergos-17.6-x86_64" on 2017.06.29

**Comment by jkw** [comment]
Same here, but error numbers **668544**.

**Comment by karasu** [comment]
Hi!

Thanks for reporting this. Sadly, webkitgtk package got renamed, and it's a dependency of antergos-welcome.

I've updated the antergos-welcome package, but it will take some time to all the mirrors to update. Please, try it again in a few hours.

https://github.com/Antergos/antergos-packages/commit/5c9a89e8b94d16eff4b7b90b182920e110c2e4e6

Cheers!

**Comment by jkw** [comment]
Is there no way to manually force change it in the code from the installer?
Sitting here with a brand new Lenovo Yoga 900 that wants Antergos! 😁

Den tors 29 juni 2017 22:06karasu <notifications@github.com> skrev:

**Comment by karasu** [comment]
Yes, it is.

From the ISO:

1. Edit `/usr/share/cnchi/data/packages.xml` file and remove all lines like this one:
 `<package>antergos-welcome</package>`

2. Run cnchi again this way:
`sudo -E cnchi -dv -p /usr/share/cnchi/data/packages.xml`

This will not install antergos-welcome package, which is not really important.

Cheers!

**Comment by jkw** [comment]
Cheers @karasu, seems to work just fine now. Downloading packages for Gnome. :-)
