### ISSUE TITLE
Cant press continue button at advanced installation mode

### ISSUE THREAD

**Issue by Ugur22** [Antergos/Cnchi#772]
### Problem:
Im trying to install Antergros in my laptop but I cant seem to get past the  advanced installation mode point. The continue button stays geyed out even though I created an
 ext4 boot partition and a swap partition.
![screenshot from 2017-07-01 14-14-37](https://user-images.githubusercontent.com/5570233/27761960-f203adf8-5e67-11e7-91a8-0886e12f5edd.png)

### Steps To Reproduce:
1.choose  advanced installation mode
2. create a ext4 partition marked as ¨/¨
3.create a swap partition marked as swap

**Comment by stratus-ss** [comment]
I could not reproduce this. I downloaded the latest ISO from torrents as of July 3, 2017. I took a brand new laptop which previously had windows on it and installed Antergos on it.

If you try launching cnchi from the command line or look at the logs, are there any errors produced up to this point?

**Comment by sims1253** [comment]
There is a missing mount in your checklist for the efi boot stuff. If you installed windows already, it looks like that for me, mounting dev2 as /boot/efi might work if i remember correctly.

**Comment by Ugur22** [comment]
Hey guys thanks I forgot to tell you all that I figured it out the problem last week. like  @sims1253 said I had to  mount dev2 as /boot/efi. Thanks for the effort anyway guys :) I wil close the issue.
