### ISSUE TITLE
[0.14.293] Error : There are no packaging issue that would interfere with installation" 

### ISSUE THREAD

**Issue by thiphariel** [Antergos/Cnchi#773]
### Problem:
New installation is impossible with the new update 0.14.292 / 0.14.293

### Steps To Reproduce:
1. Run a fresh install and let Cnchi update itself to 0.14.293
2. Go to "System check" panel
3. See the red error "There are no packaging issue that would interfere with installation"

### Additional Notes:
0.14.289 works great yesterday.
I'am using Antergos minimal ISO, if it may help.

**Comment by karasu** [comment]
@lots0logs 😀

**Comment by karasu** [comment]
@thiphariel thanks for reporting it. It's odd, as it is working here. Let me do some checks.

**Comment by thiphariel** [comment]
@karasu No problem. I update the issue, as it doing the same error with 293 ^^

**Comment by thiphariel** [comment]
Ok. I may have a problem. I try to run ```cnchi -n``` to bypass system check, and one of my SSD is not recognize (It was yesterday when I tried with 289)
I investigate this and come back to you :)

**Comment by lots0logs** [comment]
https://antergos.com/wiki/install/pre-installation-checklist/
