### ISSUE TITLE
Cannot install Antergos in VM (Can't find these packages: mlocale )

### ISSUE THREAD

**Issue by fkopietz** [Antergos/Cnchi#775]
### Problem:
Trying to install Antergos in a VM (VirtualBox). After setting up my login name, hostname and password a popup comes up with `Cannot create download package list (metalinks).`
Then the installer terminates.

### Steps To Reproduce:
1. Try to install Antergos (in a VM)

### Log Files
- Link to /tmp/cnchi.log output: https://gist.github.com/fkopietz/1f44c10369d7cd23fce5eefe16017ca2

### Additional Notes:
`2017-07-22 20:04:32 [ERROR] metalink.py(124) create(): Can't find these packages: mlocale 
2017-07-22 20:04:32 [ERROR] download.py(145) create_metalinks_list(): Error creating metalink for package mlocale. Installation will stop
`

**Comment by ase1590** [comment]
same issue when installing in virtualbox. 

Cnchi log: http://ix.io/yDq
pacman-boot.log: http://ix.io/yDr

**Comment by karasu** [comment]
Yep, I'm sorry, my mistake.

https://github.com/Antergos/Cnchi/commit/10cfbc877bcd1978549ef2da8f12995fb947e5c5 should fix it.

Can you guys try it again?

**Comment by fkopietz** [comment]
Works again. Thanks and keep up the good work 👍

**Comment by ase1590** [comment]
can confirm, works!
