### ISSUE TITLE
Add linux-hardend and linux-zen

### ISSUE THREAD

**Issue by ZeroDot1** [Antergos/Cnchi#777]
https://www.archlinux.org/packages/community/x86_64/linux-hardened/

https://www.archlinux.org/packages/extra/x86_64/linux-zen/

**Comment by karasu** [comment]
I'm not sure I follow. Do you want us to add the option to install these kernels from the installer? If that's the case, I don't see it. "Standard" users won't need to change their kernel (in fact, it's better if they don't). Experienced users just need a `sudo pacman -S linux-zen` to install them and redo the grub menu with `sudo grub-mkconfig -o /boot/grub.cfg`.
