### ISSUE TITLE
ZFS option bug in GUI

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#782]
Hi,

I've noticed during last installation if I chose to configure a ZFS setup, pressed next and then went back to the previous screen to disable that option, the ZFS setup was already partially activated (by installing the software I think). It pulled up some errors during boot time which were related to ZFS.

Installing Antergos again without selecting the ZFS option, fixed that.

(@Earthmind at the forum reported this)

**Comment by JasonGantner** [comment]
Hi,

I unknowingly followed the same procedure and got this screen at boot:
![screenshot_antergos_2017-08-11_13 38 53](https://user-images.githubusercontent.com/2913153/29211621-70d9b080-7e9a-11e7-8f58-e56e9e706a80.png)

By removing the `quiet` option, we can see that it tries to import the `antergos` pool which obviously doesn't exist.

The system can boot if the option `zfs=antergos` is removed from the command line. It then gets stuck at this point:
![screenshot_antergos_2017-08-11_13 37 20](https://user-images.githubusercontent.com/2913153/29211595-4294897a-7e9a-11e7-8364-b0727b77edc8.png)

Two error happen at first: `ash: 1: unknown operand` and `ZFS: no hostid` as seen in the screenshot. Then there are two failures in the systemd init process but It's to fast to be read.

I hope this can help you.

**Comment by karasu** [comment]
OK. Tested. https://github.com/Antergos/Cnchi/commit/7529c5e6648adb0720af536e2dec799241a352fb fixes it. (cnchi 0.14.319) I'll close this. If any of you detects this again, please comment here.

Thanks for reporting this!
