### ISSUE TITLE
The "cannot create download package" for Ukrainian users

### ISSUE THREAD

**Issue by followcube** [Antergos/Cnchi#787]
### Problem:
The "cannot create download package" for Ukrainian users

### Steps To Reproduce:
1. try to install the system
2. get the error

### Possible solution:
If you are Ukrainian user, you may face the "cannot create download package" due to the first mirror which is automatically selected for you is based on yandex.ru domain (which is bloced by most of our ISP's)
Here's what may serve as workaround: 
1. nano /etc/pacman.d/antergos-mirrorlist
2. comment the row that contains yandex.ru domain (it should be first)
3. sudo -E cnchi -dv --disable-rank-mirrors

**Comment by karasu** [comment]
Thanks for sharing this, but maybe the forum (forum.antergos.com) would be a best place to share (more users will see it).
Thanks anyway!

**Comment by followcube** [comment]
Indeed, thanks! Could you please add it somehow? Or should I do that on my own?

**Comment by karasu** [comment]
@followcube I'll do it myself, thanks!
