### ISSUE TITLE
Missing possibility to install bootloader to separate disk partition

### ISSUE THREAD

**Issue by IevgenSobko** [Antergos/Cnchi#791]
### Problem:
During installation configuration, there is the only possibility to install bootloader to some disk.
But there is no possibility to install it to some specific disk partition.
I use separate grub partition and manage it manually because for testing and review purposes I have a lot of different Linux installations.
Antergos installer is the only system that doesn't allow me to install bootloader into separate disk partition and I need every time to recover my manually managed boot loader after Antergos installation.
For instance, I would like to install bootloader to /dev/sda8 instead of /dev/sda which is my main loader

**Comment by karasu** [comment]
Hi,

Sorry but GRUB strongly discourages installation to a partition boot sector or a partitionless disk as GRUB Legacy or Syslinux does. This setup is prone to breakage, especially during updates, and is not supported by the Antergos developers.

Such specific setup as yours has to be managed manually, I'm afraid.

Thanks for the suggestion, though!

**Comment by IevgenSobko** [comment]
Hmm... Why then most of the distributions provide such option?
I always do the reinstallation of boot loader to Antergos partition and never had any problems with updates.
I think the only case might be an update of the GRUB itself. In this case there might be issues if it tries to install itself into MBR of disk instead of separate partition.
