### ISSUE TITLE
Not booting after fresh install using KDE

### ISSUE THREAD

**Issue by kq01526** [Antergos/Cnchi#795]
Using antergos-17.9-x86_64.iso with updated Cnchi results in a non booting system after a fresh install with KDE.

When selecting GNOME, it boots fine after installation.

When selecting KDE, it does not boot after installation.

**Comment by karasu** [comment]
Did you choose the same harddisk setup? Did you use the same bootloader? Did you made any change to your BIOS? (like changing from UEFI to Bios legacy....)

Did you install proprietary drivers in one case and not in the other one?

It shouldn't have any effect which DE do you choose with the booting process.

**Comment by kq01526** [comment]
@karasu No, everything identical besides choosing between GNOME and KDE.

I've tried it in a VirtualBox VM.

Used following options during installation:

AUR enabled
Bluetooth Support enabled
Chromium Web Browser enabled
Firefox Web Browser enabled
LibreOffice enabled
Printing Support enabled
SSH Service enabled

Erase disk and install Antergos checked
Encrypt this installation for encreased security checked
Use LVM with this installation checked

Use the device below for boot loader installation = same as the one for "Select drive"

**Comment by kq01526** [comment]
@karasu For some reason it is working now.
