### ISSUE TITLE
German translation is not complete ?

### ISSUE THREAD

**Issue by killajoe** [Antergos/Cnchi#801]
### Problem:
German translation is not complete ?

### Steps To Reproduce:
1.choose Germa language on boot menu
2.start Live Iso and begin installation
3.text infos inside cnchi are mixed german and english: see screenshots

Are the german translation needs some help? i do not rememeber that this was like this before... 

Screenshots: 
https://imgur.com/a/1L0yK

**Comment by karasu** [comment]
Thanks for the warning. I do not know what has happened, as there are old strings that do not show translated... I do not test all translations, as you might imagine.

I'll look into it.

**Comment by killajoe** [comment]
i see this inside the translation:

#: cnchi/installation/automatic.py:248
**msgid ""
"Do you** really want to proceed and delete all your content on your hard "
"drive?"
msgstr "Wollen Sie wirklich fortfahren und den gesamten Inhalt auf Ihrer Festplatte löschen?"

and some like this:

, etc**.\n"**

also some of the **#: cnchi/installation/automatic.py:nnn** are not translated...

**Comment by karasu** [comment]
I'm sorry I didn't have time to check this. I've added your changes to master (need to be ported to 0.14.x). Will do it asap.

**Comment by killajoe** [comment]
no huzzle! it is not critical :) i only want to track what i find on my way....

**Comment by killajoe** [comment]
i can not do the change on transifex, because german translation is already completed there...
