### ISSUE TITLE
KDE installation fails with conflicting files

### ISSUE THREAD

**Issue by davidmehren** [Antergos/Cnchi#803]
### Problem:
Using the latest Antergos 17.10 ISO the installation with KDE fails with `Can't finalize alpm transaction: transaction failed, pm_errno 49 (conflicting files)`

### Steps To Reproduce:
1. Choose KDE during installation
2. The installation fails after downloading.

### Log Files
cnchi.log: https://paste2.org/3yGhfZOP

**Comment by zorzysty** [comment]
I'm facing similar issue. Trying to install Antergos 17.10 ISO with KDE results in Cnchi error 85785.

**Comment by tim241** [comment]
Same issue here, weird though,I've installed it a while back without any issues.

**Comment by zgwerby** [comment]
Identical issue. I have tried to install antergos-kde-setup from a base system, it has error conflicting package adwaita-icon-theme. Can I remove this dependency manually?

**Comment by awaism257** [comment]
I have tried installing the OS with KDE desktop and at the end of the installation I receive the error: 86272.

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-kde-setup/pull/18#issuecomment-334849372

**Comment by zorzysty** [comment]
@karasu Thank you for providing a fix. But please explain how can I use it to install Antergos with KDE right now using ISO available on Antergos website.

**Comment by karasu** [comment]
Have you tried recently? Latest antergos-kde-setup shouldn't try to install those icons.

If it still fails (because mirrors could need more time to update), you can follow @zgwerby instructions.

**Comment by zorzysty** [comment]
I just did and installation went successfully. Thank you. 
Although after booting it goes straight to black screen and full fan speed, but that's a different issue ;-)
