### ISSUE TITLE
[17.10] Installation fails when intel-ucode exists in /boot during systemd-boot install

### ISSUE THREAD

**Issue by retro-wertz** [Antergos/Cnchi#806]
### Problem:
When an existing intel-ucode.img exists in /boot (EFI) partition during a systemd-boot install, the installation will fail:
`pac.py(161) finalize_transaction(): Can't finalize alpm transaction: transaction failed, pm_errno 49 (conflicting files), [('intel-ucode', '/install/boot/intel-ucode.img', None)]`

### Steps To Reproduce:
1. have an existing intel-ucode.img in your EFI partition(whether its from an old Antergos install or other distro)
2. install in UEFI mode, selecting systemd-boot as bootloader type.
3. continue with installation 
4. should fail show the pac.py error above.

### Log Files
existing forum discussion here:
https://forum.antergos.com/topic/8059/failed-to-install-17-10-due-to-pm_errno-49-conflicting-files?page=1
cnchi.log -> https://pastebin.com/TpUR0SAq

### Additional Notes:
Happened when using 17.6 installer. Updated to 17.10 installer still have the same issue. Deleting intel-ucode.img prior to installating will not fail. This should probably safe to overwrite, unless there are different ucode available for different versions of intel cpu.

**Comment by karasu** [comment]
@retro-wertz thanks for reporting this. Any package installation will fail if a file from that package is already installed (that's pacman policy, and it's a good one). This has never been an issue as / (root partition) is always formatted.

@lots0logs I'm not sure how to proceed on this one. My first thought is to just check if file exists and delete it before installing... or maybe we should install `intel-ucode` with a force flag? What do you think?

**Comment by lots0logs** [comment]
@karasu 
>maybe we should install intel-ucode with a force flag?

:+1:
