### ISSUE TITLE
Display Manager choice in Cnchi?

### ISSUE THREAD

**Issue by kq01526** [Antergos/Cnchi#808]
@lots0logs @karasu I've seen quite a few issues where users have asked to switch to GDM for GNOME or SDDM for KDE and so on.

I saw that you were against it and that you wanted to have a unified DM across all desktops, i.e. LightDM for everything.

That being said: I have not seen anyone asking for it to be a user selection in Cnchi.

So, how about you let the user decide which DM to use upon installation?

So Cnchi could ask "Which Display Manager do you want to use?":

And then it offers a selection like this:

1. LightDM (Antergos default, comes with Antergos theming, works across several desktops)
2. GDM (recommended for GNOME)
3. SDDM (recommended for KDE)
4. LXDM (recommended for LXDE)

Thoughts?

Regards

**Comment by killajoe** [comment]
Four (4) dufferent DM's can cause much more problems then providing one, and supporting it.

**Comment by kq01526** [comment]
> @killajoe wrote:
> In my point of view, lightdm is the one we should support

Now that Canonical has switched from LightDM to GDM, LightDM seems to be pretty much unmaintained, see:

> @robert-ancell wrote in https://lists.ubuntu.com/archives/ubuntu-desktop/2017-June/004969.html :
> Where this leaves LightDM:
> - We continue to support LightDM for the supported Ubuntu releases.
> - We will support LightDM for use in the other flavours, though this is
likely to be limited to bug fixes from the Ubuntu desktop team.
> - Others are still welcome to contribute to LightDM.

So, it's quite baffling that Antergos goes with LightDM, especially considering that GNOME is the default desktop for Antergos.

**Comment by killajoe** [comment]
Yes Gnome is the default DE but Antergos providing KDE/MATE/Cinnamon/Openbox/Deepin by default.
Robert Ancell is talking about Ubuntu support for lightdm, i do not read that development of lightdm itself will stop. Antergos is made by mainly two developers, so it is about taking a simple solution.
But i can ot speak for developing questions on antergos.

**Comment by kq01526** [comment]
> @killajoe wrote:
> Robert Ancell is talking about Ubuntu support for lightdm, i do not read that development of lightdm itself will stop.

Please check what it says under "Author" and "Developer": https://en.wikipedia.org/wiki/LightDM

And please check who owns the repo: https://launchpad.net/lightdm

:slightly_smiling_face: :wink: 

So, as far as I can tell, @robert-ancell / Canonical devs / Ubuntu devs are (were) the main developers/contributors to LightDM, so, yes, he actually seems to talk about the stop of the development of LightDM altogether...

**Comment by lots0logs** [comment]
> so, yes, he actually seems to talk about the stop of the development of LightDM altogether...

That is not even close to being accurate. If you want to know the status of LightDM all you have to do is review its mailing list from the past few months. Its pretty clear that the project will continue. It'll be moving to Github soon which makes it even less likely that the project will die anytime soon (even if Robert were to check out---which, btw, he has clearly stated he has no plans to do so).

**Comment by lots0logs** [comment]
Regarding the original topic of this issue, @killajoe has correctly stated our POV. The only thing I will add is that most users won't know what a display manager is. Those that do should be more than capable of installing it themselves after the initial install :wink:

**Comment by tenten8401** [comment]
Wayland support has been an issue for a long while now while every other display manager has had no problem with it whatsoever, despite being a reported issue for over a year now on LightDM, despite them saying they'll support Mir and Wayland on the website. I personally agree with @kq01526 on this one saying it's probably not going to be maintained very heavily anymore now that Ubuntu isn't going to be using it...

**Comment by lots0logs** [comment]
Most official Ubuntu derivatives still use (and likely will continue to use) LightDM. There is no need to take any action at this time. LightDM is maintained and isn't going anywhere anytime soon.
