### ISSUE TITLE
17.10 - Can't install the required packages with KDE Plasma

### ISSUE THREAD

**Issue by tenten8401** [Antergos/Cnchi#809]
### Problem:
When installing KDE Plasma, the error "Can't install the required packages" appears.

### Steps To Reproduce:
1. Install KDE Plasma using live image

### Log Files
- cnchi.log: https://paste.ubuntu.com/25876946/
- No postinstall.log

Using a freshly formatted drive.

**Comment by SteelTitanium** [comment]
I'm also having issues attempting to install Antergos, MATE, Deepin and XCFE all failed with same error, same conflicting files in log too, if that has anything to do with it.

**Comment by robkli** [comment]
I am having this problem too, trying to install Gnome. Same error, same conflicting files in log

**Comment by karasu** [comment]
Thanks for reporting this. It's a problem with the antergos-desktop-settings package. Fixing it right now.

It will take a few hours to all mirrors to update with the new package

**Comment by karasu** [comment]
Package created : https://github.com/Antergos/antergos-packages/commit/50776cad2d7d37debeafc1ee6e210abdd7918b18
I'll leave this open until we confirmation that it's working. Please, give it a few hours before retrying.

**Comment by robkli** [comment]
Works fine for me now, first try. Thanks so much!
