### ISSUE TITLE
Error installing Deepin DE

### ISSUE THREAD

**Issue by jacktho** [Antergos/Cnchi#817]
### Problem:
I'm getting this error during the "Checking integrity..." of a Deepin install. See errors in the log.

### Steps To Reproduce:
1. Attempt to install Deepin with Cnchi

### Log Files
- https://paste2.org/HggBJJ4K

### Additional Notes:
I do not get this error when installing Gnome via Cnchi.

**Comment by DylanHobbs** [comment]
+1 
Getting the same issue with Deepin install. 

Gnome working for me too.

**Comment by Okma** [comment]
+1 
Also getting it with Deepin.

**Comment by oussaamaa** [comment]
+1

**Comment by karasu** [comment]
@lots0logs I need help with this one. These happened in the past. Looks like a key error but every time complains about a different package. It only affects Deepin installation, which is odd. Any hints?

**Comment by karasu** [comment]
https://paste2.org/2esXVthV

**Comment by lots0logs** [comment]
@karasu did you double check the `antergos-deepin-meta` package in the repo to make sure its signature is right?

**Comment by killajoe** [comment]
as i get another one failed:
```
2017-11-18 23:00:55 [DEBUG] pac.py(547) cb_log(): checking sha256sum for /install/var/cache/pacman/pkg/licenses-20171006-1-any.pkg.tar.xz
2017-11-18 23:00:55 [DEBUG] pac.py(547) cb_log(): returning error 34 from check_validity : Invalid or damaged package
```

**Comment by karasu** [comment]
licenses is from core (Arch). I really doubt there is a problem there... it should fail in all DEs.

About antergos-deepin-meta:

```

error: failed retrieving file 'antergos-deepin-meta-1.0-2-any.pkg.tar.xz' from repo.antergos.info : Maximum file size exceeded
error: failed retrieving file 'antergos-deepin-meta-1.0-2-any.pkg.tar.xz' from cinnarch.polymorf.fr : Maximum file size exceeded
error: failed retrieving file 'antergos-deepin-meta-1.0-2-any.pkg.tar.xz' from softlibre.unizar.es : Maximum file size exceeded
error: failed retrieving file 'antergos-deepin-meta-1.0-2-any.pkg.tar.xz' from mirror.nl.leaseweb.net : Maximum file size exceeded
error: failed retrieving file 'antergos-deepin-meta-1.0-2-any.pkg.tar.xz' from www.mirrorservice.org : Maximum file size exceeded
error: failed retrieving file 'antergos-deepin-meta-1.0-2-any.pkg.tar.xz' from mirror.de.leaseweb.net : Maximum file size exceeded
error: failed retrieving file 'antergos-deepin-meta-1.0-2-any.pkg.tar.xz' from eu.mirrors.coltondrg.com : Maximum file size exceeded
error: failed retrieving file 'antergos-deepin-meta-1.0-2-any.pkg.tar.xz' from mirror.alpix.eu : Maximum file size exceeded
error: failed retrieving file 'antergos-deepin-meta-1.0-2-any.pkg.tar.xz' from ftp2.nluug.nl : Maximum file size exceeded
error: failed retrieving file 'antergos-deepin-meta-1.0-2-any.pkg.tar.xz' from ftp1.nluug.nl : Maximum file size exceeded
error: failed retrieving file 'antergos-deepin-meta-1.0-2-any.pkg.tar.xz' from ftp.acc.umu.se : Maximum file size exceeded
```

**Comment by karasu** [comment]
@lots0logs I'm positive we faced this some time ago.... and you fixed it. 😬

**Comment by karasu** [comment]
I'll try to create a new release of the package

**Comment by karasu** [comment]
Build new version. Should work when mirrors get updated. Going to bed (so I won't be here to test, sorry).

**Comment by mackcoding** [comment]
I test installed Deepin on VMWare and it was successful. Looks like the issue is fixed. Thanks 👍

**Comment by killajoe** [comment]
i confirm deepin installation working again!
