### ISSUE TITLE
Selecting the "Firefox Web Browser" and "Printing Support" features doesn't allow Firefox to print

### ISSUE THREAD

**Issue by khbecker** [Antergos/Cnchi#818]
### Problem:
When selecting the "Firefox Web Browser" and "Printing Support" features in Cnchi during installation, it would be expected that Firefox could print after installation. Unfortunately, Firefox requires the package gtk3-print-backends to print. This should be installed if both features are selected.

### Steps To Reproduce:
1. Install Antergos and select "Firefox Web Browser" and "Printing Support" features during installation.
2. Configure printer with cups.
3. Open Firefox and open Firefox's Print window.
4. No cups printers are listed.

### Additional Notes:

Please install gtk3-print-backends too so Firefox can print.

**Comment by karasu** [comment]
Thanks for the warning... will update asap.
