### ISSUE TITLE
Antergos installer-Error

### ISSUE THREAD

**Issue by oussaamaa** [Antergos/Cnchi#820]
### Problem:
When i install antergos with deepin desktop an error appear in checking integrity:
can't install necessary packages cnchi can't continue with this error code :149692

### Log File
https://paste2.org/ePOxmxsI

**Comment by karasu** [comment]
https://github.com/Antergos/Cnchi/issues/817

**Comment by matgianesini** [comment]
Having this same issue with same error code since last week. Choosing different mirrors doesn't help. I'll try selecting a different WM (KDE instead of GNOME) and see if that works.
