### ISSUE TITLE
Cnchi fails installing gtk3-print-backends

### ISSUE THREAD

**Issue by mhann** [Antergos/Cnchi#821]
### Problem:
Cnchi 0.14.404 install fails with "Cannot create download package list (metalinks)." when "Printing Support" is ticked in the features menu.

### Steps To Reproduce:
1. Run cnchi installer
2. Keep clicking next keeping default options (Including the default Printing Support option in the features menu)
3. Run the install

### Log Files
- /tmp/cnchi.log: http://sprunge.us/hADP
- /tmp/postinstall.log: non-existent

### Additional Notes:

The change that broke this appears to be caused by this change from the arch repository about 22 hours ago at the time of writing: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/gtk3&id=54e7af64837e18355122e62ff565970620db3537

manually running pacman -S gtk3-print-backends gives:

gtk3 and gtk3-print-backends are in conflict. Remove gtk3-print-backends?

**Comment by karasu** [comment]
https://github.com/Antergos/Cnchi/commit/deafd24b2c2d7665d024544d8a9ae23acee91498

Thanks!
