### ISSUE TITLE
Cnchi fails to install on ZFS: cannot import, no such pool available

### ISSUE THREAD

**Issue by averyfreeman** [Antergos/Cnchi#824]
### Problem:
Antergos 17.12 full iso
Cnchi 0.14.404

Antergos Installer - Error
"Error running ['zpool', 'import', '-f', '-d', 'dev/disk/by-id', '-R', '/install', '6839709983655845479']: 
cannot import '6839709983655845479': no such pool available.

### Steps To Reproduce:
1. Select ZFS
2. Follow prompts
3. Watch fail to import /dev/disk/by-id

### Log Files
- Link to /tmp/cnchi.log output
https://paste2.org/eOkcGYZN

- Link to /tmp/postinstall.log.
No post install available since install did not complete.

### Additional Notes:
Same on MBR and UEFI - neither one work (Same result)
Tested on KVM and ESXi - neither one work (Same result)

Would be nice if ssh/scp were on the live ISO so I can copy the logs off the VM more easily...

**Comment by averyfreeman** [comment]
Additional information:

It looks like the zpool is being exported before having the OS installed on it.  I feel bad because I recommended that the zpool be exported *after* the OS is installed. 

Tried a couple commands:
# zpool create rpool /dev/sda3
/dev/sda3 is part of exported pool 'antergos_6wbo'

# zpool import -f antergos_6wbo
cannot import 'antergos_6wbo': no such pool available
 
Proposed solution: build # zpool export <pool name>  into shutdown script rather than inside Cnchi?

**Comment by killajoe** [comment]
track back to Antergos Forum: https://forum.antergos.com/topic/8602/feature-requests-for-installer-re-zfs

**Comment by karasu** [comment]
@averyfreeman it was Cnchi 0.14.404 or Cnchi 0.14.410 ? Because the change you suggested made it to 410 not 404.... can you confirm cnchi's version, please?

**Comment by averyfreeman** [comment]
You can see it in https://paste2.org/eOkcGYZN
Here's an excerpt
Line 1:[antergos@ant-17.12 ~]$ cnchi --version
Line 2:Cnchi (Antergos Installer) version 0.14.404
...
Line 164: 2017-12-06 22:36:41 [ERROR] process.py(135) run(): misc.extra.InstallError: "Error running ['zpool', 'import', '-f', '-d', '/dev/disk/by-id', '-R', '/install', '11555318824509751176']: cannot import '11555318824509751176': no such pool available"

**Comment by averyfreeman** [comment]
https://paste2.org/v9dm2JYe
Result of 0.14.410 complete cnchi install log using ZFS in KVM on non-virtio virtual drive

Great job!
will write more later
