### ISSUE TITLE
Corrupted PGP Signature When Installing Cnchi

### ISSUE THREAD

**Issue by keeganmilsten** [Antergos/Cnchi#829]
### Problem:
*error: cnchi: signature from "Antergos Build Server (Automated Package Build System) <admin@antergos.org>" is invalid*

### Steps To Reproduce:
1. Install Cnchi using `sudo pacman -S cnchi`

Thank you for all of your hard work, and hopefully this issue can be resolved shortly.

Thanks!

**Comment by karasu** [comment]
0.14.410-3 should fix this.

**Comment by keeganmilsten** [comment]
Yay! Thank you so much @karasu. 

I can't wait to test your new version of Cnchi...
