### ISSUE TITLE
Antergos style XFCE still not present after install!!!

### ISSUE THREAD

**Issue by killajoe** [Antergos/Cnchi#831]
### Problem:
Installing XFCE DE do not take antergos specific themeing e.t.c. after install

### Steps To Reproduce:
1. install Antergos and choose XFCE DE
2. reboot
3. login to xfce - greets you with xfce standard/default theming and settings.
numix icons not choosen, numix gtk theme not choosen, default aplications not inside the dock

There is no folder ~/.config/xfce

**Comment by LucaDev** [comment]
I can confirm your problem. Saw the exact same behaviour the last time I installed Antergos XFCE

**Comment by killajoe** [comment]
still

**Comment by killajoe** [comment]
still the same

**Comment by killajoe** [comment]
still

**Comment by karasu** [comment]
I know... I've done some work but it's still not finished. To be honest @faidoc did this a long time ago... and I don't really know where the %$·%& he stored those files.

Sorry for the delay... I've started a second job and as Gnome is our "official" desktop.... this has fallen behind. I'll try to fix this this weekend and get back to you asap ;)

**Comment by faidoc** [comment]
@karasu Is the postinstall.sh script still being used? because I can't find the set-settings script that file is calling from the Cnchi script folder

**Comment by karasu** [comment]
>Is the postinstall.sh script still being used?
Yes

>I can't find the set-settings script that file is calling from the Cnchi script folder
It does not call any set-settings anymore... and maybe that's the problem, dunno. Have you checked the 0.14.x branch? postinstall.sh has suffered a lot of changes.

**Comment by ssspacez** [comment]
Check other projects' code for ideas 

https://distrowatch.com/search-mobile.php?ostype=All&category=All&origin=All&basedon=Arch&notbasedon=None&desktop=Xfce&architecture=All&package=All&rolling=All&isosize=All&netinstall=All&language=All&defaultinit=All&status=Active#simple

**Comment by killajoe** [comment]
Still 3 issues:
* default themes not set (numix icons and numix gtk theme)
* whisker menu icon is not set to /usr/share/antergos/new-logo-square32.png
* background is empty should be default antergos or some xfce-antergos-wallpaper

**Comment by killajoe** [comment]
just make a pull request here:
https://github.com/Antergos/antergos-desktop-settings/pull/3

**Comment by killajoe** [comment]
Looks almost perfect now, only that window decoration is not working (is still xfce default)
