### ISSUE TITLE
Improve boot window/step

### ISSUE THREAD

**Issue by ghost** [Antergos/Cnchi#840]
### Problem:
I think the last page of the installer, the **boot window** that you can choose where to put the boot by clicking on a menu, is causing some confusion. It has happened with me, I'm probably just tired and didn't read it correctly or the page is not simple or didactic enough and maybe is causing confusion/wrong choices.

I imagine more people are making the same mistake. I was choosing the wrong option of boot and was not being able to install(in this case, to boot) Antergos.

### Steps To Reproduce:
I was clicking on the menu and choosing the pendrive to boot the system instead of the drive.
Details: https://forum.antergos.com/topic/8929/cnchi-0-14-410

**Comment by karasu** [comment]
New testing version of antergos-iso adresses this. Thanks for reporting it, though!

https://github.com/antergos/antergos-iso/tree/testing

@lots0logs last time we talked, it was just the background image that you didn't like, did you? If I change the image will you accept the change? (we can talk by email about this one if you prefer it)
