### ISSUE TITLE
Error 232123

### ISSUE THREAD

**Issue by postadelmaga** [Antergos/Cnchi#843]
Cnchi v. 0.14.410

### Problem:
Installation proceed till last package download but then I got the error 232123 "can't install necessary packages ..."

### Steps To Reproduce:
Try to installing antergos using both installer ISO ( minum and the big one):
- gnome enviroment
- china locale
- LVM 

### Log Files
This is the output of cnchi: https://paste2.org/xbvwenpB

### Additional Notes:
Should I submit the issue here or to Antergos ?

**Comment by killajoe** [comment]
> invalid or corrupted package

So may the pacman.log can say wich package?

**Comment by postadelmaga** [comment]
After 5/6 installation failed I installed manjaro in the meanwhile and gave the pc back to my friend so I cannot check it ... all installation process failed at the end so I lost 6/7 hours to in various attempt and I gave up.
did you try the above installation configuration ? does it work for you ?
Somebody can confirm the above is working fine I can do a test in VM just to help the project

**Comment by killajoe** [comment]
Gnome + LVM yes, but not with Chinese locale, but I can do testing it.

**Comment by karasu** [comment]
Mirror or server problem that has long been fixed.... closing.
