### ISSUE TITLE
Suggestion: change order of last two pages on the menu

### ISSUE THREAD

**Issue by mrcasquinhas** [Antergos/Cnchi#844]
The page where you put the username, etc, should not be the last page, in my opinion. It should change place with the previous, where we have a list of all things we choose before. And now it looks like we're starting to install.
When pressing save, kinda looks like we will have another page, so it should be the previous, so you know "Next" is to start the install. Pressing Save it starts to install and does not feel ok.

**Comment by killajoe** [comment]
i vote for this ;) as it will be more in a line...

**Comment by karasu** [comment]
This should be an easy one... I'll work on it asap

**Comment by karasu** [comment]
https://github.com/Antergos/Cnchi/commit/f1972859ff41b0cbfcefc60a6b95df859b86a494
