### ISSUE TITLE
Provide option to specify only https mirrors when cnchi auto configures

### ISSUE THREAD

**Issue by larrydewey** [Antergos/Cnchi#847]
### Enhancement Request

It would be really nice to specify only `https` for mirror generation when cnchi does the automatic configuration.

**Comment by karasu** [comment]
Hi,

Do you mean in the installation process or in the installed system?

**Comment by larrydewey** [comment]
Gustau,

In the installation process.

**Comment by karasu** [comment]
0.16.x uses https mirrors by default (Antergos).
0.17.x uses https mirrors by default (Arch and Antergos).
Closing.
