### ISSUE TITLE
Error: 974604 - can't install necessary packages - Cnchi can't continue

### ISSUE THREAD

**Issue by prakal** [Antergos/Cnchi#851]
### Problem:
I am unable to specify a LUKS encrypted root volume. When I follow the same steps but using an unencrypted ext4 volume, it works perfectly everytime, regardless of extra packages selected.

### Steps To Reproduce:
1. Install Antergos using cnchi with US-EN locale, auto rank mirrors
2. Specify a : 
    1. LUKS encrypted formatted root volume (mount at `/`)
    2. unencrypted, unformatted `/boot` and `/boot/efi`
3. Watch it fail with `Antergos Installer - Error`

### Log Files
- Link to /tmp/cnchi.log output: https://paste2.org/3FMUUeCA
- Link to /tmp/postinstall.log: couldn't find this file
- Link to /tmp/pacman.log: https://paste2.org/WLY9m6Mv

**Comment by karasu** [comment]
Hi,

I've seen this in your log:
```
2018-02-11 21:39:59 [INFO] slides.py(276) manage_events_from_cb_queue(): Installing linux (270/807)
2018-02-11 21:40:02 [ERROR] pac.py(567) cb_log(): problem occurred while installing linux
2018-02-11 21:40:02 [ERROR] pac.py(567) cb_log(): could not commit transaction
2018-02-11 21:40:02 [ERROR] pac.py(164) finalize_transaction(): Can't finalize alpm transaction: transaction failed, pm_errno 28 (transaction aborted)
```

So it cannot install the linux pacakge. It seems it cannot write into your boot partition (/dev/sda2):
```
2018-02-11 21:40:22 [ERROR] pac.py(567) cb_log(): could not extract /install/boot/vmlinuz-linux (Write failed)
```

and:
```
2018-02-11 21:35:30 [DEBUG] advanced.py(2176) get_changes(): Device /dev/sda1 will be , not relabeled, not formatted, mounted as /boot/efi and not encrypted.
2018-02-11 21:35:30 [DEBUG] advanced.py(2176) get_changes(): Device /dev/sda2 will be , not relabeled, not formatted, mounted as /boot and not encrypted.
2018-02-11 21:35:30 [DEBUG] advanced.py(2176) get_changes(): Device /dev/sda5 will be modified, not relabeled, formatted, mounted as / and encrypted.
```

Is sda2 already formatted by another os? If not it should be formatted as ext4, sda1 should be FAT32

**Comment by prakal** [comment]
Thanks for the response @karasu. I am dual-booting with Windows 10.  
In my setup:
- `sda1` is my `/boot/efi` partition (size: 260 MB , unused: 230 MB)
- `sda2` is my `/boot` partition (size: 16 MB, unused: 2.5 MB)
- `sda5` is my `/` partition (size: 123 GB) - to be formatted and encrypted

I had formatted `sda2` as a FAT32 volume, but I deleted my bootloader, so I had to do Windows 10 recovery and it boots up Win 10 now. If I reformat `sda2` as ext4, I wouldn't be able to dual-boot with Windows, right?

**Comment by karasu** [comment]
Hi,

Problem is that 16MB is not enough to store your kernel. You need to grow that partition to, at least, 512MB

You can use gparted to do it. Tell me if you need more help.

**Comment by prakal** [comment]
I see. I thought that my `/boot/efi` volume would store the kernel. Also, there's this info from the Arch Wiki:

> Warning: If dual-booting with an existing installation of Windows on a UEFI/GPT system, avoid reformatting the UEFI partition, as this includes the Windows .efi file required to boot it. In other words, use the existing partition as is and simply #Mount the partition.

Would expanding the volume result in having to format it? I can try it and report back.

**Comment by karasu** [comment]
Your EFI partition is sda1 and as you mention, you should NOT format it (or resize it).

I don't know for what that sda2 16MB partition is used in Windows, to be honest. I haven't used windows for a long time (latest I used was Windows XP).

Gparted should be able to resize sda2 and its filesystem without having to format it... but I'm not sure. It will warn you, though.

**Comment by prakal** [comment]
Yeah, I don't know either what that 16 MB partition is for. I'll do some more research, but any changes should be reversible. So do you suggest next steps:
- Resize `sda2`:
    - from 16 MB to 512 MB, and 
    - from FAT32 to ext4 (this will necessitate formatting)
Its a little late now, so I will do this tomorrow, and report back in this thread. Thanks @karasu!

**Comment by prakal** [comment]
I followed your suggestion, and created a new ext4 partition (could not resize `sda2` because adjacent partitions are non-empty) of 512 MB, and specified it as my `/boot` partition. Installation worked as expected with an encrypted root volume, and I was able to boot into my Windows volume thru GRUB. 

I appreciate your taking a look at my issue @karasu . I'll close this issue, since its resolved.
