### ISSUE TITLE
Can't install necessary packages. Cnchi can't continue. Error 990623

### ISSUE THREAD

**Issue by kinetoskombi** [Antergos/Cnchi#855]
### Problem:
Error while installing Antergos on a Dell notebook

### Steps To Reproduce:
1. Using Antergos Live ISO
2. KDE enviroment
3. Portuguese BR location

### Log Files
- Link to /tmp/cnchi.log output: https://paste2.org/8x9cEcyb

### Additional Notes:
Error code: 990623

**Comment by prajapatiravi257** [comment]
Try this out
1. check your network connection is stable while installing
2. update your installer first (only if you're not updating it)
3. retry one more time installing
4. if above doesn't works try downloading new ISO

**Comment by killajoe** [comment]
If you can try to use custom DNS server inside your Router from open DNS or the ones from Google, as some ISP blocking some of the mirror

**Comment by kinetoskombi** [comment]
I finally managed to solve the installation problem. Apparently, the problem was with the hard drive. I had to install Windows to fix the disk and then install Antergos. Thank you for your help!
