### ISSUE TITLE
wifi Broadcom BCM4313 no funciona en el live usb

### ISSUE THREAD

**Issue by MakuSensei** [Antergos/Cnchi#857]
### Problem:
*Replace this line with a brief summary of the problem.*
vengo a reportar este fallo que tengo hace largo tiempo. 
cada vez que quiero instalar antergos tengo que usar mi celular como hostpot para poder eliminar los paquetes broadcom pre-instalados y compilar los que se encuentran en aur. 
este mismo procedimiento lo tengo que volver a hacer después de instalar el sistema.
ojala puedan solucionarlo en alguna próxima ISO. hasta entonces la única alternativa que tengo es usar directamente Archlinux lo cual no requiero instalar ni modificar ningún paquete de broadcom ya que funciona sin problemas. 
###Steps To Reproduce:
1.
2.
3.

### Log Files
- Use a service like http://paste2.org/ to provide links to the logs.
- Link to /tmp/cnchi.log output.
- Link to /tmp/postinstall.log.

**Comment by karasu** [comment]
@lots0logs Should we update broadcom-wl package with each iso so it matches the iso's kernel version? 

@MakuSensei El problema es que el driver no está actualizado. Creo que lo más fácil es usar el paquete broadcom-wl-dkms (de los repositorios de Arch):

`sudo pacman -S broadcom-wl-dkms linux-headers`

y luego activar el driver:
```
sudo rmmod b43 b43legacy bcm43xx bcma brcm80211 brcmfmac brcmsmac ssb wl
sudo modprobe wl
```

Saludos!

**Comment by MakuSensei** [comment]
@karasu  me olvide de comentar en este hilo que entre pruebas he solucionado este problema con simplemente poner el comando "sudo modprobe brcmsmac"

**Comment by karasu** [comment]
OK! Supongo que el driver brcmsmac también funciona para tu wifi. Fantástico.

Saludos!
