### ISSUE TITLE
Freeze when selecting Gnome

### ISSUE THREAD

**Issue by piegamesde** [Antergos/Cnchi#859]
### Problem:
When selecting Gnome as DM and clicking on the "next" button, cnchi will freeze and won't be able to be killed. This does not happen all the time, and does not happen if you select the no dm option. Other dm's are not tested

### Steps To Reproduce:
1. Boot the latest full installation image
2. Go to through the install process and select Gnome as DM
3. Go to the next page

### Log Files
No errors. The last line when clicking on the button is:

    [INFO] desktop.py(231) store_values(): Cnchi will install Antergos with the 'gnome' desktop

### Additional Notes:

You can't kill it nor shut down the computer -- you have to power it off the hard way.
A workaround seems to be to add `nouveau.blacklist=1` to the boot parameters, even if it does not work all the times (more testing needed)

**Comment by contraexemplo** [comment]
I'm having the same problem, and it happens when selecting any of them. I suspect this has something to do with NVIDIA drivers as well. I installed Antergos normally on an older laptop without a GPU, but I have this problem with a newer laptop with a GeForce GTX 1050 Ti. Didn't try the workaround you mentioned, though, I'll see what happens.

**Comment by piegamesde** [comment]
@contraexemplo Funny, I have exactly the same graphics card and the drivers are only making trouble until now. Another thing that has worked sometimes is the `nomodeset` parameter (but I think it was with other live systems than Antergos where it helped).

Running the installer from VirtualBox on the same mashine is fine btw (at least in this point, the mirrors are still broken, preventing me from installing). In the end, I installed the base version and Gnome afterwards, manually copying the settings from the image.

**Comment by BaconatorNoVeg** [comment]
Have tried both these workarounds, but neither has worked for me. Are there any other workarounds for this? Also have a 1050 Ti.

**Comment by karasu** [comment]
`nouveau.modeset=0` parameter should do the trick.
Closing.
