### ISSUE TITLE
Cannot create download package list (metalinks). Error 1030118

### ISSUE THREAD

**Issue by apastors** [Antergos/Cnchi#862]
### Problem:
When trying to install Antergos in a dual boot configuration with Windows 10, I get the error number given in the title.

### Log Files
- Use a service like http://paste2.org/ to provide links to the logs.
- Link to /tmp/cnchi.log output: https://paste2.org/EcMMaf8D
- Link to /tmp/postinstall.log.

**Comment by triinoxys** [comment]
Fixed here: https://github.com/Antergos/Cnchi/issues/845#issuecomment-374779410

**Comment by killajoe** [comment]
@karasu  this can be closed, as it is solved

**Comment by apastors** [comment]
Thanks! And sorry for leaving the issue open. I have been using Antergos ever since and I love it. Keep up the good work! :+1:
