### ISSUE TITLE
cnchi.desktop  first-boot-hotfix.desktop are present on installed system

### ISSUE THREAD

**Issue by killajoe** [Antergos/Cnchi#867]
### Problem:
*Replace this line with a brief summary of the problem.*

### Steps To Reproduce:
1. install Antergos with current Antergos-ISO
2. reboot
3.  ` ls ~/.config/autostart/` shows :
`cnchi.desktop  first-boot-hotfix.desktop`

This files are supposed to run from Live and wrongly copiet to installed system over skel? or by another ....

**Comment by matheusfaustino** [comment]
Same "problem" here

**Comment by killajoe** [comment]
still the same:
![bildschirmfoto vom 2018-05-14 09-59-23](https://user-images.githubusercontent.com/16797647/39985071-8a187cce-575d-11e8-80d9-5ff718e6eff4.png)

**Comment by killajoe** [comment]
Comes from this one?
package antergos-desktop-settings:

https://github.com/Antergos/antergos-desktop-settings/tree/master/skel/.config/autostart

**Comment by karasu** [comment]
Yep. Will fix it when I have the time... Thanks!

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-desktop-settings/commit/fe15d80a8f3186ea953927609a475a6746523942
