### ISSUE TITLE
chromium-flags.conf causes chromium segfault

### ISSUE THREAD

**Issue by killajoe** [Antergos/Cnchi#870]
### Problem:
chromium-flags.conf causes chromium segfault after latest update

### Steps To Reproduce:
1. update system
2. start chromium in terminal 
3. this error is shown: `[1]    31966 segmentation fault (core dumped)  chromium`

### Log Files
- https://pastebin.ca/4016830
https://forum.antergos.com/topic/9677/chromium-is-broken/20

### Additional Notes:
correcting the default installed by Antergos installation   **chromium-flags.conf**
It has wrong user path inside:_

`--user-data-dir=/home/antergos/.config/chromium/Default --homepage=http://antergos.com`

After changing this to:

`--user-data-dir=/.config/chromium/Default --homepage=http://antergos.com`

chromium starts again...

**Comment by foutrelis** [comment]
Unless you're running Chromium as root, `/.config/..` won't work either (it's outside your `$HOME`).

In my opinion, `--user-data-dir` is not something that should be set in `chromium-flags.conf`.

**Comment by killajoe** [comment]
yes better to remove that file complete in my opinion.... as chromium per default also do not show home button

**Comment by lots0logs** [comment]
We're not setting any chromium flags on user installs IIRC, that's only on the ISO

**Comment by foutrelis** [comment]
It probably comes from here: https://github.com/Antergos/antergos-desktop-settings/blob/master/skel/.config/chromium-flags.conf

Is there a way to notify Antergos users that they need to remove the flag from their `chromium-flags.conf`? Maybe an announcement in the forums?

So far we've had a report downstream: https://bugs.archlinux.org/task/58269
And a bug filed upstream: https://crbug.com/834298#c4

I think Chromium 65 just ignored the unwritable directory and used the default `$HOME/.config/chromium` path.

**Comment by lots0logs** [comment]
:man_facepalming:  That was never intended to be on user installs. We'll issue an alert through our alert system to notify all users to remove the file.

**Comment by karasu** [comment]
@lots0logs Can you do the alert thingie? I will update antergos-desktop-settings now.

**Comment by lots0logs** [comment]
I'm still debating whether or not its better to just automate the removal of the file :thinking:

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-desktop-settings/commit/625b9625257d6921a4d6466a427b4f343dcffd7b

https://github.com/Antergos/antergos-packages/commit/14ca627e7525de5b7b46f2c67a0e73bd1e3d4ff3

**Comment by karasu** [comment]
@lots0logs It will not be removed automagically when antergos-desktop-settings is updated by pacman?

**Comment by lots0logs** [comment]
Hmm..Im not sure..TBH I havent had time to look at the improvements you made to the settings packages :grimacing:

**Comment by lots0logs** [comment]
@karasu Can you review this please? https://github.com/Antergos/antergos-packages/commit/33c5505df38d6ecd748f85cb6ba260d6d39c23a3

**Comment by foutrelis** [comment]
IMO you should only instruct users to remove the flags from their configs and not do it as part of an install script. Also, you shouldn't have to deal with `/etc/skel/.config/chromium-flags.conf` since it was removed by @karasu a few comments back.

FWIW, the `sed` command also seems to be incorrect (leaves `--d` behind):

    $ echo --user-data-dir=/home/antergos/.config/chromium/Default \
           --homepage=http://antergos.com | sed -r 's%user-data-dir=.+antergos.+%\d%g'
    --d

**Comment by lots0logs** [comment]
@foutrelis Please see my response here: https://github.com/Antergos/antergos-packages/commit/34aec004e5075c97d9e82dceca303bd3c153292c#commitcomment-28684538

Also just to be clear, the reason we have a staging repo is for testing. If the sed command was wrong then I would have caught that when I tested it from the staging repo.
