### ISSUE TITLE
[ feature request ] apply makepkg tweaks upon install

### ISSUE THREAD

**Issue by jmaris** [Antergos/Cnchi#871]
Hi, I wasn't sure where else to file this so i filed it here, please inform me if it should have been filed elsewhere

### Problem:
*Antergos does not come with optimal makepkg settings out of the box*

### Steps To Reproduce:
1. build a package with makepkg
2. notice only 1 CPU core is being used during compilation
3. Notice the same during compression

### Steps To resolve : 
Cnchi could make modifications to the makepkg.conf file : 

1.  Modify the makeflags to allow for threading ( `MAKEFLAGS="-j$(nproc)"` )
2.  Use threads for xz compression ( `COMPRESSXZ=(xz -c -z - --threads=0)` ) (0 = use as many threads as CPU cores)
3. Use pigz instead of gzip (for threaded (de)compression). Note that this would require the pigz package to be installed.

**Comment by karasu** [comment]
1 and 2 ok.
About 3:
From pigz man page:
```
Decompression can't be parallelized, at least not without specially prepared deflate streams for that purpose.  As a result, pigz uses
       a single thread (the main thread) for decompression, but will create three other threads for reading, writing, and check  calculation,
       which can speed up decompression under some circumstances.  Parallel decompression can be turned off by specifying one process ( -dp 1
       or -tp 1 ).
```
So I don't see a big advantage, tbh. And it also needs adding a package... so it will be a no for this one, sorry.
