### ISSUE TITLE
Process crashed in 'mkfs.f2fs'

### ISSUE THREAD

**Issue by KaminoDice** [Antergos/Cnchi#872]
### Problem:
Cnchi will be crashed in the process in mkfs.f2fs

### Steps To Reproduce:
1.Install Antergos Step by Step,
2.Choose exactly where Antergos should be installed,
3.Mount point '/' choose the filesystem "f2fs" and go on

### Log Files
https://paste2.org/tZhKLHvX

### Additional Notes:
`2018-04-23 12:04:16 [ERROR] fs_module.py(262) create_fs(): Error running ['mkfs.f2fs', '-l', 'Arch', '/dev/sda6']: b'\n\tF2FS-tools: mkfs.f2fs Ver: 1.10.0 (2018-01-30)\n\nInfo: Disable heap-based policy\nInfo: Debug level = 0\nInfo: Label = Arch\nInfo: Trim is enabled\n\t/dev/sda6 appears to contain an existing filesystem (ext4).\n\tUse the -f option to force overwrite.\n'`
`2018-04-23 12:04:16 [ERROR] advanced.py(2365) run_format(): Couldn't format partition '/dev/sda6' with label 'Arch' as 'f2fs': Command '['mkfs.f2fs', '-l', 'Arch', '/dev/sda6']' returned non-zero exit status 255.`
`[xcb] Unknown sequence number while processing queue`
`[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called`
`[xcb] Aborting, sorry about that.`
`python: xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.`

**Comment by karasu** [comment]
Thanks for reporting this. It seems we forgot to add the `-f`` parameter to mkfs.f2fs.

**Comment by karasu** [comment]
https://github.com/Antergos/Cnchi/commit/fcdc3103482e4a6a0d280ce30f5fa927b0960bdd
