### ISSUE TITLE
option --disable-rank-mirrors still aviable?

### ISSUE THREAD

**Issue by killajoe** [Antergos/Cnchi#873]
> `cnchi.py: error: unrecognized arguments: --disable-rank-mirrors`

**Comment by karasu** [comment]
Nope, it isn't. Now it's all done in the mirrors screen.
If you don't want to sort mirrors just select the option of "leaving them as they are"

**Comment by killajoe** [comment]
![bildschirmfoto vom 2018-05-01 09-44-20](https://user-images.githubusercontent.com/16797647/39465549-4345caec-4d24-11e8-93af-160d64f54fc2.png)
should be removed from readme then ;)

**Comment by karasu** [comment]
shit! Thanks!
