### ISSUE TITLE
Unable to install with latest ISO - “Cannot create download package list (metalinks)”

### ISSUE THREAD

**Issue by ghost** [Antergos/Cnchi#877]
Unable to install with latest ISO. The following error occurs and prevents installation:

“Cannot create download package list (metalinks)”.

**Comment by attilagen** [comment]
+1

**Comment by killajoe** [comment]
https://forum.antergos.com/topic/9751/unable-to-install-cannot-create-download-package-list-metalinks

**Comment by Noxbru** [comment]
Duplicate from #865.
