### ISSUE TITLE
Cannot create download package list (metalinks).

### ISSUE THREAD

**Issue by MinecraftPlaye** [Antergos/Cnchi#883]
### Problem:
Cannot create download package list (metalinks).
Error: none

### Steps To Reproduce:
1. Wait for Cnchi to update.
2. After Cnchi is updated, click through the installer and type in your PC Name etc.
3. Wait for error to pop up.

### Log Files
- [See revisions and comments!](https://gist.github.com/MinecraftPlaye/fd284d5da3f531ca946fa7c8ffcbfd8e)

### Additional Notes:
I selected the packages: Gnome, the firewall package, Firefox, SSH stuff, Bluetooth and AUR repositories.
As of yet, in the first few days after a new iso image got released I don't have any problems installing AntergOS, a few days later using the same iso I'm running into the above problems. 
Tested on different PC setups with different iso images (18.4, 18.3).
**EDIT:** The problem got tracked down to be a mirror error. It also seems that I can't select/see all mirrors as I can't scroll down on the mirror list.
https://pastebin.com/A9q29dzP

**EDIT 2:** Interesting enough, manually I can open the mirrors and download data from them, but Cnchi seems to fail there.

**Comment by killajoe** [comment]
@karasu  this can be closed, as it is solved

**Comment by karasu** [comment]
Thanks @killajoe !
