### ISSUE TITLE
Installation stops with unnamed error

### ISSUE THREAD

**Issue by chris109b** [Antergos/Cnchi#888]
### Problem:
*Replace this line with a brief summary of the problem.*

### Steps To Reproduce:
1. Boot up Live Media via USB on https://en.wikipedia.org/wiki/Dell_XPS#XPS_13_(9333,_Late_2013), legacy boot mode (default).
2. Connect to your Wifi
3. Install, leave everything use default options, but setup for German, Germany and enable Bluetooth support.

### Log Files
- Use a service like http://paste2.org/ to provide links to the logs.
- Link to /tmp/cnchi.log output.
- Link to /tmp/postinstall.log.

### Additional Notes:
![screenshot from 2018-05-24 12-13-50](https://user-images.githubusercontent.com/12845827/40485285-a20fef72-5f4d-11e8-9d54-8f8f51b47a84.png)
[cnchi.log](https://github.com/Antergos/Cnchi/files/2035260/cnchi.log)

**Comment by scoronado12** [comment]
Sorry to jump on your report. I've been having the same issue as well trying to install with KDE in US English. Would you mind posting your cnchi.log?

Here's mine just in case: https://gist.github.com/scoronado12/8023ae947a56e8cba903261c5e707de5

**Comment by hmhofman** [comment]
Same here.  
HP Envy 17 - ae120nd
Had to disable nouveau driver (like [here](https://antergos.com/wiki/hardware/graphics/bumblebee-for-nvidia-optimus/)) to be able to run the media. 
ISO loaded via [Easy2Boot](http://www.easy2boot.com/)
Tried Dutch and English installer. 
Tried the normal and the minimal LIVE ISO. 


I guess everything is in the log file: 
- [cnchi.log](https://paste2.org/mMGGZ2Xd)
- [Partitions and RAM](https://paste2.org/GVBKx63I)
- [hwinfo](https://paste2.org/LJZEdVWG)

![screenshot from 2018-05-24 14-02-23](https://user-images.githubusercontent.com/5918209/40490478-22881fa0-5f5b-11e8-8211-d25ea31e83cc.png)

Can anything be related to 

- (line 334) the blacklisted nouveau driver
- (line 338) the AUR, bluetooth, cups, ... feature
- (line 359) Conflicts list
- (line 364) pac.py(282) install(): Error reading group 'cinnamon' from the antergos repo db

Notice I have turned off any browsers, firewall, etc. 
I figured I'd install those post-install. 

Even when some package can not be installed, I have to reboot the LIVE ISO before I can try again. 
The installed does halts before it created the bootloader. 
I don't know of any way to ignore the error and continue. Is that even possible?

**Comment by karasu** [comment]
Hi, @chris109b @scoronado12 @hmhofman 
It looks like a mirror problem (again). We issued a lot of updates just today, so maybe some mirrors are not fully updated yet. Anyway, let me do some checks...

**Comment by patchispatch** [comment]
I have this same issue with Spanish installation and KDE. I've tried disabling all optional packages such as chromium or AUR, enabling all repositories, and still nothing. The problem shows when cnchi is checking integrity, but does not always fail in the same package.

**Comment by hmhofman** [comment]
Ran it again this morning (TZ=Amsterdam). Same result. 
I need to reboot the LIVE ISO every try. 
Read something about '-p'. Could that save me some time? 

Anyway, here's what I did the last time: 
Added the `modprobe.blacklist=nouveau` from [here](https://antergos.com/wiki/hardware/graphics/bumblebee-for-nvidia-optimus/) and removed the driver complete from the LIVE: `sudo pacman -Rc xf86-video-nouveau`

Then I ran `cnchi -cdvfiu -e kde -s bugsnag`.
The -i does not have the desired effect. So I'm not sure about the rest of the parameters. 

With all the tries, It could prove useful to store packages to a separate partition? (-c)

Choose Dutch language, US Int /w Alt-GR dead keys, KDE, AUR, Bluetooth, Steam. 
Set my dual boot, linked all the partitions to the desired mount point (see the log) and the bootloaded to the 2nd disk (don't touch the Windows bootloader please!)

Running the installer I see warnings:
- [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
- [DEBUG] hardware.py(270) __init__(): Driver Nouveau is needed by (0x03, 0x10de, 0x1d10)
- Gtk-WARNING **: ...

Here are my log files: 
[everything](https://app.box.com/s/lmtmg95m97z28s17h536rwbck7mp35wa)

**Comment by jose-sanchezm** [comment]
Same problem here. Is there any workaround to get at least a bootable system?

**Comment by Trybnetic** [comment]
Thanks @karasu for your efforts! Are there any news on this issue?

I am currently having the same Problem here on my ThinkPad L430. Hope my description might help:

Base installation a few days back worked fine. Now I am getting the above mentioned error independent of whether I am installing with Cinnamon as DE or just base. Neither the boot media I used some days ago, nor a new boot media with an 2 hours old image worked. Both times I checked the `sha256sum` and everything seemed to be fine.

Here the [logs](https://paste2.org/jVWbhFwJ) from the last attempt.

Hope it will work again soon!

**Comment by sumit-anantwar** [comment]
Today I had planned to reinstall my system.
Confidently enough, I formatted the drives and clicked on install...
And now I am left only with a Live Linux!
Guys, please fix it asap. I don't like Ubuntu!

**Comment by karasu** [comment]
Hi all,

I've just finished a base installation without any issues.
Please, give it some time until all mirrors are fully updated.
One option for you guys could be to change mirrors in the mirrors page, or at least leave them by default (do not let cnchi sort them for you if it is still failing).

**Comment by NLBuescher** [comment]
Can confirm, setting the mirror list to stay on default fixed this for me.

**Comment by hmhofman** [comment]
Seems to be fixed now. 
Still got a GRUB problem, though, but I guess it's not related to this, so, if everybody approved, we can mark this as 'Solved'

**Comment by jose-sanchezm** [comment]
It is for me. Yesterday I was able to complete the installation of GNOME even letting the installer to choose the mirror to use.

**Comment by patchispatch** [comment]
Worked for me too with KDE, thanks for solving it quickly

**Comment by karasu** [comment]
Thank you all for your patience and understanding.
