### ISSUE TITLE
Adding option to install power saving tools for Notebooks

### ISSUE THREAD

**Issue by killajoe** [Antergos/Cnchi#893]
### Problem:
Mobile devices needs basic powersavings installed by default, new users or unexperienced ones will be left with overheating / less battery times e.t.c.

### Steps To Reproduce:
1. installing Antergos
2. no basic power saving options are enabled by default

### Additional Notes:
https://antergos.com/wiki/hardware/power-saving-made-easy/
TLP and Thermald are simple to implement, as they do not need special configuration.

https://forum.antergos.com/topic/10006/cnchi-bug-hunting-and-enhancements-too/4
@karasu

**Comment by karasu** [comment]
https://github.com/Antergos/Cnchi/commit/44becb2286bb30efc6e3041cda24d6c3a3b85959
