### ISSUE TITLE
Initial location selection based on IP address

### ISSUE THREAD

**Issue by manuel-192** [Antergos/Cnchi#895]
### Problem:
*Currently we have to search for a list of countries to determine location in cnchi.*

### Steps To Reproduce:
1. Start the Antergos installer
2. Go to page where your location is asked

### Additional Notes:

Location could be guessed based on user's IP address. There are several databases and applications providing this information. For example, https://www.nirsoft.net/countryip/ database could be used.
Applications (like e.g. geoiplookup) do not always provide correct/accurate info.

**Comment by karasu** [comment]
https://github.com/Antergos/Cnchi/commit/f9edc90a2fd447b7e77170b64966344ba94db30e should do the trick.
