### ISSUE TITLE
Could cnchi help fixing UEFI/BIOS problems after install?

### ISSUE THREAD

**Issue by manuel-192** [Antergos/Cnchi#897]
### Problem:
*It seems that users are able to mix UEFI and BIOS boot mode, e.g. installing Windows in UEFI mode and Antergos in BIOS legacy mode. Then Antergos grub may not recognize Windows.*

### Steps To Reproduce:
1. Install Windows in UEFI mode.
2. Install Antergos in BIOS legacy mode.
3. Reboot, and Antergos grub does not recognize Windows.

### Additional Notes:
Note that this issue is not based on my personal experience, but on some users reporting similar issues. So the description may not be exactly correct/accurate, but the problem seems to exist anyway.

The idea is to use cnchi to fix only the boot mode, not installing anything else. Cnchi would need a new option to skip the normal install, and allow reinstalling the grub in correct (or user-selected) mode.

The user could do as follows:
- Boot the USB stick installer (on a system that already has Antergos installed in wrong boot mode)
- Use new cnchi option: only reinstall grub in correct/selected boot mode.

This may sound like extra work that shouldn't be needed in the first place. Better (and probably much easier) would be to prevent installing in the wrong boot mode, or at least loudly warn if user tries to do so.

**Comment by karasu** [comment]
>or at least loudly warn if user tries to do so.

That's the option I like. Will work on this asap.
