### ISSUE TITLE
[question] Adopt a Calamar

### ISSUE THREAD

**Issue by juancarlospaco** [Antergos/Cnchi#904]
### Additional Notes:

Hello, I can not find this specific topic, not trolling, so I made this issue.

Core Team is ~3 people, to maintain >60 Repos, on Arch that literally updates hourly, so:

- **Have you seriously considered using [Calamares](https://calamares.io/about/) instead of cnchi ?.**

Some observations:
- Can use Python 3.
- YAML config.
- [Tons of plugins modules](https://github.com/calamares/calamares/tree/master/src/modules)
- Has Tests, Docs, CI, etc.
- Does not depend on any Desktop.
- Lots of big Distros use it, like Manjaro, etc.
- Lots of open issues on cnchi are fixed on Calamares.

:thinking:

**Comment by ajaybhatia** [comment]
That's what I'm thinking of from very time. Core team you definitely need to switch to Calamares. It also has advantage of installing the distro in offline mode with no time. 

May be I'm going to make it possible if core team allows me and is busy in other things. I'm ready to contribute to the project with Calamares.

**Comment by killajoe** [comment]
As Antergos is currently do work on track down Bugs inside cnchi it is not the right time to ask for switching... and also cnchi is a baby of Antergos... and in my opinion it is good to have another one developed on the marked... as if all uses the same installer... that sounds like the chromium plage ;)
And the number of BUGS is relative... her eat cnchi there are lot a issues not realy related to cnchi itself, or askings for improvements..

**Comment by juancarlospaco** [comment]
@karasu Why is Antergos installation much more complex than Manjaros ? (that uses Calamares).
as you say that Calamares can not handle Antergos install, that means something is really complex to do to install Antergos, I mean if it works for Manjaro it should work for Antergos since kinda same base and all, nearly allowing copypasting or inspecting their code from their Calamares should do a nice base to work on Antergos own Calamares.

Maybe things improved a lot on Calamares since you last cheched?. 

BTW Thanks for not thinking I am trollin', sometimes there are cool frameworks out there that a dev doesnt know :smile:

**Comment by killajoe** [comment]
i just testet two archbased distros  (Antman, Swagarch)  that using calamares, and setup looks exactly the same inside calamares, same way they implement encryption, and also both offline installs, causing huge update after reboot, so using calamares is may a bit more easy, but Antergos allows much more different setups and is open to fit everyones needs, so it is self explanatory that it is a bit more complex.

**Comment by ergoithz** [comment]
This shouldn't be closed, we (antergos fans) are frequently having a hard recommending this distro because of the frequently broken cnchi: every installation I made in the last two years failed and I had to look for a workaround offline.

I really love cnchi and appreciate how much effort you all put on it. But IMHO the core team is too small to keep in track with issues and, come on guys, there is another broader solution you can contribute and take use of, and there is much more people working on it.
