### ISSUE TITLE
[suggestion] Alternative LUKS crypto

### ISSUE THREAD

**Issue by bryce-lynch** [Antergos/Cnchi#907]
The current disk encryption used in Antergos, Ubuntu and other distros is aes-xts-plain64, which is a good compromise in terms of security/performance.

I'd like to request an "advanced settings" menu that lets the user choose a different algorithm like Serpent, which is stronger, quantum resistant (afaik), and faster than AES when used with XTS' parallelization thanks to bit-slicing.

What do you think?

**Comment by killajoe** [comment]
as in the meaning of advanced, this will be very nice but as we can see all this is possible also without having this option inside the installer itself:

https://antergos.com/wiki/install/how-to-install-antergos-w-custom-lukslvm2-partitioning/

And it is not that hard to get this done... (only my 5 cents) 

To much options inside cnchi will make it more buggy and less easy

**Comment by bryce-lynch** [comment]
Actually, if I'm not mistaken it's only a matter of using a variable in auto_partioning.py so that instead of the hardcoded aes-xts-plain64 we can use serpent-xts-plain64 (e.g. choosing it from a dropdown).

IMO it's not something that can make cnchi buggy, and it would allow newbies to use a safer encryption algorithm in light of quantum attackers in the near future.

**Comment by karasu** [comment]
@bryce-lynch can you provide a link or a document that explains the differences between aes and serpent? I wouldn't be against changing one for the other, but I have to know why. Adding another option to be able to choose encryption algorithm is a bit too much (as @killajoe explained). We pretend Cnchi to be easy to use for newcomers.

**Comment by killajoe** [comment]
`cryptsetup --type plain --cipher=serpent-xts-plain64 --hash=sha256 --key-size=256 --offset=10  open /dev/mapper/plain1 plain2`

`cryptsetup --type plain --cipher=serpent-xts-plain64 --hash=sha256 --key-size=256 --offset=10 open /dev/sdaX plain2`

https://wiki.archlinux.org/index.php/Disk_encryption#Ciphers_and_modes_of_operation

https://wiki.archlinux.org/index.php/disk_encryption#Comparison_table

**Comment by bryce-lynch** [comment]
@karasu I have to admit, although Serpent **_is_** more secure than AES, I took for granted what I read that it was also faster in xts mode because of its bit-slicing implementation (papers: [1](https://pdfs.semanticscholar.org/9295/bc9c8ba121de375d7369d9b6e4bc46804c2d.pdf), [2](https://www.hyperelliptic.org/SPEED/slides09/kasper-aes_speedcc09_slides.pdf), [3](http://jultika.oulu.fi/files/nbnfioulu-201305311409.pdf)).

Various benchmarks such as [this one](https://crypto.stackexchange.com/questions/15091/why-is-serpent-faster-than-aes-in-this-benchmark) also reports better performance for Serpent, but on a i7-4510U based laptop I've just tried `cryptsetup benchmark` and it reported AES is 300% faster.

So I don't know if it's a good solution for all users or if this commit should be reverted just to err on the safe side. I'm sorry for any inconvenience I may have caused.

**Comment by karasu** [comment]
Hi @bryce-lynch 

Do not worry, I should have run `cryptsetup benchmark` myself. I've changed it again to AES. I will let this to be configurable. Thanks!
