### ISSUE TITLE
Sometimes,there is no reaction of the cnchi after click

### ISSUE THREAD

**Issue by matinvic** [Antergos/Cnchi#912]
### Problem: Sometimes,there is no reaction of the cnchi after click
*Sometimes, even if the GUI is active, but when using mouse to click it, it is no reaction. Then, the only way to leave the installer is pressing Enter key. * (I used Virtualbox to install it)

### Steps To Reproduce:
1. Set up all requirement as other Linux distribution in Virtualbox.
2. Start Cnchi and do some action. (Partition, chose language etc.)
3. There is a possibility to meet this bug.

### Log Files
No log file.

**Comment by LeoTindall** [comment]
I have this very consistently on every modal dialog when running under Virtualbox.

**Comment by killajoe** [comment]
yes same here it is a virtualbox issue...i do also have this on other distros inside, virtualbox

**Comment by karasu** [comment]
I overlook this one, sorry.

I always test Cnchi in a Virtualbox VM and I've never experienced this (I have some graphical glitches, though, related to using i3).

As it seems it's not a Cnchi bug, I'll close this one. Thanks for reporting it.
