### ISSUE TITLE
Cannot create download package list (metalinks) - hunspell-es

### ISSUE THREAD

**Issue by epestanamx** [Antergos/Cnchi#919]
### Problem:
Cannot create download package list (metalinks)
Error: None

### Steps To Reproduce:
1. Wait Cnchi updates
2. Select spanish language
2. Select your other region options
3. Select your partition options
4. Wait Cnchi rank the best mirrors
5. The error pops up when creating my user account

### Log Files
[Log File](https://paste2.org/zwE7bVc8)

### Additional Notes:
I used Cnchi 0.14.426
I selected Gnome Desktop, AUR, Bluetooth, LibreOffice, Linux LTS, Firewall

**Comment by karasu** [comment]
@epestanamx I can't reproduce it here. Anyway, let me do some tests.

**Comment by epestanamx** [comment]
I forgot to mention that I am installing Antergos in Spanish language.

**Comment by karasu** [comment]
Solved in Cnchi 0.16.x
