### ISSUE TITLE
Cannot create download package list (metalinks)

### ISSUE THREAD

**Issue by MyriaCore** [Antergos/Cnchi#920]
**Problem**
My issue seems to be the exact same as #918. The install process is fine until the 'create your user account' screen, when an error message pops up and the program closes:
```
Cannot create download package list (metalinks)
Please reference the following number when reporting this error: none
```

**To Reproduce**
1. Wait Cnchi updates
2. Select your region options
3. Select your partition options
4. Wait Cnchi rank the best mirrors
5. The error pops up when creating my user account

**Log Files**
[Gist](https://gist.github.com/MyriaCore/65a00cc0b455a3729e94c2d26c42e09a) containing...
- [/tmp/cnchi-alpm.log](https://gist.github.com/MyriaCore/65a00cc0b455a3729e94c2d26c42e09a#file-cnchi-alpm-log)
- [/tmp/cnchi.log](https://gist.github.com/MyriaCore/65a00cc0b455a3729e94c2d26c42e09a#file-cnchi-log)
- [/tmp/pacman-boot.log](https://gist.github.com/MyriaCore/65a00cc0b455a3729e94c2d26c42e09a#file-pacman-boot-log)

**Additional context**
I selected Deepin Desktop, AUR, Bluetooth, Chromium, Printer, Flash, Uncomplicated Firewall, and Steam + PlayOnLinux. I'm running cnchi version 0.14.426. I've tested it, and the error happens on both antergos-18.7-x86_64.iso and antergos-minimal-18.7-x86_64.iso.

**Edit:** Typo

**Comment by MyriaCore** [comment]
I've been digging through some of my logs, and I have a few notes that may be helpful. This warning pops up about ten thousands times a few moments before the installer breaks. This is once again similar from #918:
`metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db`

I also noticed in pacman-boot.log, I'm getting some weird errors the multilib database:
`error: could not register 'multilib' database (database already registered)`
Running `pacman -Syu` returns similar errors.

**Comment by MyriaCore** [comment]
So, [here's my pacman.conf](https://gist.github.com/MyriaCore/1655b5cdab1e302101efb3757de86f32), and it seems as though I've just completely over looked this. multilib is listed twice, so I'm gonna have to just get rid of one of them. The thing is, I never messed with it, or used a tool to make it like that, it just came broken.

**Comment by MyriaCore** [comment]
Just did more testing, deleting that seems to make it happier, but it doesnt get rid of the error! I'm still getting the same one. I've got no clue how to trace that specific error.

**Comment by MyriaCore** [comment]
Thanks so much! I don't think I have my mirror list file there, so when I get to my pc I'll upload those too.

**Comment by MyriaCore** [comment]
@karasu [here](https://gist.github.com/MyriaCore/1f5207c71d5b3c8d99de9dd7e9f64470) are all of my mirror lists after cnchi sorted them! Maybe this'll help you pinpoint the faulty mirror!

**Comment by karasu** [comment]
@MyriaCore Have you tried again?

**Comment by MyriaCore** [comment]
@karasu I ended up installing with GNOME, the install went all good. A few days later, I tried downloading deepin via the angergos-deepin-meta package and it worked. IDK if that's because of a difference between install-time and post-install, but [here](https://gist.github.com/MyriaCore/16dd31fe66211fabe8f159edfd9576e3) are my mirrorlists after the install process of GNOME and DDE.

All in all, it seems to be fixed. I'm all good here.

**Comment by merlerp** [comment]
I still get the error

**Comment by MyriaCore** [comment]
@merlerp can you post logs? Mirror lists, cnchi.log and your pacman.conf would be helpful.

**Comment by MyriaCore** [comment]
@merlerp have you retried / gotten any logs yet? I think my issue is gonna be similar to yours, but still unrelated, and I need to close this issue soon before it starts bogging down the issues page.

**Comment by DarkRedman** [comment]
I've seen that pacman.conf provides **[multilib]** twice (one more in the end of file)

Also I've digged in the Deepin issue and python code, I don't know where cnchi get installation instructions but first cinnamon repo doesn't exist anymore it should use [community] repository and install the package **deepin-session-ui** (which now provides the deepin-notifications package)

**Comment by karasu** [comment]
@DarkRedman Thanks!

We use meta packages to install the desktop environment, but with so many changes in Arch (packages get renamed or removed) we are going back to the old method, that is, specifying all packages in packages.xml

I'll update packages.xml asap.

Oh, the [multilib] apearing twice is an iso bug, not cnchi's.

**Comment by MyriaCore** [comment]
Yeah, I had noticed the multilib thing, but I figured the ISO guys already knew about that.

**Comment by DarkRedman** [comment]
@karasu You're welcome!

I see, indeed Arch packages can be a pain sometimes. It'd be interesting that when error of this kind occurs it shows a warning (or info ?) with the location of the packages.xml so we can try to fix somestuff on our own.

I'm aware of that for the [multilib]

**Comment by karasu** [comment]
>occurs it shows a warning (or info ?) with the location of the packages.xml so we can try to fix somestuff on our own.

Cnchi 0.16.x tells you which is the "faulty" package. Closing this.
