### ISSUE TITLE
Error to install kde-l10n-xx package

### ISSUE THREAD

**Issue by rplanchuelo** [Antergos/Cnchi#981]
**Describe the bug**
There is a error when cnchi tries to install kde-l10n-xx because these packages are deleted from Arch Repository

**To Reproduce**
1. Install Antergos with KDE Plasma in Spanish 

**Expected behavior**

**Screenshots**
[cnchi.log](https://github.com/Antergos/Cnchi/files/2314950/cnchi.log)

**Log Files**
-Attached
[cnchi.log](https://github.com/Antergos/Cnchi/files/2314957/cnchi.log)

**Additional context**

**Comment by rplanchuelo** [comment]
![imagen](https://user-images.githubusercontent.com/32977921/44532686-fc99c600-a6f3-11e8-9072-5de030239145.png)

**Comment by karasu** [comment]
Fixed: https://github.com/Antergos/Cnchi/commit/85a9f65bab9d1a3e451a7dd9fff586c1dc9647e6

Thanks for reporting it, @rplanchuelo

**Comment by rplanchuelo** [comment]
Very quick. Thanks a lot
