### ISSUE TITLE
Cnchi should prevent gnome from suspending

### ISSUE THREAD

**Issue by pbelanyi** [Antergos/Cnchi#986]
**Describe the bug**
The live system got suspended while the installer was running, I suppose by gnome, due to inactivity. When I woke the PC up, it didn't resume the installation, and grub was left in a broken state.

**Expected behavior**
Cnchi should prevent gnome from suspending while the installation is running.

**Comment by karasu** [comment]
It's already done in 0.16.x, that will be issued in September. I'll leave this open as a reminder
